### ISSUE TITLE
打造簡便unblock youku路由器(使用openwrt + privoxy)

### ISSUE THREAD

**Issue by karlcheong** [uku/Unblock-Youku#106]
記得很久前有人就問過 在路由器如何設置Unblock Youku
後來更有一篇教程, 通過squid來達成Unblock Youku功能

對於一般家居用的路由器來說,都是基於MIPS LE(Boardcom)或MIPS BE(Atheros)
unblock youku伺服器使用之Node.js對MIPS支援性很差, 很難用來運行轉發代理
而 squid 倒是可以在家用路由器運行, 不過一來squid設定複雜我不會設, 二來
我正好在 #80 中為了給Android也能解鎖, 用privoxy 運行轉發代理
可以直接把設定搬過來用, 所以這個教程使用的軟件為privoxy

要求:
已安裝OpenWRT系統的路由器

1 SSH進去路由, 然後輸入指令安裝 privoxy
    opkg update
    opkg install privoxy

2 把規則文件及basicsetting設定文件, 放到 /etc/privoxy

https://github.com/karlcheong/unblock_youku_privoxy_rules

3 輸入指令啟動 privoxy 
    /etc/init.d/privoxy start

(可選:)輸入指令, 使路由啟動時自動運行 privoxy 代理
    /etc/init.d/privoxy enable

4 把要解鎖的裝置設定代理為  路由區域網IP:8123

**Comment by akpotter** [comment]
感謝樓主的文章跟 rule, 昨天在家裡的 openwrt 測試 reverse proxy 成功了。
利用這個方法，小米盒子連上 openwrt router 也可以不需要改任何設定，收看 youku 等源的影片。
在安裝的時候遇到一些問題  拋磚引玉一下:

1. 預設安裝新版 opkg install privoxy 以後，用 /etc/init.d/privoxy start 開看起來會抓到 uci 的 config 而不是 /etc/privoxy/config，後來發現問題以後手動執行 privoxy /etc/privoxy/config 就成功了。

2. 想要在開機帶起來的話也可以將 "privoxy /etc/privoxy/config" 加入 /etc/rc.local 的 exit 前面行即可。

**Comment by bba56k** [comment]
ddwrt可以吗？ 能post一下你的详细步骤吗？
多谢

**Comment by karlcheong** [comment]
如果是只改dnsmasq 把特定域名指向我們的代理的話還好，
但想要架設privoxy／其他HTTP代理的話，
ddwrt 的方法會跟openwrt有相當不同。。

相比openwrt，因為ddwrt的系統分區是唯讀的，所以軟件包和設定只能放在路由內置jffs2分區／USB／samba上。
（路由內建jffs2分區空間和USB接口在便宜的路由幾乎沒有，因為系統分區已佔用了大部分空間，而用samba的話還不如把privoxy放到跑samba的機器上運行）
還有DDWRT是沒有預裝opkg管理器的，得手動安裝，比較麻煩也易出問題。

簡單來說，要用ddwrt弄privoxy的話，假設你的路由有足夠內置jffs2空間/USB記憶棒，我會這樣做：
1 安裝opkg，privoxy 和他們的依賴包以及privoxy的rules到jffs2分區，把dnsmasq的設定也放到jffs2
2 ddwrt中的dnsmasq設定中加入上面的addn-hosts, __還有下面額外設定使它不監聽 lo 本機介面__
`
    interface=<你的LAN區域網絡介面編號,一般是br0>
    except-interface=lo
`
3 在boot script 再運行一個 標準設定的 dnsmasq ，只監聽 lo 本機介面

**Comment by bba56k** [comment]
你的openwrt路由器已经自动代理了？ 任何连接的客户端都自动走unblock youku? 盒子上，什么也不用设置？

能把你参考的文章链接或者＠我一下吗？
我找个openwrt路由试试！

多谢

**Comment by karlcheong** [comment]
@bba56k 
我因為換了個 11ac 路由, 已經沒在用openwrt了, 
現在是用的一個 raspberry pi 在架設 (一個超微型ARM電腦), 
設定和192.241那個DNS代理基本一樣, 也是 dnsmasq+privoxy

在上面每一步我都解釋了目的, 所以你也可以通過自己的方法做, 能達成效果就可以
我參考最多的就是 
openwrt (opkg) http://wiki.openwrt.org/doc/techref/opkg
, dnsmasq 的 manpage http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
和 privoxy 的config/action/filter manpage http://www.privoxy.org/user-manual/index.html

**Comment by biankasyo** [comment]
@kukat 请教下我也是在N56U第三方固件上安装privoxy，但因没有/etc/init.d/privoxy不知如何启动，请问怎么弄好

**Comment by whuhacker** [comment]
@biankasyo 如果你是用的 OpenWRT 固件，可以使用官方的包管理系统进行安装
```
opkg update
opkg install privoxy
```

**Comment by biankasyo** [comment]
@whuhacker 多谢指教，本体固件是俄罗斯Padavan编写的改版华硕固件，自行安装entware后，安装privoxy，现已启动成功，已将basicsetting中的config及trust复制到etc/privoxy下，但不知为何8123依旧失败

**Comment by bba56k** [comment]
请问楼主的路由器型号？可以 推荐几款吗？ 谢谢

**Comment by biankasyo** [comment]
之前8123端口无法成功，是因为自行安装的opt环境绝对路径与basicsetting中的config路径不同导致privoxy启动失败，在修改config后8123端口方式已成功，在尝试进阶版时，同样遇到了与之前回复中相同问题因系统不同卡在了第4步，在Padavan固件中dnsmasq用的是系统/etc/resolv.conf，因此修改了/etc/storage/dnsmasq/dnsmasq.conf的配置文件，在其中添加addn-hosts=/opt/etc/privoxy/basehosts及server=8.8.8.8，目前通过http://uku.im/check检测为true，打开youku主页没有问题，但访问视频页面时提示Maximum number of open connections reached，不知问题出在哪里，还请赐教，多谢！

**Comment by ysuolmai** [comment]
貌似YOUKU已经更新了，这个proxy服务器不能用了。unblock youku插件还可以用（最近更新过）。求大神更新啊！

**Comment by sbeagle25** [comment]
請問這個方式現在還可以使用嗎
我照步驟做完之後還是無法看

**Comment by gmuskie** [comment]
Port 80 不能用啊！

3.18. Can I just set Privoxy to use port 80 and thus avoid individual browser configuration?

No, its more complicated than that. This only works with special kinds of proxies known as "intercepting" proxies (see below).

REF： http://www.privoxy.org/faq/configuration.html#PORT-80

**Comment by zhyjp** [comment]
if you are using version 3.0.23-3, you should change this file /etc/init.d/privoxy  line 113, 
change privoxy.privoxy to root.root, 
this solved my 'not able to listen port 80' issue.

**Comment by kenichan** [comment]
能post一下你的详细步骤吗？

**Comment by litan1106** [comment]
感謝樓主的文章. 昨天在家裡的 dd-wrt kong arm r7000 运用 entware-ng 測試 reverse proxy 成功了.
请教如何如何屏蔽广告?

**Comment by chuyee** [comment]
请问这个是不是只针对80端口的HTTP, 443的HTTPS可以用吗？
