### ISSUE TITLE
求支持迅雷离线网页版

### ISSUE THREAD

**Issue by JayXon** [uku/Unblock-Youku#188]
美国ip会自动跳转到看看首页
这里有提到，https://github.com/iambus/xunlei-lixian/issues/372

**Comment by JayXon** [comment]
今天突然发现又不行了
```
Remote Address:119.188.108.241:80
Request URL:http://lixian.xunlei.com/
Request Method:GET
Status Code:302 Moved Temporarily
```
```
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Wed, 02 Dec 2015 04:05:52 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Location: http://act.vip.xunlei.com/vip/2013/notice/
Expires: Sat, 05 Dec 2015 04:05:52 GMT
Cache-Control: max-age=259200
Via: c20d077
```

**Comment by zhuzhuor** [comment]
@JayXon 最新的更新代理了一些迅雷离线的 web 界面，我这边试了试已经可以正常登录页面和在网页上离线下载了（文件下载并不通过代理服务器）。另外没有处理在线播放的页面
可以试试看，有问题请再来反馈

**Comment by JayXon** [comment]
我试了一下3.0.0.7，依旧不行，看了一下 http://lixian.vip.xunlei.com/task.html 也302了，可能是因为我是会员所以网址不一样？
本来想本地添加一下这个网址测试一下还有哪些网址需要添加，结果 squid 403 了，貌似是你们的服务器上有限制？

**Comment by jkldgoefgkljefogeg** [comment]
http://lixian.xunlei.com/*
http://lixian.vip.xunlei.com/*
http://dynamic.cloud.vip.xunlei.com/*
http://cloud.vip.xunlei.com/*

**Comment by zhuzhuor** [comment]
@JayXon 
@jkldgoefgkljefogeg 

多谢！好吧，我把这些都加进去试试，看看服务器压力。
上次只加了一部分，怕流量比较大 https://github.com/Unblocker/Unblock-Youku/commit/1e080a0c2477e8a53340e9ca8441dd0fc3a9f655

**Comment by zhuzhuor** [comment]
最新版的扩展程序已经上传到 Chrome Web Store 了，等更新了再试试

**Comment by JayXon** [comment]
可以了，谢谢

**Comment by LilHayah** [comment]
请增加 gdl.lixian.vip.xunlei.com 这个域名。 最新发现迅雷离线时，点取回本地还是跳到了看看，看了一下，发现他取回本地的url使用了这个域名。

**Comment by jkldgoefgkljefogeg** [comment]
Why not use hosts file to set gdl.lixian.vip.xunlei.com? There are only 4 IP addresses (2 for China Telecom, 2 for China Unicom)

**Comment by yanggis** [comment]
Hosts file supports one IP address only.

**Comment by jkldgoefgkljefogeg** [comment]
If you want gdl to redirect to China Unicom CDN node, use hosts to set gdl to China Unicom server. 

You can find the IP to use with tools like this
http://ping.chinaz.com/gdl.lixian.vip.xunlei.com
