### ISSUE TITLE
在Android 3.x以上, 以Drony本地代理替代PAC自動代理設定

### ISSUE THREAD

**Issue by karlcheong** [uku/Unblock-Youku#259]
**注意：本文图中的地址已经不能使用了，新版 PAC 的地址为 `http://pac.uku.im/pac.pac`**

---

這篇是#80 privoxy本地代理的續篇
多謝@grjegreagjergjerja 在 https://github.com/zhuzhuor/Unblock-Youku/issues/80#issuecomment-40302850 推薦的drony本地代理
現在Android 通過drony也能 解析使用pac代理設置了

功能: 跟#80一樣, 各瀏覽器和影音網站的官方app均可解封(需再測試)，
一般不影響系統上其他apps正常使用。
在手機本身運行，解析使用pac代理設置，不影響上下載速度。

注意: 由於apps可能不使用系統代理設置等原因, 不是每個apps都能免root解封。
不能免root解封時可嘗試用proxydroid強制把所有連接都轉到drony (注意此時不能使用global proxy選項)

要求: Android版本 >= 3(HC), 如本身連接的網絡需要proxy連接外網則需自行修改pac文件

drony下載: https://play.google.com/store/apps/details?id=org.sandroproxy.drony

使用方法:
### 1. WiFi下:

開啟Drony 進入setting-wifi
![1_wifi](https://cloud.githubusercontent.com/assets/1787644/2690050/71a62076-c32b-11e3-99a4-996d816e95dc.png)
選擇你正在連接的WiFi網絡 / 需啟動Drony的WiFi網絡
![1_wifi2](https://cloud.githubusercontent.com/assets/1787644/2690059/077b5882-c32c-11e3-9266-3fe11c340aa4.png)
#### 3G下:

開啟Drony 進入setting-not listed network
![1_3g](https://cloud.githubusercontent.com/assets/1787644/2690114/6fc7b2bc-c32e-11e3-8a42-926871133561.png)
### 2. 修改script proxy 設定, 輸入pac地址 (類型可為http://, https://, file:///), 然後下載, 測試, 儲存設定

![2](https://cloud.githubusercontent.com/assets/1787644/2690113/51ca31cc-c32e-11e3-9588-7cf21e954d32.png)
![3](https://cloud.githubusercontent.com/assets/1787644/2690115/7ed5d6b2-c32e-11e3-8596-1c512a829687.png)
### 3. 修改proxy type設定 為script:

![4](https://cloud.githubusercontent.com/assets/1787644/2690122/e3a7db58-c32e-11e3-90c2-b0ffa9f049ef.png)
### 4. 啟動drony

![5](https://cloud.githubusercontent.com/assets/1787644/2690124/ff7d2734-c32e-11e3-9108-3dbaa24aa062.png)
### 5. 修改系統代理設定

WIFI代理設定, 進入你連接的WIFI網絡的內容:
![screenshot_2013-09-17-19-04-45](https://f.cloud.github.com/assets/1787644/1156557/ab93594c-1f8a-11e3-9c98-01b854a4a0d6.png)
![6_wifi](https://cloud.githubusercontent.com/assets/1787644/2690133/f32c7f60-c32f-11e3-9673-ea2b7886abc1.png)
3G代理設定, 進入你使用的APN的設定, 修改 代理和連接埠
![6_3g](https://cloud.githubusercontent.com/assets/1787644/2690136/43ed2332-c330-11e3-9b51-70ac5285a59e.png)

**Comment by wydy** [comment]
其实设置WIFI和蜂窝网代理哪个步骤可略去，现在Drony支持VPN模式不需要设置代理了
