### ISSUE TITLE
感觉可以把精简模式去掉，换成关闭模式

### ISSUE THREAD

**Issue by zhuzhuor** [uku/Unblock-Youku#339]
感觉精简模式目前没什么用了呢
我这里收到的用户反馈有一部分都是不小心切换成精简模式而自己没注意的

感觉可以弄成 Off, Normal, Redirect 三种模式
如果用户从 Off 切换回别的模式应该会自己手动刷新网页的吧，如果刷新不管用会不会多刷新几下。。。
或者模式切换的时候，我们扩展程序试试在后台用 API 清空一下 cache，然后 reload 一下页面?

**Comment by zhuzhuor** [comment]
现在看统计，转发模式的用户数比精简模式还要少
现在越来越多的网站在转发模式下也不起效了（只对 Flash 管用），感觉转发模式也会要退出历史舞台了

> ![screen shot 2016-03-20 at 10 57 35 am](https://cloud.githubusercontent.com/assets/928905/13905948/9788f8ea-ee8a-11e5-9119-d5ee9b75e731.png)

**Comment by yanggis** [comment]
1,475,589是日访问量吗？

**Comment by zhuzhuor** [comment]
@yanggis 貌似是一个礼拜的 1/10 的统计量，重新截了个图

> ![screen shot 2016-03-20 at 11 14 59 am](https://cloud.githubusercontent.com/assets/928905/13906160/260eb95e-ee8d-11e5-913e-404d1a48c15a.png)

随机只选取了 1/10 的用户来统计，不然会超出 Google analytics 的额度

* https://github.com/Unblocker/Unblock-Youku/blob/07b04580f695d171f1a1dce1afc6ea262acd6b4d/chrome/config.js#L303
* https://github.com/Unblocker/Unblock-Youku/blob/07b04580f695d171f1a1dce1afc6ea262acd6b4d/chrome/pages/js/analytics.js#L68

**Comment by kongyingtan** [comment]
精简模式至少bilibili还是很好用的。校园网本身有代理的情况下普通模式用不了啊。求千万别关

**Comment by zhuzhuor** [comment]
@kongyingtan 感觉绝大部分的人不会用到，可以把精简模式做成一个 advanced menu 里面的高级选项
普通用户看不到，需要用的用户可以手动去 advanced menu 里开启

**Comment by kongyingtan** [comment]
@zhuzhuor 谢谢大大。只要能精简模式幸存就好！

**Comment by Besezta** [comment]
@zhuzhuor 確實想要一個關閉模式，但不用把精簡去掉...多加一個按鈕？

**Comment by ckaise** [comment]
@zhuzhuor I want a disable mode too. 
If no one is working on this feature, I will code the chrome extension now.

**Comment by zhuzhuor** [comment]
最新版 chrome 扩展程序新加了 @ckaise 贡献的关闭模式，可以完全关闭扩展程序的 header/proxy/redirect 功能
另外，按照之前讨论的，转发模式现在不怎么能正常工作而且用户很少。所以在新版我也把转发模式隐藏了

等我 push 给一小部分用户看看反馈吧，没有什么问题的话 push 给所有用户

**Comment by Kara-ism** [comment]
@zhuzhuor  请求添加回转发模式(Redirect Mode)
因为一些因素，我必须配合Proxy SwitchyOmega或Proxy SwitchySharp使用
去掉转发模式(Redirect Mode)的Unblock Youku後同时搭配代理插件使用，在代理插件取得浏览器权限後会提示版权问题无法播放…

**Comment by zhuzhuor** [comment]
@Kara-ism 你可以试试精简模式

**Comment by Kara-ism** [comment]
@zhuzhuor 
你好，我测试了下，精简模式虽然不会有代理权限冲突，但在部份视频网站是无法播放的。
像是搜狐，还有现在封IP的爱奇艺是会提示版权问题的。
还请考虑下添加回转发模式(Redirect Mode)，谢谢。

**Comment by zhuzhuor** [comment]
@Kara-ism 感觉太多模式了不是太好
如果把转发模式和精简模式合并了怎么样，能 redirect 用 redirect，能只改 header 的就只改 header
于是就改成三个模式 Off, Non-Proxy, Standard

**Comment by Kara-ism** [comment]
@zhuzhuor 
我能理解作者想要简化模式以免造成困扰的想法，
不过我觉得转发模式(Redirect Mode)如果能保留下来还是比较好的，
给部份需要特别设定代理的使用者，
让他们选择在精简(Lite Mode：修改headers)或是转发(Redirect Mode)切换。
我觉得zhuzhuor可以为转发模式(Redirect Mode)设置在选项中，
勾选了才会在插件页面中显示转发模式的设置，如此一来也能简化模式以免造成困扰。

**Comment by zhuzhuor** [comment]
最新的 chrome extension 已经把 redirect mode 合并到 lite mode 了，专门作为给需要使用别的代理的同学们使用
于是在新的 lite mode 下，能用 header 解封就用 header，能用 redirect 解封就用 redirect 解封，比之前的单独 lite/redirect mode 都要有用一些

另外一些附带的好处：
1. 更改了 urls.js 的结构，现在各个 URL 的作用更加清晰
2. 现在的普通模式不再盲目地代理所有的 URLs，如果能只用 header 的方式解封（例如 b 站）就会只用 header 的方式解封

**Comment by zhuzhuor** [comment]
是不是要把 lite 模式做进高级选项的东西之后再考虑吧，这个 issue 就先 close 了

如果新版本 chrome extension 有什么问题，欢迎再开 issue 反馈，感谢
