### ISSUE TITLE
安装了AVAST!杀毒软件，视频看不了

### ISSUE THREAD

**Issue by ChaossysL** [uku/Unblock-Youku#369]
身在美国，今天给电脑安装了avast，就发现国内的视频看不了了，但虾米网的音乐还可以继续听。把杀毒软件关了就可以看视频了，求解决办法

**Comment by xurubin** [comment]
把Avast的邮件保护中的SSL扫描关闭即可解决问题。
Avast的SSL扫描应该是用proxy做MitM了。
http://worlddeity.pixnet.net/blog/post/185046513-2014-08-09-%E5%AE%89%E8%A3%9Dunblock-youku%E5%BE%8C%E5%84%AA%E9%85%B7%E8%B7%9F%E5%9C%9F%E8%B1%86%E9%82%84%E6%98%AF%E7%84%A1%E6%B3%95
