### ISSUE TITLE
乐视直播不能看

### ISSUE THREAD

**Issue by sampsonchen** [uku/Unblock-Youku#473]
乐视直播中的任何视频都不能看，倒不是因为仅限中国大陆地区，只是速度超级慢，只有3-4kb/s，偶尔也能缓冲出一个静止的画面

麻烦大神看一下！在http://live.letv.com/  选择任何直播中的视频都不行，直播完的回看就没有任何问题

本人在美国。

**Comment by zhuzhuor** [comment]
多谢反馈
但是缓冲速度慢的问题我们也没什么好办法来解决
视频的清晰流畅度取决于你的电脑和乐视的服务器之间的网络速度
如果让我们给国内的视频网站分别做海外的线路优化也不太现实

推荐你试试 Google DNS https://developers.google.com/speed/public-dns/?hl=en
访问网站时，会帮你连接最近的服务器，但是对你这情况的效果也是未知数

**Comment by sampsonchen** [comment]
速度慢这个问题只在看直播的时候才出现，其它的节目都没有问题。所以我想是不是直播的时候乐视对海外服务器做了限制？能不能想办法可以连上海外服务器呢？

**Comment by zhuzhuor** [comment]
@sampsonchen 我的感觉是，直播用的服务器经常变动不稳定，我觉得是因为直播这种活动本身就是经常变动的原因，见 #424 #218 。我猜测是乐视的这些直播服务器是临时弄的，没有完善地通过他们的海外服务器进行缓冲加速。如果是这种情况我们也没有什么办法

**Comment by Chasego** [comment]
在#424里提到的一点我不是很明白，他说“连接国内代理翻回国之后就可以看了”。连接国内代理后，速度不应该更慢的吗？为什么反而行了？还是本身网络的不稳定导致的偶然现象？

**Comment by sampsonchen** [comment]
我这几天在乐视连着看了N场的NFL还有英超，欧冠的直播。发现使用pac.unblockcn.com是可以流畅的看直播的。但是unblock youku就不行。。。虽然我知道这个网站宣传手段很恶心，我也不想公开发表在这，但是真没找到私信老大的地方啊。。。能不能技术上解决一下。。现在可以确定不是网速的问题，是某种验证方式不正确，不知道unblockcn是怎么做到的。老大研究一下干掉他们吧。。

**Comment by sampsonchen** [comment]
可以在直播列表里找一场直播试验一下我说的问题，那个直播列表都是北京时间，所以在西半球的人需要到之后一天的直播里找直播源。我不懂技术，只能提供我的观察结论

**Comment by sampsonchen** [comment]
@zhuzhuor 老大麻烦看一下我上面的反馈啊

**Comment by zhuzhuor** [comment]
@sampsonchen 收到，感谢
最近我刚搬家+入职比较忙，回复比较慢

@tommyzhaozbh @yanggis 你们有人能帮忙看看这个问题吗，多谢啦

**Comment by whuhacker** [comment]
他们是 letv.com *.letv.com 全部走了代理，比较粗暴

**Comment by zhuzhuor** [comment]
@whuhacker 这... 该说他们财大气粗呢，还是因为用户比较少呢

如果我们能找个范围小一点的 URL pattern，只代理 html 的估计也行

**Comment by sampsonchen** [comment]
@zhuzhuor 谢谢老大，辛苦了！

**Comment by yanggis** [comment]
@zhuzhuor, @whuhacker, 这个问题没有这么简单，能提供你俩的电子邮件吗？咱们可以私下讨论一下。

**Comment by zhuzhuor** [comment]
@yanggis 可以在 gitter 上给我私信 https://gitter.im/

**Comment by sampsonchen** [comment]
@zhuzhuor @whuhacker @yanggis 乐视有一个网络测速然后选择最快节点的功能（点开视频后在视频右上角的位置），我用了blockcn的pac之后依然是被乐视自动选了国外节点，以此看来似乎并不是完全走的国内代理，我的感觉应该是乐视有某种验证机制，通过了国内ip验证后就可以看直播了

**Comment by yanggis** [comment]
@sampsonchen, @zhuzhuor
我这两天看了一下乐视视频卡顿的问题，主要分两个方面，第一个就是乐视视频有一个自动配置视频服务器的功能，会根据用户的IP配置离用户最近的服务器，比如一个用户用的国内代理在黑龙江，那乐视视频就会分配它在黑龙江的服务器给这个客户，事实上这个客户是海外看的，去连这个黑龙江的服务去就会出奇的慢。
另外一个方面乐视直播是基于P2P的，所以要求客户量达到一定量才能播放流畅，所以比较热门的直播比如西甲和英超就会比较流畅，但是你要看日本的J联赛或者美国的超级碗等就会很卡。
这其实和我们对乐视的Unblock没有什么关系。凑巧的办法就是这个用作unblock的服务器刚好在上海，北京等乐视服务器比较好的地方，那你看直播就会凑巧比较流畅。
最后比较郁闷的问题是，乐视网有个让用户选择不同地点服务器功能，遗憾的是这个功能现在基本没用，即便是你选择了海外节点，你链接的服务器还是原来的那个服务器，并没有跳到海外节点上，所以还是会一直卡。

**Comment by ddlp** [comment]
同问，乐视体育直播全部没法看！
http://sports.letv.com/match/121673003.html#live/1020160301190209

**Comment by zhuzhuor** [comment]
@ddlp 多谢反馈

这直播地址比较随机，现在已经打不开了
但是这录像视频还可以正常播放 http://sports.letv.com/match/121673003.html#record/24804930
欢迎提供个之后的直播地址，我们时间允许的话可以在直播的当时看看问题

**Comment by xchen22** [comment]
@zhuzhuor 这场恒大的比赛就看不了 http://sports.letv.com/match/307425003.html#live/1020160301182922

**Comment by zmingxie** [comment]
我正在看英超直播，挺流畅的 http://sports.le.com/match/1006626003.html#live/1020160810175720

不过在iPad上解锁不了，看了一下PAC文件，没找到有http://sports.le.com/ @zhuzhuor 你有空能确认一下吗？

**Comment by ddlp** [comment]
我试了一下这个：http://sports.le.com/live/1020160808143817.html#live/1020160808143817

广告都不卡，一到内容就卡。

我香港宽频千兆带宽，下载一般10M+/S

**Comment by tommyzhaozbh** [comment]
@ddlp 你的那个视频我试了一下，回放的时候用的是香港的服务器，超清时速度可达2.5MB/s。但直播的时候用的是深圳的服务器，不知为何速度奇慢，可能本身直播用的服务器带宽不够。
PS：我也是用1000M HKBN的

**Comment by ddlp** [comment]
@tommyzhaozbh 
感谢师兄。可否私信微信号，方便联络交流

**Comment by tommyzhaozbh** [comment]
Gitter留言即可

**Comment by ddlp** [comment]
直播没得看。 速度为0

http://sports.le.com/match/1021701003.html#live/1020160828144753
