### ISSUE TITLE
新英体育 视频无法播放问题

### ISSUE THREAD

**Issue by Betcome** [uku/Unblock-Youku#586]
看到过有朋友提过新英体育的issue #373 #351 #353  但是使用时还是有些问题 特来请教

以下在使用unblock youku v 3.0.3 情况下测试
问题描述如下：
1.历史视频回播主页链接 
http://www.ssports.com/video/index.html 可以直接访问， 点击任何一个视频 
例如 这场比赛录像 http://ssports.smgbb.cn/play/1602118.html
点链接 没有代理会**超时**，但是如果使用国内代理 如VPN 则可以直接播放

2.比赛直播列表主页链接
http://www.ssports.com/shop/matchlist.html
例如 点选免费场次 http://ssports.smgbb.cn/live/live_16947688_1.html
点链接 没有代理会**超时**，但是如果使用国内代理 如VPN 则可以直接播放

希望能看一下 
谢谢

**Comment by yanggis** [comment]
这个貌似没太好的办法解决，因为它的验证服务器和视频服务器是同一个服务器，如果你要走代理，就意味着视频数据也会走代理，这对于个人来说可以，但是要是有个十几个人对同一个服务器这个干，服务器流量基本就跑光了。

**Comment by Betcome** [comment]
@yanggis 感谢回复 历史视频回播 一旦页面载入 开始播放 即使断掉链接也没问题 不知道它的检测在哪里出现 比赛直播还没有测试。

**Comment by yanggis** [comment]
点播我没试过，直播我试过，走代理一直可以播放，只要断开代理，立刻就断掉了。
