### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by yjcxy12** [uku/Unblock-Youku#588]
请问这个谷歌插件的界面改变要怎么测试？
另外想多做贡献，有qq群之类的么？

**Comment by zhuzhuor** [comment]
@yjcxy12 多谢你的 pull request！我这就试试

我争取最近写个 contributing guide/tutorial 吧，方便大家上手
没有 QQ 群...  实时聊天可以用 gitter.im
* https://gitter.im/Unblocker/Unblock-Youku
* https://gitter.im/zhuzhuor

你说的界面的改变的测试是指？
如果是指怎么测试本地修改的代码的话，可以在 chrome 里打开 chrome://extensions 页面，打开 developer mode，然后 load unpaced extension 来测试
另外，Chrome 官方的 extension dev guide 可以看这里 https://developer.chrome.com/extensions

> ![screen shot 2016-02-05 at 10 47 03 pm](https://cloud.githubusercontent.com/assets/928905/12865195/1196c0b0-cc5b-11e5-8cd6-9d07d956bc0d.png)

**Comment by zhuzhuor** [comment]
噢~如果你问的是怎么测试不同 locale 的话
Mac 上直接修改系统的语言，然后重启 Chrome 就好了
Windows 上好像直接在 Chrome 里修改 http://superuser.com/questions/363408/how-do-i-change-my-chrome-language-back-to-english

**Comment by Gisonrg** [comment]
哇我前天刚想fix这个issue，没想到被抢先了 :smile:  

谢谢你们，非常实用的插件！希望以后也能有机会贡献一些代码 :)

**Comment by yjcxy12** [comment]
@zhuzhuor 目前对Proxy和Chrome extension没什么经验，准备给js文件添加单元测试，并慢慢改成es6，不知这个是不是希望改善的feature？

**Comment by zhuzhuor** [comment]
@yjcxy12 非常感谢！这些非常需要！

@Gisonrg 谢谢！超级欢迎！

**Comment by garfee** [comment]
进来声援一下。
后面有哪些feature、issue要解决？可以list一个出来，大家一起贡献。

被攻击后，有采取过一些措施吗？

**Comment by zhuzhuor** [comment]
@garfee 
感谢！现在的 issue list 有一些现有的问题，你要是感兴趣可以看看。
另外有一部分是用户在 [Google Group](https://groups.google.com/forum/#!forum/unblock-youku) 上反馈的不能看的问题，比如 @mc16888 昨天就迅速解决了一个用户新提出的问题 https://github.com/Unblocker/Unblock-Youku/pull/599

被攻击之后增加了一些服务器，改进了服务器架构，用了一些 anti-ddos 的服务器

@yjcxy12 @Gisonrg @garfee @tliu57 @tommyzhaozbh @mc16888 @xin-zhang 
我这个周末争取写个 contributing guide 吧，也列一列之后想做的东西
不知道大家最想看到什么样的内容：1. 项目介绍和结构 2. 需要的功能和改进 3. Chrome extension 开发教程. 4. ?
我在想可以写成 blog 的形式，不知道你们觉得这样好吗，可以长期更新，也可以有 guest posts

**Comment by Gisonrg** [comment]
@zhuzhuor 
我觉得比较重要的是1. 项目介绍和结构 和 2. 需要的功能和改进. chrome extension的话有官方tutorial可以参考

**Comment by garfee** [comment]
@zhuzhuor @Gisonrg 
非常赞同，1,2比较重要，3的话大家自己可以搞定。

**Comment by alannesta** [comment]
@zhuzhuor 很好奇你是怎么维护url.js里庞大的url列表的？是否有什么自动化的机制定期抓取？还是各大视频网站的url都一直想对固定？

**Comment by zhuzhuor** [comment]
@alannesta 主要都是大家帮忙维护的，很多人帮忙添加过规则 https://github.com/Unblocker/Unblock-Youku/commits/master/shared/urls.js 
的确现在都是靠发现问题后手动更新才行
如果能用 selenium 之类的自动测试的话就好了，欢迎懂这个的朋友给提提想法

**Comment by zhuzhuor** [comment]
最近刚开始写这个 contributing guide，这两天突然有点忙还没写主体的部分，争取这周末之前搞定
https://github.com/Unblocker/Unblock-Youku/blob/master/contributing.md

另外 Github 今天开始支持 issue/pull request 的 template https://github.com/blog/2111-issue-and-pull-request-templates 感觉也是个非常及时的功能，我们也可以试用下

**Comment by sijincao-ad** [comment]
@zhuzhuor , 谢谢回复。最近捣鼓了一下代码，发现server.js只是redirect server的代码，不知道secure.uku.im这个proxy server的代码也是node写的吗？可不可以也可以放到项目中来？

**Comment by zhuzhuor** [comment]
@sijincao-ad 普通模式的代理服务器是用的开源的 squid，配置方法可以见我们的 wiki https://git.io/vzmmZ
其中 squid 的 url 配置文件其实也是用 redirect server 的代码生成的，所以说基本上所有的东西都是开源的

不过你提了个非常好的点，写 contributing guide 的时候我们注意提一下 squid 这个

**Comment by alannesta** [comment]
@zhuzhuor , 多谢指点。上面那个账号也是我的哈哈(公司用的)
建议能有一篇local dev environment setup的guide。现有的几篇比较分散，我的理解的是:  [让Squid带有Unblock Youku功能](https://github.com/Unblocker/Unblock-Youku/wiki/%E8%AE%A9Squid%E5%B8%A6%E6%9C%89Unblock-Youku%E5%8A%9F%E8%83%BD), [代理服务器设置示例](https://github.com/Unblocker/Unblock-Youku/wiki/%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%BE%E7%BD%AE%E7%A4%BA%E4%BE%8B) 两篇结合在一起可以实现本地run一个local server (server.js)，在setup squid形成一个完整的环境。[在美团云架设自己的 Unblock Youku 代理服务器](https://github.com/Unblocker/Unblock-Youku/wiki/%E5%9C%A8%E7%BE%8E%E5%9B%A2%E4%BA%91%E6%9E%B6%E8%AE%BE%E8%87%AA%E5%B7%B1%E7%9A%84-Unblock-Youku-%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E5%99%A8) 这一篇是在默认使用unblock-youku chrome插件的情况下单纯的配置一个proxy server (实际上还是要先访问secure.uku.im:993 这个server再由这个server转发请求到自己配制的proxy server?)

如果能有一篇开发环境的setup guide就更好了

**Comment by zhuzhuor** [comment]
`让Squid带有Unblock Youku功能` 这篇文章是 @tywtyw2002 写的，现在正式的服务器架构还是很简单的
1. 普通模式 -> squid 代理服务器
2. 转发模式 -> Node.js 转发服务 (-> squid 代理服务器)

你说的本地开发环境的 setup guide 这个也很好，我想想怎么写比较好

另外我最近也在想，我们的 prod 服务器 url 限制比较严格，不方便用来做开发调试
可以尝试写个脚本，去某些网站上抓取公开的国内 IP 的代理服务器，然后方便大家调试使用
