### ISSUE TITLE
忍无可忍！对unblockcn不实指控的澄清说明

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#589]
早在去年8月，我们的服务器就开始受到各种攻击，与此同时，网上有关“unblock youku更名为unblockcn”的消息传得到处都是。

> ![006btq1zgw1eusm1snuxnj30gt0m9n7c](https://cloud.githubusercontent.com/assets/8757104/12864870/e8a6d886-ccd5-11e5-8171-d6fcab090fa3.jpg)

这则消息导致大量不明真相的用户统统跑去安装，结果卸载之后各种手尾要收拾。

> ![qq](https://cloud.githubusercontent.com/assets/8757104/12864889/5e73a9ae-ccd6-11e5-90f1-c7e5431e1ff9.png)

也因为这些冒充，导致不少用户向我们投诉说我们什么时候搞起流氓软件。
（下面这图是用户给我们反馈的信息，可以看到网页的标题竟然写着unblock youku）

> ![6c23f844-cc8e-11e5-934f-b3ebe2812c50](https://cloud.githubusercontent.com/assets/8757104/12864901/ec520090-ccd6-11e5-9b72-babd92a7747a.png)

由于不断遭受网络攻击，为了维持大家的免费服务，我们不得不选择以自愿捐款的形式减轻财政负担。恰巧在此前，Unblock Cn的服务器也被攻击了。此时，unblockcn居然指控我们说我们在攻击他们的服务器，并污蔑称我们在利用同情心去骗取大家捐款以攻击他们的服务器。

> ![qq](https://cloud.githubusercontent.com/assets/8757104/12864954/4a8d51bc-ccd9-11e5-9b68-c4bef688bc8a.png)

面对这些不实指控，我们认为我们必须要作出一些澄清，以免引起更大的误会：

1. **我们的所有插件绝无任何恶意代码**
首先，作为一款开源插件，我们的所有源代码都公布在github平台，任何人随时都可以查看我们插件究竟有没有任何劫持用户页面代码或者是对用户计算机有害的代码。而且，我们的插件是经过谷歌人工审查的，在发布新版的时候都会由谷歌的技术人员对我们的代码进行审查。我们不是在吹牛的：之前各位在安装3.0系列版本的时候跳出要求更高权限就是因为我们在更新的时候会跳出捐款页面。而这些如果没有技术人员的审核，又怎么会有这些东西呢？

2. **我们从未，日后也不会去攻击别人的服务器！**
我们背后没有任何的财团支持，服务器的所有运营开支都是由原作者 @zhuzhuor 一个人负担的，以至于前段时间服务器被大规模攻击的时候，新添加服务器的成本都是由他一人负担。要进行这些持续的大流量攻击，成本绝对不低。如果我们有这样的钱去攻击人家的服务器，倒不如省下这些钱去建立更多服务器，为大家提供更好的服务不就更好？更何况，攻击他人的服务器是违法行为，我们不会这样做。再者，攻击他们的服务器对我们有什么好处呢？我们也不会从中获得任何金钱利益，至于用户数什么的那压根就是虚的：要那个干嘛呢？又不能当饭吃。

在此，我们对unblockcn发表这种不负责任的言论深感愤怒，因为我们也是网络攻击的受害者。同时我们也对这种以各种冒充来蹭名气的营销手法表示不满。我们强烈要求unblockcn方面收回有关言论，我们从不反对或者打击其他提供类似服务的公司或者团体，但也希望不要做出这些有损我们项目名声的行为。任何用户都有选择的权利，但请不要用这种蹭名气的手法来进行营销。

Unblock Youku开源项目组

**Comment by zhuzhuor** [comment]
:+1:

**Comment by sallowdish** [comment]
這個真心有點噁心到了

**Comment by Migflyway** [comment]
支持你们

**Comment by kainliu** [comment]
工作辛苦，支持！

**Comment by tywtyw2002** [comment]
:+1:

**Comment by xin-zhang** [comment]
真是f..k!
太无耻了

**Comment by zhuzhuor** [comment]
还有之前有用户发来的 email 和留言，说 UnblockCN 劫持用户强迫用户付费（**而 Unblock Youku 一直都是免费开源软件**）
截图之前有发在别的 GitHub issue 里，在这里再总结一下。可能一下找不全，如果你们看到也可以帮我贴上来

> ![abc1e256-9681-11e5-932e-c1e8a2c93949](https://cloud.githubusercontent.com/assets/928905/12908923/5277d81a-ceb0-11e5-8a75-f2b1c684e0c9.png)
> ![7bbdaefa-cbc9-11e5-861f-13360d17bcb0](https://cloud.githubusercontent.com/assets/928905/12908921/5270b832-ceb0-11e5-99d8-b6e8071aa2cb.png)
> ![741cfd7c-cbc9-11e5-9b4f-5163e190ae0c](https://cloud.githubusercontent.com/assets/928905/12908922/5272195c-ceb0-11e5-90d3-594cb968f0b5.jpg)

**Comment by zhuzhuor** [comment]
之前一些帖子的链接：

* [Unblock Youku 服务器被 DDoS 攻击的时候 UnblockCN 恶意宣传](https://github.com/Unblocker/Unblock-Youku/issues/452)
* [被骗安装了 UnblockCN 之后不能卸载的用户来向求救](https://github.com/Unblocker/Unblock-Youku/issues/468)
* [UnblockCN 劫持用户用户强迫付费，页面还冒充 Unblock Youku](https://github.com/Unblocker/Unblock-Youku/issues/468#issuecomment-180162723)

**Comment by mpqft** [comment]
请大家举手之劳去https://www.google.com/safebrowsing/report_phish/ 举报这个钓鱼网站。

**Comment by Migflyway** [comment]
又出了一个 unlock you pro 是什么鬼？

**Comment by zhuzhuor** [comment]
@Migflyway 你是说这个吗 https://chrome.google.com/webstore/detail/unblock-youku-pro/kmkfhfggebhpdhbcomfhgdnophjcbfcn
之前有人提过 https://github.com/Unblocker/Unblock-Youku/issues/521 也是个冒名顶替的垃圾软件，欢迎去 Chrome Web Store 举报 https://chrome.google.com/webstore/report/kmkfhfggebhpdhbcomfhgdnophjcbfcn

**Comment by tiaotiaozhang** [comment]
very good application

**Comment by gaosong2101** [comment]
这帮人做广告都做到知乎上去了，看到的我全都举报了，管理员也处理了大部分
他们还有个贴吧，比较棘手，没办法就那样吧...

**Comment by zwang** [comment]
建议原作者最好到这里提交请求google chrome web store移除这个软件
https://support.google.com/legal/troubleshooter/1114905?rd=2#ts=1115658%2C1115673

**Comment by mpqft** [comment]
@zwang 提交这个没有用，因为这个流氓软件不是通过chrome web store发布的，而是变态的用exe...

还是去https://www.google.com/safebrowsing/report_phish/举报有用，如果被采纳，这个网址会被chrome, firefox以及safari等主流浏览器屏蔽，同时在google搜素的时候会提供警告。

**Comment by mpqft** [comment]
@gaosong2101 有大量的匿名用户在知乎上推荐unblockcn的，问题是在知乎举报都没有理由举报。还是去Google Safe Browsing举报钓鱼网站吧。

**Comment by gaosong2101** [comment]
@mpqft 理由就是广告，因为他们的广告打的很低级（互相点赞、互相评论、广告内容都很相似），一看就能看出来那就是广告

Google safe browsing我也举报了，**大家举报的时候写一点理由会更好**：
该网站提供的软件存在泄露隐私的风险、阻碍其他软件正常工作、卸载后仍有这样的情况等等等等一些事实就往上写好了

**Comment by mpqft** [comment]
@gaosong2101 其实最大的理由就是钓鱼。证据就在pac.unblcockcn.com的代码里。他们把chrome webstore和mozilla addon的网址redirect到他们自己的付费页面。这个行为绝对触及google的底线的。

**Comment by zhuzhuor** [comment]
@gaosong2101 @mpqft @zwang 非常感谢！欢迎大家都去举报，我刚也去举报了

**Comment by AlexandyZ** [comment]
赞一个开发者。无耻之徒一定要举报！

**Comment by zhuzhuor** [comment]
192.241.222.103 是 DNS 服务器吧？这个是 @whuhacker 帮忙在维护，可以等等他的调查

**Comment by whuhacker** [comment]
@garydevil 可以描述一下 `不能用了` 的现象吗？具体是哪个网址不能看？

**Comment by sequoiar** [comment]
@zhuzhuor 已举报。

**Comment by CttYss** [comment]
已帮忙举报　加油

**Comment by garydevil** [comment]
剛回來  192.241.222.103  check了 現在可用了

**Comment by garydevil** [comment]
3q3q zhuzhuor

**Comment by freefrank** [comment]
请问怎么捐助你们呢？用你们的dns两年了，十分感谢你们的努力。

**Comment by zmingxie** [comment]
@freefrank see https://www.uku.im/index.html

**Comment by freefrank** [comment]
@zmingxie 收到！

**Comment by cresporobben** [comment]
虽然不太清楚事情，但绝对支持unblockyouku，之前打开qq音乐，上面显示让我装unblockcn才能解除限制，我以为unblockyouku改名字了就真的去装了，还充了vip，后来发现vip毛用没有，而且特别难用，我还想怎么unblockyouku变的这么low了，之前用插件的时候几年都没出过问题，怎么改软件以后天天出问题，然后才发现原来根本不是一家。然后去把unblockcn的客服骂了一顿，果断用回unblockyouku。
不过吐槽一下，这几天开始unblockyouku开始出问题了啊，优酷土豆各种播放失败，刷新好多次才行，腾讯视频播了一半直接显示该视频暂时无法播放，昨天看爱奇异，更是直接显示你电脑可能装了恶意插件请卸载，然后把unblockyouku屏蔽了才可以播放。然后还有我看到有个我碰到的问题也有人提出来。就是最近看乐视体育直播特别卡，不知道跟你们有没有关系
我在新加坡

**Comment by zhuzhuor** [comment]
@cresporobben 多谢支持！

优酷和土豆应该还行，如果你发现问题可以来报告下
另外昨天又有一段时间有人 DDoS 攻击我们的服务器 https://github.com/Unblocker/Unblock-Youku/issues/616 你说的昨天不稳定也可能是服务器切换造成的

爱奇艺的问题我们也一直在积极解决，最近的进展可以看 https://github.com/Unblocker/Unblock-Youku/issues/612

最近国外访问国内的网络的确是有点慢，可能是国内最近有大的会议，所以网络检查的比较严
还有就是... 新加坡最近断了一条海底光缆，而且是修复时间未知... http://status.linode.com/incidents/wwzn1mcmc2fp

**Comment by komoesensei** [comment]
@zhuzhuor
海底光缆好像是预定在3月尾修复？
www.theborneopost.com/2016/03/04/tm-broadband-hit-by-temporary-slower-internet-speed/
现在马来西亚打开部分网页也是超慢的。。。

**Comment by tommyzhaozbh** [comment]
继续无语中……
![default](https://cloud.githubusercontent.com/assets/8757104/13721181/2fc60ec8-e859-11e5-81aa-862eef4d99c8.png)

**Comment by caoool** [comment]
http://tieba.baidu.com/f?kw=unblockcn
这貌似是他们的贴吧地址，请各位水军去澄清一下真相。
本人非常厌恶这种恶心的行为，我认为这是一个民族的耻辱。

**Comment by cyanjin** [comment]
unblockcn vip赚钱无可厚非（只要不是拿开源这边的code），但这么不要脸诬陷unblock youku实在是下贱

**Comment by justwater910** [comment]
我刚被骗了钱。下了unblockCN,貌似还是不能用。而且我的wifi也上不去了。我在新加坡。他们是骗子

**Comment by yanggis** [comment]
@justwater910 以前@zhuzhuor发过怎么清理unblockCN插件，你可以搜索一下，清理之后重启安装unblockYouku就好了。
