### ISSUE TITLE
关于最近爱奇艺视频不能正常播放的说明

### ISSUE THREAD

**Issue by zhuzhuor** [uku/Unblock-Youku#638]
最近使用 Unblock Youku 访问某些爱奇艺视频不能正常播放，原因是爱奇艺很有针对性地封锁了 Unblock Youku 几台服务器的 IP。我昨天和前天刚忙着添了两台新的服务器，今天又都被封了。

我的第一反应是前两天刚刚在知乎上看到的 [你见过哪些愚蠢的善良](http://www.zhihu.com/question/42051930)。爱奇艺这做法表面上看似无可厚非，但是其实无论是爱奇艺的用户还是正版视频的推广都是受害者。

Unblock Youku 作为一个拥有 300 万用户的开源免费软件，安全负责任地运行了很多年。我们从来不屏蔽视频网站的广告，也不会让付费资源变得免费，而我们的服务器开销全都来源于大家的捐款。

如果封锁了 Unblock Youku，反而会让一些别的[恶意代理插件](https://github.com/Unblocker/malicious-chrome-extensions)或[流氓代理软件](https://github.com/Unblocker/Unblock-Youku/issues/468)渔翁得利，直接受到损失的反而是大部分不懂技术的普通用户。爱奇艺最近有几部独家版权的电视剧，如果海外华人观看不了爱奇艺的正版资源，也不愿意去使用别的代理软件，唯一的办法可能就是去某些盗版网站上观看或 p2p 下载。好不容易培养起来的用户观看正版视频的习惯也许就会这么地倒退了。

Unblock Youku 并不是正版资源推广的敌人，我们也希望海外的千千万万华人同胞们能够更加方便自由地访问国内的正版优质资源。Unblock Youku 只是在正版推广道路上帮助用户解决不得已的问题的一个工具。

希望爱奇艺能将精力多放在提高用户体验和引入更多的正版资源上。而我们 Unblock Youku 开源项目，短期内应该没有时间和资源来频繁地更新 IP/服务器来一直躲避封锁。有技术能力的同学欢迎自行架设一个代理服务器供自己和身边的人使用，教程可以看[这里](https://git.io/vzmmZ)和[这里](https://git.io/vupNr)。

> ![screen shot 2016-04-22 at 1 20 21 am](https://cloud.githubusercontent.com/assets/928905/14735892/84e2c5ce-0828-11e6-95b8-52751167b13c.png)

**Comment by yanggis** [comment]
@zhuzhuor, DNS服务器也被封了吗？

**Comment by zhuzhuor** [comment]
@yanggis DNS 我没试，如果 DNS 用的代理服务器流量小的话可能暂时还好

**Comment by cm-chen** [comment]
hola 可以用 把browsing国家选china 不过用之前先把unblock关了 因为冲突
<img width="771" alt="2016-04-23 4 44 59" src="https://cloud.githubusercontent.com/assets/11937113/14760452/3361257e-0977-11e6-9379-26923639ce9e.png">

**Comment by cm-chen** [comment]
hola 可以用 把browsing国家选china 不过用之前先把unblock关了 因为冲突
<img width="1302" alt="2016-04-23 4 58 11" src="https://cloud.githubusercontent.com/assets/11937113/14760459/4c117fec-0977-11e6-906c-c94a8a0026ea.png">

**Comment by Dummykid** [comment]
好像是iaiyi有海外会员的服务,所以特意封unblock youku吧?

**Comment by zhuzhuor** [comment]
@Dummykid 你是说 VIP 会员，好像 VIP 在海外依旧还是不能正常观看？

爱奇艺的官方 VIP 说明页面 http://vip.iqiyi.com/viphelpdesk.html

另外还有网友在微博上的评论
> ![screen shot 2016-04-24 at 10 37 30 am](https://cloud.githubusercontent.com/assets/928905/14769289/c4a6ceec-0a0a-11e6-9e2c-f176c99673ce.png)
> ![screen shot 2016-04-24 at 10 37 44 am](https://cloud.githubusercontent.com/assets/928905/14769291/ca5fad7c-0a0a-11e6-8820-9a6341331de9.png)

**Comment by zhuzhuor** [comment]
@Dummykid 我专门付费注册了个 VIP 会员试了下，的确依旧还是不能看
另外注册爱奇艺的账户（无论是不是 VIP） 都需要一个中国大陆的手机号码，我这是借了朋友的手机号收验证码才能注册成功

> ![screen shot 2016-04-24 at 12 46 00 pm](https://cloud.githubusercontent.com/assets/928905/14769999/f04ce30a-0a1a-11e6-86f2-dc265b672828.png)

> ![screen shot 2016-04-24 at 11 00 56 am](https://cloud.githubusercontent.com/assets/928905/14770024/5ffee838-0a1b-11e6-8289-2ca9f7ec90dc.png)

**Comment by Dummykid** [comment]
你这个是海外版的吗? 爱奇艺有个vip海外版 ,一年50刀

**Comment by zhuzhuor** [comment]
@Dummykid 是，是用海外的 PayPal 付费的，没什么卵用
估计就像微博上说的，只是增加了“海外”的付费方式，观看还是得用代理或者 VPN

**Comment by Dummykid** [comment]
真坑.
对了 ,最近我 发现一个suntv的电视盒子 (我不是在 做广告), 99刀买 盒子送2年tvb和长城平台的节目.  我在 长城平台看了,suntv是授权代理. 2年后如果 想继续使用服务的话,再花99刀可以再看2年.
感觉以后 广电局继续封杀国外ip,只能给我爸妈买个suntv的盒子,让他们想看啥就看啥了, 话说99刀看2年还送个盒子,好像也不是 很贵.

**Comment by ruijianw** [comment]
爱奇艺还有个问题，ios下的「爱奇艺PPS」这个app貌似无视unblock youku的pac文件，我用的是自己搭建的服务器，ipad下用safari访问web页面播放没问题，用「爱奇艺PPS」就显示版权问题， 不知道是不是这个app走了什么特殊的地址，列表里面没包括进去，有需要我可以借你我的账号测试。

**Comment by zhuzhuor** [comment]
@ruijianw 这个问题请单独开个 issue 吧，可能是 iOS app 访问的地址和网页版不一样

**Comment by ruijianw** [comment]
好

**Comment by eepocket** [comment]
可以用Amazon的AWS架设这个自己的代理吗？

**Comment by ruijianw** [comment]
@eepocket 如果你能申请到中国区的aws服务器，那就可以

**Comment by Migflyway** [comment]
我也注册过，无法观看。

**Comment by Migflyway** [comment]
小米观影会员，腾讯视频会员，爱奇异。买了都无法观看。

**Comment by fishleng** [comment]
還有樂視都是, 基本上都封了海外,

**Comment by fujunswufe** [comment]
以后不看爱奇艺了呗，反正也有替代品

**Comment by zhuzhuor** [comment]
有用户反馈了这样的使用方法... 回头看看原理是什么

![screen shot 2016-05-12 at 11 54 42 pm](https://cloud.githubusercontent.com/assets/928905/15240220/fc58976c-189c-11e6-94e7-43e0bf81dfee.png)

**Comment by MonkeyLeeT** [comment]
@zhuzhuor 
美国本地测试，广告加载之前就显示版权信息了，并不能看到刷新按钮。难道是香港特有的？

**Comment by asuka0819** [comment]
在日党表示DNS和chrome插件都没事啊

**Comment by yanggis** [comment]
@asuka0819 你来晚啦，问题早就修复啦，呵呵。
