### ISSUE TITLE
 Unblock Youku 官方论坛 bbs.uku.im 试运营

### ISSUE THREAD

**Issue by zhuzhuor** [uku/Unblock-Youku#643]
我们之前一直在用 GitHub Issues 和 Google Group 来收集用户反馈和做一些非技术的公告和讨论
但是这两个地方的界面对非技术出身的人来说都不怎么友好
特别是 Google Group 功能非常有限，管理起来不是很方便

于是最近用 [Discourse](https://www.discourse.org/) 弄了个 Unblock Youku 的官方论坛 [https://bbs.uku.im](https://bbs.uku.im)
大家可以先试试，可直接用 GitHub/Google/Facebook/Twitter 的帐号登录，遇到问题欢迎来汇报

以后想把这个 BBS 做为用户反馈的地方，用来替代 Google Group
另外不适合 GitHub 的非技术类型的讨论和公告都可以发布到 BBS 上去
有人有什么好的使用体会和分享都可以发到 BBS 上去，让更多的用户看到

感谢大家长久以来的支持！

**Comment by Kara-ism** [comment]
刚上去看了一下，貌似用的是Discourse；查了下这论坛用的是PostgreSQL保存论坛数据。
不过我觉得基本用Google Group就行，毕竟要让论坛服务器稳定运行也是件麻烦事……

觉得Google Group麻烦的话有考虑用Google+社群麽？
Google+社群有个「筛选器」功能可以当作论坛的版块功能，作为区分分类用途…。

**Comment by zhuzhuor** [comment]
@Kara-ism 我们之前用 GGroup 就是图省事，但是 GGroup 那界面和功能太让人着急了。G+ 社群估计没多少人用呢，而且肯定都是得实名注册。让用户都来 GitHub 也不太实际。
用户体验还是最重要的，我们需要个不懂技术的用户也能方便地互相交流地地方

**Comment by Besezta** [comment]
論壇程式不錯，收下了（弄錯重點

**Comment by komoesensei** [comment]
发帖根本发不出ORZ. 根本没搞懂不够详细是什么意思。。。
不够长？太长？
少了什么关键字？。。
还是其他的什么？。。

**Comment by zhuzhuor** [comment]
@komoesensei 你遇到具体的错误信息是什么，能发个截图之类的看看吗？
这用的是一个老外写的开源的论坛软件，中文翻译不一定准确

**Comment by komoesensei** [comment]
![s60508-124711](https://cloud.githubusercontent.com/assets/17672437/15096072/28d039d8-151b-11e6-891d-2865c4306d7f.jpg)

**Comment by zhuzhuor** [comment]
@komoesensei 能把你的那个 title 的内容发到这里来吗? 我试试看。感觉还挺神奇的

**Comment by komoesensei** [comment]
使用PAC 下载bilibiliB站新番偶尔会丢一段分段。。。（有没有其他人遇到这问题？（这标题到底要多长才能发出去啦啦啦啦啦？

@zhuzhuor 上面是标题。。

**Comment by komoesensei** [comment]
因为之前试了几次都发不出去所以看起来有点乱。。。

**Comment by zhuzhuor** [comment]
@komoesensei 多谢反馈，我这里能够 reproduce，我回头看看怎么设置设置吧，感觉像是 antispam 的东西

**Comment by zhuzhuor** [comment]
@komoesensei BTW，你其实把标题写简单点就能发出去了，例如 `使用PAC 下载bilibiliB站新番偶尔会丢一段分段`

**Comment by komoesensei** [comment]
@zhuzhuor
发出去了
感觉那问题应该很少人遇到？
嘛。。。姑且反馈下。。
