### ISSUE TITLE
关于腾讯视频 无法观看“火锅英雄”

### ISSUE THREAD

**Issue by yyz20002008** [uku/Unblock-Youku#649]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome

请具体描述您遇到的问题（例如有问题的视频网址）：http://film.qq.com/cover/w/wvcu4w3elpdnzjl.html?vid=n00206kx4b9&ADTAG=INNER.TXV.COVER.REDIR

查到我是美国的ip,说不能用，我用的是同学的好莱坞会员，我同学能用，但我的ip不能用，我们相聚就20mile,都是verizon供应商。ip:24.104.xxx.xxx

您所处的国家或地区：美国 东部 

谢了

**Comment by zhuzhuor** [comment]
@yyz20002008 我这里试了下也可以
你看你访问 https://uku.im/check 是 true 还是 false
如果是 false 看看有没有和别的软件冲突什么的，也可以把 Unblock Youku 卸载了再重装下
