### ISSUE TITLE
谁能测试一下豆瓣fm的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#652]
最近豆瓣fm新加了HTTPS，使得原来的代理规则失效了。最近我加了一个HTTPS的规则，现在插件已经有这个HTTPS的规则了，但还是返回版权限制。有哪个在香港的也是碰上这个问题？我真的没辙了……

**Comment by i9602097** [comment]
https不能代理的。

**Comment by i9602097** [comment]
代理https要匯入證書，比較麻煩。

**Comment by tommyzhaozbh** [comment]
也就是说squid 对这些加密页面没有办法，一定要用vpn?

**Comment by komoesensei** [comment]
stackoverflow.com/questions/516323/https-connections-over-proxy-servers
wiki.squid-cache.org/Features/HTTPS

**Comment by mc16888** [comment]
@tommyzhaozbh 我昨天用自己的美团云试到的方法。

Sqiud.conf
加多一个 acl
`acl crx_url_connect url_regex -i "/opt/crx_url_list_connect.txt"`
然后加
`http_access allow CONNECT crx_url_connect`
要加在这一句前面
`http_access deny CONNECT !SSL_ports`

之后在 /opt 下面加一个 file "crx_url_list_connect.txt"
file 里面加 
`^douban\.fm:443.*$`

不过我怀疑上面的做法不是很正规，因为网上找到的代理 https 做法以一般都是用 ssl bump 和汇入证书。

**Comment by zhuzhuor** [comment]
代理 HTTPS 是可以的，只是不能做细致的 URL 过滤，可以整个 domain name 一起通过代理服务器
另外不需要导入 MITM 证书的

@mc16888 你这个测试之后是可以正常 work 的对吧？

**Comment by mc16888** [comment]
@zhuzhuor 可以。

**Comment by zhuzhuor** [comment]
那估计我们现在的 Squid 配置文件没能处理好 HTTPS 请求，需要找个时间测试和更新下

**Comment by zhuzhuor** [comment]
@mc16888 多谢你的提示
现在 Squid 代理服务的配置应该是改好了，可以正常支持 HTTPS 请求的代理了
见最新的更新 https://github.com/uku/Unblock-Youku/commit/e399b3c0cf5dc71dccd6d618019ee9d71c01337e

@tommyzhaozbh 
大家可以回头试试对 https://douban.fm 起效不起效

**Comment by mc16888** [comment]
@zhuzhuor 我刚刚试了一下，https://douban.fm 已经OK了。

**Comment by zhuzhuor** [comment]
@mc16888 多谢帮忙！
