### ISSUE TITLE
转发模式 按钮消失？ 功能取消？

### ISSUE THREAD

**Issue by pyy** [uku/Unblock-Youku#655]
请问最新版本的Chrome插件，在后台看到“转发模式”，但是如何使用呢？popup面板里只有 Off,Lite,Standard三个按钮。

我按照教程配置了转发服务器后端，不知道如何使用，难道必须要搭建squid做后端？

谢谢！

**Comment by zhuzhuor** [comment]
见 https://github.com/uku/Unblock-Youku/issues/339 最下面 
lite/redirect 模式现在功能非常有限，如果有能力的话还是搞个 squid 服务器吧

**Comment by zhuzhuor** [comment]
要么直接把转发服务器架设在国内，要么就在国内再弄一个 squid 服务器给转发服务器做代理
如果有了国内的 squid 服务器就直接设置给标准模式用了
