### ISSUE TITLE
如何给后端Squid3服务器 添加用户认证？

### ISSUE THREAD

**Issue by pyy** [uku/Unblock-Youku#657]
你好，本人第一次用Squid3，请问如何给Squid3添加基本的用户认证，使Unblock-Youku小部分人使用？以免被代理爬虫搜到使用而浪费自己的服务器钱？

查看了stackoverflow的帖子，添加了基本的htpasswd认证，但是如何在uku的chrome插件中使用？谢谢
http://stackoverflow.com/questions/3297196/how-to-set-up-a-squid-proxy-with-basic-username-and-password-authentication

谢谢

**Comment by zhuzhuor** [comment]
PAC (proxy auto-config）没法用用户名密码验证
如果你设置了白名单的话应该问题不大，绝大部分的网站爬虫都访问不了
