### ISSUE TITLE
HOSTS修改腾讯视频的视频源CDN 地址

### ISSUE THREAD

**Issue by kang000feng** [uku/Unblock-Youku#661]
请问腾讯视频的视频源CDN 地址是vlive.qqvideo.tc.qq.com吗? 通过本地PC端HOSTS解析腾讯视频的CDN 域名到离我速率最快的IP 地址可行吗？是不是可以加快播放速度？不管在国内国外都可以通过这种方式修改吗？谢谢！

**Comment by kang000feng** [comment]
@tommyzhaozbh 请问腾讯视频v.qq.com/的视频源CDN 地址是多少？谢谢！

**Comment by tommyzhaozbh** [comment]
这个恐怕还要去研究一下，我倒是没有研究过腾讯CDN的事情，因为速度一直都还行。

**Comment by kang000feng** [comment]
@tommyzhaozbh  我用开发者工具 wireshark 都没有抓取到。好奇怪。

**Comment by hzhu007** [comment]
话说最近一个月看腾讯很慢跟这个有关系么
