### ISSUE TITLE
腾讯tv vip会员是否可以通过更改dnS的办法在海外观看呢?

### ISSUE THREAD

**Issue by wtjfree** [uku/Unblock-Youku#662]
我在英国,是用安卓电视盒子改DNS看国内的节目

现在腾讯送 TV VIP会员 所以就搞了一下,结果都不能看了. 登出会员可以看免费的节目,登录会员啥都不能看.好象错误信息是100,80

不知道其他兄弟是不是也是这种情况,如果可以请问如何解决.

**Comment by yanggis** [comment]
出了腾讯，其他的视频可以看吗？比如优酷，乐视，bilibili等等。

**Comment by wtjfree** [comment]
是vip会员呀. 其他的我没有会员,所以我也没法测试

**Comment by yanggis** [comment]
哦，哈哈，我的意思是非VIP会员的腾讯视频的电视剧和电影可以看不？看VIP电影以前好像是有点问题。
