### ISSUE TITLE
b站直播在海外没法看

### ISSUE THREAD

**Issue by jzhangbs** [uku/Unblock-Youku#663]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: chrome插件

请具体描述您遇到的问题（例如有问题的视频网址）：

如题。在live.bilibili.com最上面的视频窗那里会提示“video not found or access denied: 一个网址”。然后点进直播间就一直是小电视。我通过vpn返回墙内就可以看了，所以想问问有没有什么办法能让海外也能正常解析b站直播

您所处的国家或地区：香港

**Comment by yanggis** [comment]
设置DNS为158.69.209.100，然后重启电脑再试试。

**Comment by zhuzhuor** [comment]
@jzhangbs 
我这里刚试了下是可以，你看看你的 chrome extension 是最新版的v3.3.0吗，另外没有关闭吗

> ![screen shot 2016-06-25 at 1 22 37 pm](https://cloud.githubusercontent.com/assets/928905/16358945/09189f30-3ad8-11e6-84ca-45812118b7d4.png)

**Comment by jzhangbs** [comment]
前面两条我都确认过了都是看不了，然后我发现直接拿流量看都是可以的，看来是学校的网给屏蔽了啥东西，应该除了vpn是无解了，悲剧……

**Comment by zhuzhuor** [comment]
@jzhangbs 那的确是有可能
你如果是在用标准模式可以试试精简模式，两种模式的解封方法不太一样，说不定另外一种模式在你们校园网可以正常使用

**Comment by JackieDreamy** [comment]
标准模式无法加载，Lite模式可以。

地区：美国

比如这个地址http://bangumi.bilibili.com/anime/v/15565

**Comment by zhuzhuor** [comment]
@JackieDreamy 多谢反馈，我试了下的确是这样，我们研究研究

**Comment by zhuzhuor** [comment]
今天稍微看了下这个问题，觉得比较奇妙
比如像这个 URL
```
http://interface.bilibili.com/playurl?cid=2372258&player=1&ts=1467875404&sign=d13b202c085779385496b959018cf983
```
使用代理就会出错，不使用代理就没事

两种猜测
1. 还需要代理别的某个 URL，才能使得这个  URL 不出错
2. 或者这个 URL 就不能通过代理？彻底不代理，只需要更改 header 就好

**Comment by komoesensei** [comment]
@zhuzhuor
感觉和这个是同一个问题的样子。。
https://bbs.uku.im/t/bilibili/47/79?u=komoesensei

**Comment by zhuzhuor** [comment]
@komoesensei 多谢你的 link
那个帖子里 i9602097 的反馈我当时没怎么看明白... 是把 https://app.bilibili.com 加到 PAC 里就行了吗，貌似当时就把那个 URL 加到 PAC 里了
这次 @JackieDreamy 给的这个视频链接，我把整个浏览器代理了都不行，反而不代理就没事，感觉不是一个问题

**Comment by zhuzhuor** [comment]
让 @yanggis 帮忙试了试
在电脑上用 DNS 也是不能正常播放
但是用 DNS 在手机上看网页或者 app 都可以正常播放这个视频...
http://bangumi.bilibili.com/anime/v/15565

**Comment by zhuzhuor** [comment]
决定先把 interface.bilibili.com 从 chrome extension 的普通模式代理列表里去掉了，只通过改 header 的办法来解封，见 https://github.com/uku/Unblock-Youku/commit/d6d40ed88ee61dd4da6cd269a6712731c699afab
这样可能会导致有些不能用 header 方式解封的用户访问 b 站有问题，不过先这样运行试试看

如果有后续问题，欢迎再来反馈

**Comment by zhuzhuor** [comment]
续楼上的 update
在 v3.3.2 又把这个 change 给取消了，因为 v3.3.1 版本更新了之后有很多人反馈 b 站看不了了
@JackieDreamy 之后发现有 b 站视频不能看的话，请手动切换 lite 模式试试

想了想，用 v3.3.1 版本的做法，header 方式不能正常工作的人会彻底访问不了一些 b 站视频
如果用 v3.3.2 或者 v3.3.0 的做法的话，大部分的人至少 lite 和 standard 两种模式中的一种还可以正常访问 b 站

**Comment by JackieDreamy** [comment]
这几天搬家来的，好像是因为bilibili升级的缘故导致的，我现在配合bilibili helper是米问题的

**Comment by komoesensei** [comment]
@JackieDreamy
如果用bilibili helper没问题的话用lite模式应该也没问题吧？

**Comment by JackieDreamy** [comment]
@komoesensei 
lite没问题，用bilibili helper主要是为了看锁非大陆地区的视频（比如HK）
