### ISSUE TITLE
Unblock Youku not work properly.

### ISSUE THREAD

**Issue by sunyiyun2001** [uku/Unblock-Youku#664]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome Version: 51.0.2704.106 (64-bit); Extension Version: 3.3.0; Have Firewall which blocks VPN and Proxy.

请具体描述您遇到的问题（例如有问题的视频网址）：Bilibili.com下的任何新番

您所处的国家或地区：OR, USA

会卡在加载视频内容这一步上面。

**Comment by zhuzhuor** [comment]
你可以试试看 精简模式 可以解决你的问题吗？
![screen shot 2016-06-26 at 8 40 42 pm](https://cloud.githubusercontent.com/assets/928905/16367988/472afaaa-3bde-11e6-915e-63fa888932dc.png)

**Comment by sunyiyun2001** [comment]
还是不行。

**Comment by sunyiyun2001** [comment]
有没有什么备用服务器之类的？

**Comment by sunyiyun2001** [comment]
Firewall是palo alto的硬件防火墙

**Comment by zhuzhuor** [comment]
@sunyiyun2001 lite 模式不使用代理服务器或者 VPN，你确定是防火墙封锁代理或者 VPN 的原因吗
