### ISSUE TITLE
使用爱奇艺iOS app时pac文件无效

### ISSUE THREAD

**Issue by nahgnaw** [uku/Unblock-Youku#665]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: 
pac

请具体描述您遇到的问题（例如有问题的视频网址）：
爱奇艺的iOS app前两天更新后pac文件无效了(显示版权限制信息)。
不知有没有什么方法可以解决一下

您所处的国家或地区：
美国

**Comment by tommyzhaozbh** [comment]
服务器被炸了，晚点再试试

**Comment by zhuzhuor** [comment]
@nahgnaw  PAC 服务器现在没有受到攻击了，你再试试？如果不行的话估计需要更新一下 PAC 文件的内容

**Comment by nahgnaw** [comment]
用爱奇艺的iOS app还是不行 但用ipad浏览器可以看 前几天他们的app更新了一下 然后就不能看了 是不是他们干了点啥

**Comment by tommyzhaozbh** [comment]
其实这个问题我也碰到过，爱奇艺不知怎的好像无视pac，设了pac某些视频也不管用。

**Comment by zhuzhuor** [comment]
后续的更新在 https://github.com/uku/Unblock-Youku/issues/685
