### ISSUE TITLE
突然看不了b站，关掉以后就可以看

### ISSUE THREAD

**Issue by sviivs1** [uku/Unblock-Youku#668]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome 插件/firefox 插件

请具体描述您遇到的问题（例如有问题的视频网址）：突然看不了b站，关掉以后就可以看了
但是「正版视频」开着插件卻可以看. 一开一关很不方便.

您所处的国家或地区：英国

**Comment by zhuzhuor** [comment]
@sviivs1 多谢反馈，能提供一个具体的视频链接吗？

估计和这个问题一样 https://github.com/uku/Unblock-Youku/issues/663
你试试 lite 模式能看吗？
