### ISSUE TITLE
有人帮忙测试一下QQ音乐不?

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#670]
刚才在论坛看到有人说QQ音乐网页版失效了，我不清楚是不是腾讯改了链接，而且现在我人在大陆没法测试。谁能帮忙测试一下?Chrome 插件的
PS: 如有可能帮忙测试一下DNS对QQ音乐pc端是否仍然有效 @yanggis

**Comment by yanggis** [comment]
DNS对QQ音乐无效，因为里面有一个基于IP的验证，会直接连182.254.116.117服务器验证客户设备是不是在大陆，这个DNS解决不了。

**Comment by zhuzhuor** [comment]
我这里试了几首曲子是可以的正常播放的（相对比，不开启扩展程序是没法播放的）
可以问那个反馈用户问问具体的曲子来测试

@yanggis 说的那个 IP 我没见到过，也没在现在的 urls.js 里。我们把它加到 urls.js 里？

**Comment by yanggis** [comment]
@zhuzhuor 你看这个issue, https://github.com/uku/Unblock-Youku/issues/507  里面搜索182.254.116.117就能看到问题了。

**Comment by zhuzhuor** [comment]
@yanggis 多谢，我看到 #507 里提到一个另外一个 URL 被我之前加到 urls.js 里了，不知道为什么这个 IP 没有。这就加进去

**Comment by yanggis** [comment]
@zhuzhuor 你就让连这个IP的都走代理就行了，我现在发现腾讯的所有视频和音乐软件都能看到连这个IP做验证的link，包括TV版的QQ音乐，连那个新的CIBN微视听新版的也可以用这个IP验证了，虽然腾讯视频不验证这IP也可以播，难说以后会不会都跟着用都用这个。要是都加了这个，那DNS解锁就有点小麻烦了。

**Comment by zhuzhuor** [comment]
@yanggis 多谢，已经加进去了

**Comment by tommyzhaozbh** [comment]
@yanggis QQ音乐 Windows 客户端都不行?

**Comment by yanggis** [comment]
@tommyzhaozbh Windows客户端我没试，现在在单位DNS解锁被单位屏蔽了，用不了。IPhone, android手机和QQ音乐TV版我都试过，如果不加那个IP都不行。

**Comment by tommyzhaozbh** [comment]
那先谢了。如果谁也在海外的也帮忙试试DNS+QQ音乐windows端看看行不行。

**Comment by yanggis** [comment]
@tommyzhaozbh 刚才试了，DNS+QQ音乐网页版在windows10上可以听。

**Comment by asuka0819** [comment]
@tommyzhaozbh qq音乐客户端+DNS在win8上面没问题，只是打开页面会及其地慢！

**Comment by tommyzhaozbh** [comment]
@asuka0819 直接用DNS的话会有可能比较慢，但如果直接改hosts速度会快很多。

**Comment by yanggis** [comment]
@tommyzhaozbh 的确是这个问题，因为一般情况下DNS没法像客户本地的DNS服务器一样分派到距离用户最近的服务器。有时候速度不能让人满意。

**Comment by asuka0819** [comment]
@tommyzhaozbh 求大神指导教程

**Comment by tommyzhaozbh** [comment]
@asuka0819 这个简单，c:/windows/system32/drivers/etc 这个路径下有一个hosts文件，没有后缀的。用记事本打开(记事本要以管理员模式运行)，文件最后加一行保存即可
158.69.209.100 i.y.qq.com

上面的ip替换成任意一个dns都行

**Comment by jasperchow** [comment]
@tommyzhaozbh 请问一下修改hosts文件的方法同样适用于osx吗？

**Comment by tommyzhaozbh** [comment]
可以的，但OsX可以直接使用pac，直接改pac也行

**Comment by jasperchow** [comment]
@tommyzhaozbh 我试了一下改hosts还是会显示超出服务区域，但pac的方法是可以的
