### ISSUE TITLE
在国内开启unblock youku的话打不开豆瓣fm

### ISSUE THREAD

**Issue by seansay** [uku/Unblock-Youku#671]
http://douban.fm

<img width="899" alt="screen shot 2016-07-19 at 11 35 20 am" src="https://cloud.githubusercontent.com/assets/349342/16937844/036194c2-4da5-11e6-9a00-434ac69ddca0.png">

**Comment by zhuzhuor** [comment]
为什么在国内还需要用 Unblock Youku? 你可以在菜单里选择 Off，如果只是临时回国的话
> ![screen shot 2016-07-18 at 8 38 11 pm](https://cloud.githubusercontent.com/assets/928905/16937877/8e80f0d0-4d27-11e6-9f5f-027b30ca655a.png)

**Comment by seansay** [comment]
@zhuzhuor 
我其实是豆瓣fm的开发人员，因为总有用户反馈过来出现这样的现象，最后发现是unblock youku的问题。所以不知道这个empety response是因为？

**Comment by zhuzhuor** [comment]
@seansay 多谢前来反馈，反馈这个问题的人多吗，问题常见吗

之前我们的开源项目被人 DDoS + 诽谤（[见之前的 issues](https://github.com/uku/Unblock-Youku/search?q=ddos&type=Issues&utf8=%E2%9C%93)）
在那之后在 DNS 上给国内的访问者解析到一个偏远的抗 DDoS 服务器上了去了，可能这个服务器对国内的用户不怎么友好

如果反馈用户比较多的话我把 DNS 改到正常的服务器上试试吧

**Comment by seansay** [comment]
@zhuzhuor 
不算多，但是偶尔就会出现一个这样的用户。

麻烦了

**Comment by zhuzhuor** [comment]
@seansay 最近服务器已经重新 restructure 了，这个 issue 就 close 了。之后还有问题的欢迎再来反馈
