### ISSUE TITLE
阿里云搭建自己的squid服务器

### ISSUE THREAD

**Issue by sbihero** [uku/Unblock-Youku#672]
我在参照wiki的方法在阿里云搭建自己的服务器时，出现了问题。
服务已经正常运行，已经有active(running)。
![image](https://cloud.githubusercontent.com/assets/635915/16964801/4643014c-4dcb-11e6-8dbf-bd12cc678d36.png)
服务器没有设置防火墙，现在上行下行允许所有端口。
![image](https://cloud.githubusercontent.com/assets/635915/16964817/56408dda-4dcb-11e6-854a-0345c2b71b91.png)
![image](https://cloud.githubusercontent.com/assets/635915/16964825/5cdbaab2-4dcb-11e6-8229-151dd215847f.png)
但是在客户端测试的时候依旧无法成功：
![image](https://cloud.githubusercontent.com/assets/635915/16964993/0ead3576-4dcc-11e6-8afc-76f646d6efdf.png)
不知道开发者有没有在阿里云搭过，有没有遇到类似的问题。

PS.服务器本身应该没有问题，shadowsocks可以测试通过。

**Comment by tommyzhaozbh** [comment]
我们的服务器本来就是在阿里云上面的，我现在给自己用的服务器也是阿里的，都没有这个问题。在这种情况下很可能是设置没有正确加载导致链接无法通过代理服务器。但这个要问问@Zhuzhor

**Comment by komoesensei** [comment]
会不会是不小心把ss的端口和squid的端口设置成同一个了？

**Comment by mc16888** [comment]
不会是你自己电脑的防火墙把 8888 port 给挡了吧。

另外你在你阿里云打这一句，结果是TURE还是FALSE

`curl -x 127.0.0.1:8888 "http://ipservice.163.com/isFromMainland"

**Comment by zhuzhuor** [comment]
@sbihero 阿里云可能需要备案才能用，见 https://github.com/uku/Unblock-Youku/issues/320
你可以试试别的云？美团云用 80 之外的端口好像不用备案

**Comment by sbihero** [comment]
我在美团云上又试了一下，发现问题是ss和squid有冲突。ss的端口是8989，squid是8888。
而且都安装后，8888的服务也还在。还需要进一步debug。

**Comment by lxxgreat** [comment]
@mc16888 curl -x 127.0.0.1:8888 "http://ipservice.163.com/isFromMainland" 可以访问。 但是从外网访问就不行。

**Comment by lxxgreat** [comment]
亲自测试， 把squid的3128端口改成其他端口就可以了。 我改成9999端口， OK.
