### ISSUE TITLE
优酷播放失败的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#673]
大量用户反馈说优酷视频播放失败，全部反馈仅在中国大陆播放(错误代码1000)，相关反馈可以在论坛找到。谁能帮忙测试一下?如果可以的帮忙提交pull request

**Comment by tommyzhaozbh** [comment]
@yanggis DNS更新了不?

**Comment by yanggis** [comment]
@tommyzhaozbh 嗯，更新了。
