### ISSUE TITLE
b站视频出现无法播放地情况

### ISSUE THREAD

**Issue by asuka0819** [uku/Unblock-Youku#675]
有一个很奇怪地现象
我家里加载DNS的时候，看一些b站非版权地视频地时候会显示说无法正常播放的黑屏
但是我在学校用chrome＋插件倒是没什么问题
把dns恢复过来就没事了，感觉应该是dns的问题吧
不知道是什么情况

所处的国家或地区：日本

**Comment by yanggis** [comment]
@asuka0819 你用的是哪个DNS啊？158那个吗？

**Comment by asuka0819** [comment]
@yanggis 应该不是，我首选45然后下面是158的，然后换了个位置又可以了
感觉45那个是不是被污染了，有时候会莫名指向b站的其他视频地址去……

**Comment by yanggis** [comment]
@asuka0819 DNS只会干预要解锁的那几个链接，其他的都不会走DNS服务器过，不会指向b站其他视频地址的，更谈不上污染了。

**Comment by asuka0819** [comment]
@yanggis 了解了，感谢解答
