### ISSUE TITLE
有关pac的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#676]
前几天有一个台湾的用户反馈说用了pac之后163的检测还是返回false，原因不明。这是怎么回事呢?

**Comment by zhuzhuor** [comment]
后来这个用户有提供更多的信息吗？有进展的话可以 reopen 这个 issue

**Comment by tommyzhaozbh** [comment]
有提供一下，但网络设置是对的，其他的也没啥问题，就是不清楚哪里有问题
