### ISSUE TITLE
网易云音乐不能用了

### ISSUE THREAD

**Issue by AgentKWang** [uku/Unblock-Youku#678]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome插件， 也试了改 DNS 158.69.209.100

请具体描述您遇到的问题（例如有问题的视频网址）：http://music.163.com

您所处的国家或地区：美东

**Comment by yanggis** [comment]
@AgentKWang 改完DNS之后你重启电脑了来清空DNS了吗？http://ipservice.163.com/isFromMainland 返回是true还是false？

**Comment by AgentKWang** [comment]
@yanggis 试过ipconfig /flushdns。 http://ipservice.163.com/isFromMainland返回true。举个例子，http://music.163.com/#/song?id=29019227这首就因为地区限制不能听。

**Comment by yanggis** [comment]
@AgentKWang 你是不是本地修改了hosts文件啊？这个歌我试了是可以听的。

**Comment by AgentKWang** [comment]
@yanggis, 我hosts没改啊。。也是奇怪了  我怀疑是不是ipv6的问题。但是禁用了ipv6也没效果。

**Comment by yanggis** [comment]
@AgentKWang 在你电脑上ping music.163.com 然后ping s2.music.126.net看返回的IP都是多少。
然后访问http://www.lagado.com/proxy-test 看看是不是显示你已经使用了代理；
然后http://ipservice.163.com/isFromMainland  看看是不是显示为true.

**Comment by AgentKWang** [comment]
@yanggis OK, 弄好了，原因是我那抽风的公司VPN给我加了一堆DNS suffix，断开VPN的时候不知道为什么没帮我清除。感谢你的耐心帮助！
