### ISSUE TITLE
Chrome Lite Mode 下bilibili.com 无法播放国内视频

### ISSUE THREAD

**Issue by charleyzhuyi** [uku/Unblock-Youku#679]
最近，Lite Mode 在Bilibili.com 下无法播放了，切换到Standard Mode 就可以了，，但是Standard 模式比Lite 要慢很多，希望能尽快修复Lite Mode 的使用bilibili

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome

请具体描述您遇到的问题（例如有问题的视频网址）：bilibili.com Lite 模式无法播放

您所处的国家或地区：美国

Unblock Youku 3.3.6

**Comment by tommyzhaozbh** [comment]
由于现在b站修改了api，精简模式已经不起作用，所以只有一个模式可用了
