### ISSUE TITLE
Unblock Youku 官方论坛登陆不上了

### ISSUE THREAD

**Issue by xkk** [uku/Unblock-Youku#680]
无法使用github账号登陆论坛
登陆会提示如下信息 抱歉，在验证你的帐号时发生了错误。可能你没有批准授权申请？

然后我在github看是已经授权的
授权信息如下
Unblock Youku Official Forum
 Last used within the last 4 months Owned by zhuzhuor  https://bbs.uku.im
Permissions
 Access user email addresses (read-only)

**Comment by yanggis** [comment]
@zhuzhuor 论坛上回帖也回复不了，写了一大段，点回复，却说内容太少之类的，不让发帖……。

**Comment by zhuzhuor** [comment]
@xkk 多谢反馈，我今晚有空了看看
@yanggis 可能是 spam filter 的误伤，等我看看。你可以私信我你发的内容，我来试试看

**Comment by zhuzhuor** [comment]
@xkk 我试了下的确是这样，重置的 github oauth client secret 还是不行，给 discourse 的人发了个消息看看他们有什么解决办法吗，希望不用 revoke 所有人的授权

**Comment by zhuzhuor** [comment]
@yanggis @tommyzhaozbh 调低了后台 spam filter 的设置，你们再试试？最近也没改过这个，不知道为什么突然变严格了？你们的帖子的什么内容，能发给我试试吗

**Comment by zhuzhuor** [comment]
@xkk 3rd party login 的问题解决了，你可以再试试
我发现不仅 github 不能用，别的 twitter/google/facebook 都不能用。discourse 最近估计 update 了个不该搞的东西，已经跟他们反馈了

**Comment by tommyzhaozbh** [comment]
现在可以了

**Comment by xkk** [comment]
已经可以了
