### ISSUE TITLE
英国ip没办法看http://2016.cctv.com/上的奥运会直播

### ISSUE THREAD

**Issue by relliky** [uku/Unblock-Youku#681]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
windows chrome插件
请具体描述您遇到的问题（例如有问题的视频网址）：

放完广告后，显示：由于播出安排变更，暂时不提供该时段内容。测试过很多项目，包括正在直播项目以及应该是长期播放的CCTV5.

您所处的国家或地区：
英国剑桥

**Comment by zhuzhuor** [comment]
最新版 v3.3.7 添加了这个 CCTV 页面的支持，等更新了你试试看

如果之后还有问题，或者网页有更新，欢迎再来反馈，多谢

**Comment by mc16888** [comment]
@zhuzhuor 这几个不是播片的CDN服务器吗，全代理的话，国内服务器会不会负担太重啊。

'http://cctv1.vtime.cntv.cloudcdn.net/cache/*',
'http://cctv5.vtime.cntv.cloudcdn.net/cache/*',
'http://cctv5plus.vtime.cntv.cloudcdn.net/cache/*',
'http://cctv13.vtime.cntv.cloudcdn.net/cache/*',
'http://sports1pull.live.wscdns.com/live/aoyun2',

**Comment by zhuzhuor** [comment]
@mc16888 今天看流量的确负担有点重，但是貌似不代理不行，只用 header 也不行。奥运期间我临时多弄几台服务器吧

**Comment by zhuzhuor** [comment]
已经新加了几台服务器，在这奥运期间运行下吧，奥运结束了可以关掉
