### ISSUE TITLE
有关爱奇艺ios端的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#685]
之前曾经有人反馈过爱奇艺ios端有问题。今天我刚刚更新了一下app，发现连DNS也不起作用了。
![2016-08-11 104037](https://cloud.githubusercontent.com/assets/8757104/17577527/63abaa20-5fb1-11e6-9691-c1aa95a239b5.png)
一气之下用Charles去检查，发现多了这么一条链接是不在代理名单里面的。
![image](https://cloud.githubusercontent.com/assets/8757104/17577550/af0aae62-5fb1-11e6-9f9f-075fd270cb15.png)
但我没有办法确定这是不是就是要代理的东西，所以希望有人能帮忙测试一下。
随同附上Charles的记录文件  链接: http://pan.baidu.com/s/1hsz46FE 密码: p3s6

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 可以先加到 PAC 的 URL 里面试试

@yanggis 你能重现这个问题吗

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我看到 PAC 其实里面有 https://pac.uku.im/pac.pac
所以应该不是这个 URL 的问题

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 所以我觉得有点奇怪，但我真的看不到还有什么地方有检测的了。

**Comment by yanggis** [comment]
@tommy 现在用DNS不能看爱奇艺了吗？

**Comment by mc16888** [comment]
@tommyzhaozbh @zhuzhuor @yanggis 

我用爱奇艺ios app V7.6 测试，发现
http://cache.video.qiyi.com/vps?* 
改成
http://cache.video.iqiyi.com/vps?* 

把 cache.video.iqiyi.com 加去DNS就可以了。

**Comment by zhuzhuor** [comment]
@mc16888 牛逼，多谢！

**Comment by yanggis** [comment]
好的，我一会加上去，非常感谢！

**Comment by tommyzhaozbh** [comment]
@mc16888 厉害，你用什么抓包的？我怎么抓不到啊……

**Comment by yanggis** [comment]
@mc16888  cache.video.qiyi.com这个link早就在DNS服务器里了呀？@tommy @mc16888 你们用DNS看不了爱奇艺视频吗？

**Comment by tommyzhaozbh** [comment]
真看不了……还有那个多了一个i，之前是qiyi，现在是iqyi

**Comment by mc16888** [comment]
@tommyzhaozbh 我用 surge 这个app 直接在iphone 上抓包. 我之前用fiddler2 也没抓到。另外我弄了个DNS服务器，用DNS服务器的LOG去看iphone到底连了那些关于爱奇艺的domain, 之后再跟surge抓的包对一下就很容易找到上面那个新的URL.

**Comment by yanggis** [comment]
@tommyzhaozbh 我更新DNS了，看看可不可看得了。

**Comment by tommyzhaozbh** [comment]
嗬，居然可以了。
