### ISSUE TITLE
支持EDGE

### ISSUE THREAD

**Issue by fengshuo211** [uku/Unblock-Youku#687]
我知道unblock youku是一个chrome的插件，但现在edge也开始支持扩展了，请问有计划让unblock youku支持edge吗

**Comment by zhuzhuor** [comment]
@fengshuo211 多谢反馈，这个之前我也想过
但是 Edge 貌似暂时没有支持 proxy API 的打算，只能等支持了之后再开发 

Edge 现在计划支持的 API 列表可以在这里找到 https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/extension-api-roadmap/

这个 issue 就先 close，之后有后续更新欢迎 reopen
