### ISSUE TITLE
bilibili"No DNS Record"

### ISSUE THREAD

**Issue by sviivs1** [uku/Unblock-Youku#688]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:chrome  插件

请具体描述您遇到的问题（例如有问题的视频网址）：
bilibili看视频时，发生了"No DNS Record"
Lite也无效.

ERROR

The requested URL could not be retrieved

您所处的国家或地区：
英国

**Comment by sviivs1** [comment]
![79](https://cloud.githubusercontent.com/assets/20362603/17710598/d9e1e99c-63e5-11e6-803b-6a5f4cc46899.png)

**Comment by zhuzhuor** [comment]
@sviivs1 多谢反馈！这个问题我前两天也遇到了
稍微等一两分钟再刷新就好了，估计是 b 站自己的 DNS 的问题。你现在再试试还有问题吗？

不过之后可以在代理服务器上给这些网站的 DNS 做一下缓存，免得出现类似的问题

**Comment by sviivs1** [comment]
多谢赐教

**Comment by sunyiyun2001** [comment]
利用这个插件来做一个类似于hosts一样的东西如何？

**Comment by zhuzhuor** [comment]
@sunyiyun2001 chrome extension 没办法改 host 
chrome extension APIs 可以看 https://developer.chrome.com/extensions/api_index
