### ISSUE TITLE
unblock youku chrome 仿冒插件

### ISSUE THREAD

**Issue by smallzzy** [uku/Unblock-Youku#689]
你好， 现在在chrome web store 搜索unblock youku 会出现一个假的app， 会时不时弹广告

https://chrome.google.com/webstore/detail/unblock-youku/dokgmnpapgebodhihibnppgcbaboapco

![capture](https://cloud.githubusercontent.com/assets/3302921/17839647/f8a2faae-67a2-11e6-9f40-4c85592bb265.PNG)

![capture2](https://cloud.githubusercontent.com/assets/3302921/17839649/fb2fa7b8-67a2-11e6-8dca-1596c6bdb8b1.PNG)

您所处的国家或地区：US

**Comment by zhuzhuor** [comment]
@smallzzy 多谢反馈！现在 Google 已经把这个仿冒的软件下架了。如果 Report Abuse，理由充分的话一般都可以处理掉
