### ISSUE TITLE
b站ios端的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#690]
有用户在论坛反馈说b站的ios端看不了新番，无论是DNS抑或是pac全不行。谁能帮忙测试一下?
@mc16888 @yanggis

**Comment by mc16888** [comment]
@tommyzhaozbh PAC对bilibili ios客服端不起作用，一定要用DNS，我刚用158.69.209.100在iphone试了一下，没发现有问题啊.

**Comment by yanggis** [comment]
新番应该可以看的，那些反馈说不能看新番的基本是因为他们设置了DNS的同时还配置了PAC文件，导致解锁数据根本没有发送到DNS服务器。

**Comment by yanggis** [comment]
按优先级来说，VPN > 代理 > PAC文件 > DNS服务器，所以前面配置任何一种代理，都会干扰DNS服务器的解锁。

**Comment by tommyzhaozbh** [comment]
@mc16888 据说pac不行是因为它有https链接需要走代理?

**Comment by mc16888** [comment]
@tommyzhaozbh 好像没看到有https的连接。

**Comment by m274d** [comment]
@yanggis 感谢您的回答！
我想问下对于ios上的b站客户端问题，只要设置dns就够了吗？目前遇到的情况是
ios版本：9.3.1
bilibili客户端版本：4.26
dns：150和45都测试过了
坐标：香港
使用pac：点击版权新番后可以加载分集但是不能加载视频，已经在缓存列表内的视频也不能继续解析。
使用pac：点击版权新番后无法加载分集，显示：该内容不支持您所在的地区，已经在缓存列表内的视频也不能继续解析。

看了论坛和这里的issue还是没有完整的头绪，望不吝赐教！

**Comment by tommyzhaozbh** [comment]
@m274d 我测试了一下，iOS9.3.4搭载哔哩哔哩4.27新番是没有问题的，仅使用DNS。另外DNS和pac不要一起用，否则pac会盖过DNS。如果不行，请反馈一下你所在的网络环境。理论上香港的所有ISP都没有DNS劫持的，但学校这种就不担保了。

**Comment by m274d** [comment]
@tommyzhaozbh @yanggis 感谢解答！已经证实是香港酒店的dns网络限制！
目前坐标加州，使用150dns正常，无需pac！特此前来反馈～

btw，b站仅限港澳台地区的是不是就没有办法了？

**Comment by calpa** [comment]
@m274d 香港的ISP没有限制，大多没有问题，除非是私人机构挡住了。。。
