### ISSUE TITLE
疑似插件被植入广告程序？

### ISSUE THREAD

**Issue by rodejavic** [uku/Unblock-Youku#692]
求助，我的chrome浏览器只开unblock youku这一个应用，最近几天无论点击哪个网页总是弹出广告，显示是counterflix所为。各种杀软都用过了显示无毒。实在没办法了就把chrome卸载并重新安装，刚开始没事，但是enable unblock youku后再次出现疯狂弹广告的情况。再卸载，重装后关闭unblock youku则不再出现。

您所处的国家或地区：AU

**Comment by zhuzhuor** [comment]
你确定安装的是这个 Unblock Youku Chrome 扩展程序？ 还是装了别的垃圾扩展程序？
我们 Chrome Web Store 链接是 https://uku.im/chrome

**Comment by rodejavic** [comment]
@zhuzhuor 对的，最多评价的那个。

**Comment by zhuzhuor** [comment]
@rodejavic 你能把你的 chrome://extensions 帮忙截个图看看吗，看看有没有别的东西作祟
我们 Unblock Youku 扩展程序有[严格的白名单](https://github.com/uku/Unblock-Youku/blob/master/shared/urls.js)，所以不会照你说的所有网页上都起效的

感觉你这情况比较神奇，希望能多给我们提供点信息来找出问题所在，比如出现广告的网页截图之类的。如果可能的话希望能提供一下 Chrome developer console 里面的一些异常信息 https://developers.google.com/web/tools/chrome-devtools/debug/console/console-ui

**Comment by tommyzhaozbh** [comment]
Counterflix 其实是一个流氓软件，表面上是为了给人们突破地区限制上网的工具，其实只是一个捆绑了大量广告软件的流氓软件。根据网上的描述，由于他是利用DNS去达到类似Gostify那样的突破限制的，所以你最好检查一下你的DNS设置以及hosts文件有没有被修改并且清除一下DNS缓存试试。https://www.pcrisk.com/removal-guides/10184-counterflix-ads

**Comment by tommyzhaozbh** [comment]
还有这个 http://transcoder.baidu.com/from=0/bd_page_type=1/ssid=11e9746f6d6d797a68616f31393933411c/uid=0/pu=usm%401%2Csz%401320_1001%2Cta%40iphone_2_5.0_3_537/baiduid=C47D30056B486127A3E1111946DD28BF/w=0_10_counter+flix/t=iphone/l=3/tc?ref=www_iphone&lid=2458959529921688916&order=5&fm=alop&tj=www_normal_5_0_10_title&vit=osres&m=8&srd=1&cltj=cloud_title&asres=1&title=RemoveAdsbyCounterflix-VirusSolutionand...&dict=32&sec=14722&di=27b7b4828c3f0b5f&bdenc=1&tch=124.270.221.790.3.3562&nsrc=IlPT2AEptyoA_yixCFOxXnANedT62v3IEQGG_z-G2zm8jkioff4qEd6uS88wL8LTUS4swHW4csoYwk0dOjltnsVWf4gnvjdm6iq7sK_wtdPMUMtZ&eqid=221ffaaa120b36001000000657becbf7&wd=&clk_info=%7B%22srcid%22%3A%22www_normal%22%2C%22tplname%22%3A%22www_normal%22%2C%22t%22%3A1472121858174%2C%22xpath%22%3A%22div-a-h3%22%7D

**Comment by rodejavic** [comment]
@tommyzhaozbh ，似乎已经解决了

**Comment by zhuzhuor** [comment]
多谢 @tommyzhaozbh 帮忙
第一次听说这个 counterflix 和 gostify，两个网站都基本上一样
貌似是个 DNS service 但是还有很多垃圾软件？ Google 一搜全都是 how to remove adware counterflix/gostify...

**Comment by infosys2011** [comment]
我的页面上面也有Counterflix广告，始终删除不掉的，包括清除dns缓存和更改dns，都不行的

**Comment by zhuzhuor** [comment]
@infosys2011 请检查你是不是装了别的插件，可以在 chrome://extensions 页面看。另外 Windows 电脑的话试试重装一下 Windows？
