### ISSUE TITLE
提个小小的建议，能否给代理加上connect方法？

### ISSUE THREAD

**Issue by Lyken17** [uku/Unblock-Youku#693]
我平时用surge较多（因为自定义规则方便），看到有提供pac以后，就尝试着把http代理添加到surge的配置中。
<img width="427" alt="local surge dashboard today at 01 15 41" src="https://cloud.githubusercontent.com/assets/7783214/18025680/42f9b268-6be6-11e6-88ea-c4f713c6c81f.png">
设置好代理规则后，显示的是unnable to connect to the proxy server。在本地用cli测试正常

`➜  ~ curl -x http://proxy.uku.im:443 "http://www.bilibili.com"
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml”>
…
…`

猜测应该是服务器没有开启connect方法？不知道这个对服务器负载重不重，可以的话，希望能够开启。

**Comment by zhuzhuor** [comment]
connect 方法只能给 https 网站使用
普通的 http 代理也只会给 https 网站使用 connect 方法的，surge 里难道不是用的标准的协议？你再设置试试看？

**Comment by mc16888** [comment]
@zhuzhuor surge ios manual里面的known issue有提过 HTTP 是用 connect 连的。估计 MAC 版也一样。

http://surge.run/manual/

**Comment by Lyken17** [comment]
@zhuzhuor 不是很清楚底层的实现细节，所以去发邮件问了作者。

作者表示是需要上级服务器开启connect方法

<img width="452" alt="re 99 bundle mail today at 20 16 38" src="https://cloud.githubusercontent.com/assets/7783214/18031393/38e23216-6c93-11e6-9cc0-0f45ad89b6c9.png">
