### ISSUE TITLE
iOS升级后pac失效

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#694]
https://bbs.uku.im/t/youku-ipad/150/4
这是论坛的反馈，有用户说更新iOS 9.3.5之后pac完全失效，更新前没有问题。有谁碰到过这个问题？

**Comment by justwater910** [comment]
我也遇到这个问题哦。求解

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我试了下，的确是这样。 iOS 9.3.5 之后 PAC 就无效了
看 iOS 这尿性估计又是一时半会好不了了，要么就给 iOS 用户暂时只推荐 DNS 方法吧

**Comment by letlet** [comment]
我更新到iOS10了，还是没解决。要不要号召大家一起去苹果公司反映一下？
