### ISSUE TITLE
unblock youku在优酷上不好使了。。。

### ISSUE THREAD

**Issue by craneyuhe** [uku/Unblock-Youku#695]
最近看十宗罪 出现unblock youku chrome 插件失效的问题！

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

请具体描述您遇到的问题（例如有问题的视频网址）：

您所处的国家或地区：英国

**Comment by zhuzhuor** [comment]
@craneyuhe 你说的是这个电视剧吗 http://v.youku.com/v_show/id_XMTY1ODYzMjQ1Ng==.html

这个问题应该在最新版 v3.4.1 已经解决了，可以等待自动更新
如果着急的话，手动更新的办法可以看 http://weibo.com/5666348267/E5aXIs6Ek

**Comment by zhuzhuor** [comment]
这问题关掉了，如果有问题欢迎再来 reopen
