### ISSUE TITLE
用 DNS 访问 ipservice.163.com 偶尔会出现 503

### ISSUE THREAD

**Issue by zhuzhuor** [uku/Unblock-Youku#696]
@yanggis 大概 6-7 次访问会出现一次 503 Service Temporarily Unavailable，是不是后台有哪个代理服务器 down 了？另外这个错误信息是 nginx 生成的，这 nginx 是 163 的服务器呢还是我们的？

**Comment by yanggis** [comment]
@zhuzhuor 这个是因为我北京那个服务器相应有时候有点慢，我设置了DNS服务器等待响应时间比较短，如果超过那个时间就认为是503错误了。要不然大量的连接没有释放很占内存。不过测试了一下影响不太大。如果有问题我可以修改一下响应参数。

**Comment by zhuzhuor** [comment]
@yanggis 好，就是和你提一下这个问题，如果问题不大就行。我之后也注意观察下这的影响
