### ISSUE TITLE
ubuntu14.04搭建server端的问题

### ISSUE THREAD

**Issue by andy1247008998** [uku/Unblock-Youku#697]
首先我阅读了wiki中用centos搭建的教程，遗憾的是我唯一在内地的服务器运行的是ubuntu并且暂时没有计划变更操作系统。

我做了这些事情：
1.ubuntu14.04自带的是squid3，因此centos教程中所有的路径都对应替换为/etc/squid3/xxx
2.删除squid.conf中sogou的3行，因为已经过时。
3.注释掉cache一行，否则启动squid3后秒退。
4.在chrome插件中测试http+8888端口，结果为OK

遇到的问题：
1.cache的问题没有找到解决方法
2.启动squid后出现异常流量，甚至ssh登录也被阻断。停止squid后立刻解决。

如果您之前在ubuntu上顺利安装，或者有patch可以提供，请告诉我。
感谢

**Comment by tommyzhaozbh** [comment]
这个要叫老大过来 @zhuzhuor

**Comment by mc16888** [comment]
@andy1247008998 
问题1里的cache是指这两句吗 ？
`cache_dir ufs /var/spool/squid 2048 16 256`
`coredump_dir /var/spool/squid`

我自己的ubuntu14.04改成这样。
`cache_dir ufs /var/spool/squid3 2048 16 256`
`coredump_dir /var/spool/squid3`

问题2 我还没遇过，你换一个port看行不行。

**Comment by zhuzhuor** [comment]
@andy1247008998 Ubuntu 和 CentOS 下面的 Squid 配置文件不同，所以你需要做适当的修改
如果用 Ubuntu 安装 Squid 的话，推荐你直接修改 Ubuntu 自带的配置文件，这样就不会导致不能正常工作了
