### ISSUE TITLE
b站显示因为地区限制无法观看

### ISSUE THREAD

**Issue by rodejavic** [uku/Unblock-Youku#699]
![2016-09-08_125953](https://cloud.githubusercontent.com/assets/21236050/18335679/8c8cc68a-75c4-11e6-8b57-f1f3897feac7.png)
![2016-09-08_130548](https://cloud.githubusercontent.com/assets/21236050/18335777/6487cdaa-75c5-11e6-8d44-c3edd48735ba.png)

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Unblock youku, adblock

请具体描述您遇到的问题（例如有问题的视频网址）：Hi,我又来了.
今天点击b站新番显示因为地区限制的原因无法观看视频,关掉浏览器，但是能看到弹幕。 试了其它b站视频也是如此。情况如上图所示。 求助！

您所处的国家或地区：AU

**Comment by Jie211** [comment]
同样情况
Unblock youku, adblock
您所处的国家或地区：JP

**Comment by tommyzhaozbh** [comment]
应该是b站更新了规则，我试过也是这样。只要发现你不在大陆地区的话，当你加载视频的时候就会给你加载这个。但我没能搞清楚究竟是哪个地址在搞鬼（有的地址它看不到response），这个还要看看谁能搞懂了。

**Comment by zhuzhuor** [comment]
应该在最新版解决了，见 https://github.com/uku/Unblock-Youku/commit/154529888c762adf65afe252beba1e5b2448280b
如果之后还有问题，欢迎再来汇报

**Comment by rodejavic** [comment]
ok 我这边好了。 程序员万岁！

**Comment by Jie211** [comment]
@zhuzhuor 已经没问题了 close吧
