### ISSUE TITLE
B站新番貌似不能用unblock youku看了

### ISSUE THREAD

**Issue by zhengye1** [uku/Unblock-Youku#701]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Chrome

请具体描述您遇到的问题（例如有问题的视频网址）：今天去B站觀看love live sunshine的時候發現視頻錯誤，估計IP不對不讓看了...我Unblock youku是一直用標準模式的

您所处的国家或地区：加拿大

**Comment by zhuzhuor** [comment]
我刚才试了试 love live，观看没有问题
见 https://github.com/uku/Unblock-Youku/issues/699 最近针对最新版 b 站升级了一下，可以试试最新版 Unblock Youku v3.4.2 看还有问题没，如果还是有问题欢迎再来汇报
