### ISSUE TITLE
Mac OS有什么新办法可以下载歌吗

### ISSUE THREAD

**Issue by alec111234** [uku/Unblock-Youku#702]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Mac

请具体描述您遇到的问题（例如有问题的视频网址）：破解海外限制下载qq音乐跟网易云音乐？

您所处的国家或地区：美国

**Comment by oliverhuhan** [comment]
现在国内冲会员在海外不用这些代理都可以用

**Comment by summersky92** [comment]
终极解决办法。。。。。冲一个月会员  把歌曲都下了。。。。
