### ISSUE TITLE
B站部分限制區域影片無法觀看

### ISSUE THREAD

**Issue by s911415** [uku/Unblock-Youku#704]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Chrome Unblock Youku v3.4.2

请具体描述您遇到的问题（例如有问题的视频网址）：
B站部分資源使用https加載，使得影片位置無法取得
使用http://www.bilibili.com/video/avXXX/ 時，playurl使用https://interface.bilibili.com 加載無規則匹配，無使用代理抓位置
使用http://bangumi.bilibili.com/anime/v/XXX 時，是使用 http://bangumi.bilibili.com 加載，規則有匹配到，可以正常觀看

您所处的国家或地区：台北

**Comment by zhuzhuor** [comment]
我们的代理服务器也可以代理 https 链接
另外，你能提供个具体的 http://www.bilibili.com/video/avXXX/ 视频让我们测试吗

**Comment by s911415** [comment]
http://www.bilibili.com/video/av6292084/
http://bangumi.bilibili.com/anime/v/95801

**Comment by zhuzhuor** [comment]
https 的链接已经加在最新版的扩展程序里了 https://github.com/uku/Unblock-Youku/commit/86f9b82a3cf36b23200d9ad6ac5e3dccf7def6f0
等更新之后可以试试看效果
