### ISSUE TITLE
有关B站龟速的原因讨论

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#706]
B站龟速的问题最近很多人都察觉到。而ws.acgvideo.com所进行的302跳转看样子并不一定都是跳转到网宿的服务器（但也不排除是网宿租用的服务器，因为这些地址查出来都不属于网宿自己的）。
根据用户反馈回来的数据，不同地区的302跳转都有不同。但某种程度上有一定规律：澳洲的多数会直接跳转到北京网宿的服务器，日本的也是（这里打个问号，因为查出来的地址是写日本网宿，但IP whois却是CN，这就搞不懂了），港台区就直接是就近的（香港的就分配香港的，台湾的就分配台湾的，地址基本是所属ISP的CDN）。也就是说，基本上CDN的分配是符合就近原则的。
既然是符合就近原则，那基本上可以排除由于距离过远而导致的网速变慢。如果同城之间的数据传输都是那么慢的话，我的猜想就是：要么就是网宿调整服务器，要么就是网宿对CDN限速了。但至于是哪个，这就不懂了。

**Comment by komoesensei** [comment]
关于这个有人说连接后加载一会把unblock youku关掉后。。可以满速的样子。。
这个。。
https://bbs.uku.im/t/b/218/21?u=komoesensei

**Comment by tommyzhaozbh** [comment]
但我测试过，其实这样并不会改变视频源地址，该是哪个还是哪个，除非刷新才有可能，而且速度没有明显提升，开不开插件速度没差多少。而且B站的视频不分段，你还是从那个地方加载，那个其实只是假象而已。

**Comment by zhuyanjun0818** [comment]
日本 ，没有版权的东西关掉看就是满速的，开启unblock后速度网速监测显示200K动都不动一下，限制得非常完美(ˉ▽ˉ；)...

**Comment by CaptainCan** [comment]
Seattle 跟 zhuyanjun0818 一样的情况

**Comment by komoesensei** [comment]
由于用户量增长太快，今年以来，b站服务器和带宽的负载越来越捉襟见肘。为了保证所有人的观看体验，我们从9月8日起进行了带宽的再次升级，并对高峰时期（晚上8点至12点）的视频离线缓存进行了限速。目前带宽升级工程已经完成，但在高峰时期我们依然优先保证在线观看。预计本周内将对高峰期的离线缓存限速进行提升。如您确有下载需要，请在非高峰期操作。今后我们也将继续优化带宽分配方案，为用户提供更好的观看体验。高峰时段（20:00-24:00）具体限速方案如下：LV6 不限｜LV5 不限｜LV4 1000kb/s｜LV3 800kb/s｜LV2 600kb/s｜LV1 400kb/s｜LV0 200kb/s｜非注册用户 100kb/s。 注：实际下载速度受用户网络环境、网络硬件、网络服务提供商等多方面影响 。
