### ISSUE TITLE
B站需要解鎖區域限制的番劇全部都加載不了html5播放器了

### ISSUE THREAD

**Issue by dvdhoo** [uku/Unblock-Youku#707]
B站需要解鎖區域限制的番劇全部都加載不了html5播放器了，只能加載flash。
我指的是B站最新的內建HTML5播放器。前一段時間都能正常加載。

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome 插件

请具体描述您遇到的问题（例如有问题的视频网址）：bilibili.com

您所处的国家或地区：加拿大

**Comment by zhuzhuor** [comment]
我们没有控制是否加载 html5 播放器，是 b 站自己的设置问题吧

**Comment by tommyzhaozbh** [comment]
我测试了一下，当把播放器切换为html5播放器的时候，这条链接是没法正常通过代理的。但列表里面又有这条地址，真是奇怪。
![image](https://cloud.githubusercontent.com/assets/8757104/19672862/d3770a62-9aac-11e6-8064-ecf45b5f5de2.png)

**Comment by zhuzhuor** [comment]
@dvdhoo https://github.com/uku/Unblock-Youku/issues/716 里面提到了手动打开 html 播放器的办法，你可以试试

@tommyzhaozbh 见我在 #716 里面的回复，Chrome 里用的 PAC 文件，https url 只能有域名的部分了，不然不 work

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 这个应该是最新的Chrome才会这样吧？

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我用的 Chrome 版本号
![screen shot 2016-10-24 at 9 30 31 pm](https://cloud.githubusercontent.com/assets/928905/19673055/2e676dc6-9a31-11e6-89e4-872ad3b66f7b.png)

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 不过看样子Chrome早晚会塞死这个漏洞，起码ios已经是这样了。毕竟url后面的token太重要了，如果误装恶意插件的话那就完蛋了。

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 这个更改不是针对 chrome extension 的，这个用来抵御用 [WPAD](https://en.wikipedia.org/wiki/Web_Proxy_Autodiscovery_Protocol) 来攻击的。比如你去用咖啡店的公共 WiFi，WiFi 可能会给你的电脑用 WPAD 挂一个 PAC 文件

反过来 Chrome extensions 要弄类似攻击的话就不用这么麻烦，直接用 webRequest API 就行了。所以说 Chrome extension 的安全全靠 Web Store 的审核，还有用户的自觉（虽然说现在两个都还有一定问题）
