### ISSUE TITLE
B站iOS端规则更新

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#712]
最近用pac看B站（是的，pac在iOS10又可以用了），版权番失效了。我抓不到究竟是哪条规则，求帮忙～
@mc16888

**Comment by yanggis** [comment]
data.bilibili.com

**Comment by zhuzhuor** [comment]
@yanggis @tommyzhaozbh 是 https 还是 http 的？ 欢迎弄个 pull request

**Comment by mc16888** [comment]
@tommyzhaozbh  剛剛用iPhone 7 (10.0.3), Bilibili app ver 4.30 試了一下, pac 還是不能用. 也沒發現有什麼新規則, 今天晚上有時間再試.

**Comment by tommyzhaozbh** [comment]
@mc16888 pac我测试过uku.im/check以及在QQ音乐HD上可用，ios 10.0.2，但不知为何B站客户端就是不行。

**Comment by yanggis** [comment]
@tommyzhaozbh 直接挂全局代理可以看B站不？

**Comment by tommyzhaozbh** [comment]
全局是可以的，用了DNS也是可以的，但只用pac是不行的。

**Comment by yanggis** [comment]
@tommyzhaozbh 那应该就是PAC的bug，某个连接没有按规则抓取到让它走代理。既然DNS可以用，那就应该没有新增别的link，这一段一直都很稳定，B站的DNS规则一直都没有变化。
