### ISSUE TITLE
酷狗PC客户端即使 true 还是海外限制

### ISSUE THREAD

**Issue by brlala** [uku/Unblock-Youku#714]
**酷狗PC客户端**说**海外限制**。估计是酷狗用了不同的方式

用了DNS方式，status 显示 true，网易云/百度音乐/B站全都没问题

酷狗PC客户端连首页都不能显示。

您所处的国家或地区：马六甲 马来西亚

**Comment by yanggis** [comment]
现在酷狗音乐PC版加了基于IP的验证，就是这个连接，在一启动加载主界面的时候验证，这个是DNS没法解决的。
http://42.62.20.167/pc_success.html?tabid=2&uip=14.18.236.181&tra=192.168.1.1|10.93.0.1|10.93.0.1|&cip=192.168.1.139&dns=104.236.184.163,&url=http://www2.kugou.kugou.com/fm2/indexV2.html&html=&ver=8100&cid=1003&time=2016-10-22 9:47:20&kugouid=316706082

**Comment by brlala** [comment]
明白了 谢谢
