### ISSUE TITLE
有关自建服务器的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [uku/Unblock-Youku#715]
自己搭建的阿里云服务器，运行200多天了，一直都没有什么问题。但是最近速度越来越慢，今天甚至出现服务器连接超时的问题，有时候连后台都进不去。究竟是哪里出问题呢？

附部分性能检查数据：
![image](https://cloud.githubusercontent.com/assets/8757104/19638908/92f0ba8c-9a08-11e6-8917-09688c7abaf9.png)

**Comment by zhuzhuor** [comment]
观察下有没有 process 在偷跑流量，有可能是什么程序有漏洞或者默认弱密钥被 hack 了

**Comment by tommyzhaozbh** [comment]
Last login记录没有异常，机器负荷也不高，流量进出的怎么看?

**Comment by yanggis** [comment]
搜索linux流量监控，安装那个插件，运行命令就可以看到了。
不够你这种我觉得应该是系统文件故障，或者你和你的VPS之间通讯故障引起的。检查通讯故障很容易，VPN从另外一个国家登陆你的VPS就可以了。

**Comment by zmingxie** [comment]
会不会是因为用久了以后太多的open socket或者file descriptor没有被free up?

可以看一下`pidof` 或者`netstat -l`的output
