### ISSUE TITLE
bilibili HTML5無法播放了

### ISSUE THREAD

**Issue by cxz9001** [uku/Unblock-Youku#716]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome 插件

请具体描述您遇到的问题（例如有问题的视频网址）：http://bangumi.bilibili.com/anime/v/96154

您所处的国家或地区：台灣
使用HTML5播放器無法撥放(FLASH播放器可以)

用HTML5播放器要先打開↓
http://www.bilibili.com/html/help.html#p
![image](https://cloud.githubusercontent.com/assets/7628517/19641682/52aa2d44-9a14-11e6-9d9f-5fea3cc49709.png)
![image](https://cloud.githubusercontent.com/assets/7628517/19641701/70033296-9a14-11e6-8be6-23e771248849.png)
![image](https://cloud.githubusercontent.com/assets/7628517/19641704/7c742ec2-9a14-11e6-830c-66f4fee151f9.png)

**Comment by newgene01** [comment]
剛才重新整理後同樣被擋版權OTZ
好像是因為今天HTML5播放器更新後開始支援新番了
之前新番只能用FLASH看
可能HTML5播放器用了什麼新的偵測法

好不容易今年終於等到B站支援HTML5了
CHROME用FLASH開十幾個就開始崩潰
HTML5開再多分頁也無所謂
而且只有HTML5有1080P阿阿阿

**Comment by zhuzhuor** [comment]
![screen shot 2016-10-24 at 8 50 23 am](https://cloud.githubusercontent.com/assets/928905/19652767/efbcbdac-99c6-11e6-8ec9-bde0734e2dce.png)

我这里可以 reproduce，之后帮忙看看

**Comment by zhuzhuor** [comment]
应该在 https://github.com/uku/Unblock-Youku/commit/f71317ce36a995cb403d79131eba39c511c820d6 里面 fix 了。最新版刚上传到 Chrome Web Store，自动 push 给用户还要等几个小时到一天的时间。之后你们再试试，如果还是有问题欢迎再来反馈


另外在这里记录一下，Chrome 貌似也开始不给 PAC 文件完整的 HTTPS URL 了。例如如果 PAC 有类似 `https://example.com/abc/*` 的 URL 就不会 work，只有用 `https://example.com/*` 才行
猜测是为了抵御这个利用 PAC 来泄露 https full url 的攻击 https://www.blackhat.com/docs/us-16/materials/us-16-Kotler-Crippling-HTTPS-With-Unholy-PAC.pdf
@mc16888 @tommyzhaozbh @yanggis
