### ISSUE TITLE
海美迪H7 三代设置DNS依然无法观看大陆节目

### ISSUE THREAD

**Issue by flamedd** [uku/Unblock-Youku#717]
我用的H7 二代没有问题，但是用3代的时候虽然设置了DNS，但是芒果TV依然有大陆观看限制

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:海美迪H7三代

请具体描述您遇到的问题（例如有问题的视频网址）：我用的H7 二代没有问题，但是用3代的时候虽然设置了DNS，但是芒果TV依然有大陆观看限制

您所处的国家或地区：

**Comment by yanggis** [comment]
那是因为3代的海美迪更改了IP验证的link,你用的是海美迪自带的芒果TV，这个我们没有这个设备，没法测试问题到底出在什么地方。

**Comment by flamedd** [comment]
所以我用老的固件或者老版本的芒果tv也没用了吗？这是和三代的硬件有关？






On Fri, Oct 28, 2016 at 8:44 PM -0500, "X.K. YANG" <notifications@github.com> wrote:












那是因为3代的海美迪更改了IP验证的link,你用的是海美迪自带的芒果TV，这个我们没有这个设备，没法测试问题到底出在什么地方。

**Comment by yanggis** [comment]
除非你用海美迪二代固件，不过那个不太可能兼容。或者你可以单独联系我，我告诉你怎么测试和抓包，兴许可以解锁。

**Comment by flamedd** [comment]
这个怎么联系你？大概需要多久来测试？

**Comment by yanggis** [comment]
发邮件给我吧！不确定要测多久。

**Comment by yuiop99** [comment]
我新买的A8也有同样的问题，旧的海美迪hd600a四核没问题。

**Comment by yuiop99** [comment]
还有在nexus 7， nexus 9上也改dns也不能看

**Comment by yanggis** [comment]
您在nexus上安装的芒果tv这个APP吗？

**Comment by yanggis** [comment]
@yuiop99 新版的海美迪自带的芒果TV都不支持，因为没人帮抓包，我自己没有海美迪的设备，所以没法测试问题问题出在哪里。

**Comment by yanggis** [comment]
@yuiop99 另外您可以把海美迪和你的Nexus root一下，然后在google play搜索安装chinatunnel，看看是否可以解决。

**Comment by yuiop99** [comment]
我尝试我root我的海美迪都不成功，所以不能是chinatunnel.

**Comment by yuiop99** [comment]
在海美迪上貌似是改了DNS但是其实没改到，好像系统不给改。我试了用当贝市场里面的改DNS功能就可以很明显看出能改跟不能改的区别。

**Comment by yanggis** [comment]
如果该改DNS都改不了的话，那就只能root安装chinatunnel了，别无他法了。

**Comment by wtjfree** [comment]
yuiop99 好好找找root方法吧. 应该可以root的.

**Comment by zhuzhuor** [comment]
这个 issue 先 close 了，有问题欢迎再来 reopen
