### ISSUE TITLE
你好，由于不是很稳定，我想自己搭建一个服务器，但是我看你们的是HTTPS 代理，和教程上PROXY不一样，请问HTTPS都会用到什么技术，还是squid的吗，服务器上需要装什么软件，能不能简要回答下，我好根据你们提供的线索去Google，技术小白，飘过

### ISSUE THREAD

**Issue by ILoveMoneyAndGirl** [uku/Unblock-Youku#718]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

请具体描述您遇到的问题（例如有问题的视频网址）：

您所处的国家或地区：

**Comment by wtjfree** [comment]
我也准备要用OPENWRT的路由器搭建unlock youku服务.

我有个疑问.请问这个路由器作为服务端, 地理位置是应该在国内还是在国外也可以?
另外也想了解一下如果在路由器上同时提供DNS服务,是不是对解锁有很大帮助呢?

我看美团云的教程是在国内搞vps.和国内同学科学上网有异曲同工之妙.

**Comment by zhuzhuor** [comment]
@ILoveMoneyAndGirl 不需要特殊的技术，我们用 HTTPS 有一些历史原因。你自己搭建的squid 服务器用 HTTP 就可以了

**Comment by zhuzhuor** [comment]
@wtjfree 必须得要一个国内的服务器才行。路由器肯定在你海外的局域网，需要一个国内的 squid 代理服务器做配合

**Comment by wtjfree** [comment]
@zhuzhuor 您理解错了。 我是要部署unlock youku在国内的openwrt路由器上。能稍微指点以下安装或者需要什么环境吗？

**Comment by wtjfree** [comment]
大概撸了一遍unlock youku的wiki 貌似现在就只有squid唯一的解。也就是说我在国内路由器上安装squid的服务端应该就可以了是吗？

**Comment by zhuzhuor** [comment]
@wtjfree 对，国内的路由器上安装个 squid 就行了
