### ISSUE TITLE
Bilibili Clips Under Domain bangumi.bilibili.com Blocked with HTML5 Player

### ISSUE THREAD

**Issue by maobowen** [uku/Unblock-Youku#719]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: PAC

请具体描述您遇到的问题（例如有问题的视频网址）：
Bilibili clips under domain **bangumi.bilibili.com** are blocked using HTML5 player, but work fine with Flash Player.

I used PAC file http://yo.uku.im/proxy.pac as proxy configuration in macOS 10.12.
![image](https://cloud.githubusercontent.com/assets/14121443/20028207/d9d76480-a301-11e6-9fbd-804eac00a12c.png)

It worked fine with Flash Player.
![image](https://cloud.githubusercontent.com/assets/14121443/20028257/d8c84a90-a302-11e6-99c4-71fce560b197.png)
And IP check http://ipservice.163.com/isFromMainland worked fine as well.
![image](https://cloud.githubusercontent.com/assets/14121443/20028259/f0249ae0-a302-11e6-98a2-a095daf276d1.png)

However, when I switched to HTML5 Player, the clip was blocked.
![image](https://cloud.githubusercontent.com/assets/14121443/20028291/f096c880-a303-11e6-8042-124f14809b5c.png)
And if I refreshed http://ipservice.163.com/isFromMainland, it became false immediately. Then I had to reset my network or to wait for several minutes until it automatically became true again.
![image](https://cloud.githubusercontent.com/assets/14121443/20028303/38105e7e-a304-11e6-86fe-07fe39c4ed9c.png)

Any clips under domain **bangumi.bilibili.com** can be used to reproduced this issue. I walked through the traffic but was unable to find out how bilibili performed geo check and why HTML5 could not be used while Flash Player could.
I found a related issue #716 here, but was not sure it helps. Since I want to stick on using PAC rather than installing Chrome extension, are there any possible solutions? You know what, Flash Player sucks on MacBook, so I want to get rid of it asap.

您所处的国家或地区：United States

**Comment by tommyzhaozbh** [comment]
This is because the html5 player uses https to check the IP address while the pac method seems not able to solve the https proxy. Some users have reported this issue but we don't have a good solution for that yet.
