### ISSUE TITLE
海外bilibili变慢，希望可以排除特定网站

### ISSUE THREAD

**Issue by XUJINKAI** [uku/Unblock-Youku#720]
我在台湾，bilibili在标准模式下反而会很慢，希望可以排除特定网站

**Comment by tommyzhaozbh** [comment]
B站对于不同视频有不同域名，凡是域名以bangumi开头的都是版权番剧，速度都很正常，但www开头的(包含一些非版权视频和其他视频)一过代理全部有限速。
问题就是，如果把www域名下的过滤规则删掉，部分视频就会出现15秒的肥肠抱歉，所以不好处理。目前唯一的办法就是在看没地区限制视频的时候把代理关掉。
PS: 既然很多番剧都已经换了bangumi的地址，不如试行把interface.bilibili.com删掉看看有没有用户反馈说看不来? @zhuzhuor

**Comment by zhuzhuor** [comment]
见 https://github.com/uku/Unblock-Youku/pull/722
