### ISSUE TITLE
Bilibili html5播放器视频服务 地址

### ISSUE THREAD

**Issue by JoeyWNK** [uku/Unblock-Youku#723]
```
http://cn-zjwz4-dx.acgvideo.com/vg9/
http://cn-jsks2-dx.acgvideo.com/vg3/
http://cn-zjjh14-dx.acgvideo.com/vg3/
```
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
PAC/ Chrome Proxy
请具体描述您遇到的问题（例如有问题的视频网址）：
例如 视频地址：
`https://cn-zjjh14-dx.acgvideo.com/vg3/3/a1/8986943-1.mp4?expires=1480390800&ssig=EOgk7SKYqe1K1dpQEVDAOw&oi=3078818617&rate=0`
直接访问就会遇到屏蔽
您所处的国家或地区：
北美

**Comment by zhuzhuor** [comment]
能提供相关的视频地址来测试下吗？

**Comment by JoeyWNK** [comment]
测试地址：[http://bangumi.bilibili.com/anime/v/95970](http://bangumi.bilibili.com/anime/v/95970)
可能有广告视频，现在bilibili应该在灰度发布，不同的访问形式触发的来源不一样
默认flash播放器使用flv格式，视频地址是`ws.acgvideo.com`没有问题
需要切换html播放器（右上角），当视频格式是mp4时，就会发送一个15s左右的失败视频
![image](https://cloud.githubusercontent.com/assets/6046395/20860700/79b7d344-b94c-11e6-9e7b-08b55c87c763.png)
以下是截取到的链接`https://bangumi.bilibili.com/player/web_api/playurl`上的播放地址
![image](https://cloud.githubusercontent.com/assets/6046395/20860713/a3a6e532-b94c-11e6-98ac-8d592968fc49.png)
通讯协议有可能会是`https`

**Comment by LLin233** [comment]
我现在是直接无法加载播放器....

**Comment by zhuzhuor** [comment]
@JoeyWNK 我试了下把 #722 的更新 revert 了就好，我这就更新下吧
另外，不用把 acgvideo.com 通过代理也可以，你还遇到别的视频吗，我再试试？

**Comment by JoeyWNK** [comment]
@zhuzhuor 
我感觉这跟我使用的代理方式有关系，我使用了[SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega)插件

关于Bilibili的代理规则只有两条

- 220.243.230.209

- bangumi.bilibili.com

代理服务使用了两个
- PAC http://pac.uku.im/pac.pac

- https secure.uku.im

访问bangumi的时候
使用http proxy没有问题，Developer Tools上记录到的视频地址是ws.acgvideo.com的flv格式
但是使用PAC作为代理，Developer Tools上记录到的视频地址是cn-zjwz4-dx.acgvideo.com的mp4格式，然而该地址会检查访问ip，如果是海外的就直接发送失败15s失败的视频

**Comment by zhuzhuor** [comment]
@JoeyWNK 你是说 b 站可能在做 a/b test？有些用户得到的是 mp4 有些用户得到的是 flv? 难道我代理 interface.bilibili.com 了之后只是偶然触发了 a/b test 中的一种？

你说 `使用http proxy没有问题`，这个 http proxy 指的是？

**Comment by JoeyWNK** [comment]
@zhuzhuor 我认为是在a/b test，不过没足够的样本
b站的html5播放器支持flv格式[html播放器更新日志](http://www.bilibili.com/html/webplayer_history.html#html5)所以这个来源地址到底怎么分配的，我也没搞明白，可能与访问ip有关系
感觉测试不好做的原因还有一个就是浏览器自己会缓存。。。所以感觉更复杂了
http proxy 使用了`secure.uku.im:8443`这个代理服务
