### ISSUE TITLE
Music.QQ unable to access 

### ISSUE THREAD

**Issue by hayvesyong** [uku/Unblock-Youku#725]
Hi there,

It seems like the Music.QQ is no longer working with Youku Unblock. Wonderingly am i the only person not able to access to listen with Music.QQ??

I am accessing the website from Norway.

Thanks and will deeply appreciated your help, feedback and reply.

Regards,
Hayves

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Chrome plugin app

请具体描述您遇到的问题（例如有问题的视频网址）：https://y.qq.com/

您所处的国家或地区：Norway

**Comment by tommyzhaozbh** [comment]
Remember to log in before using. Otherwise the web version cannot be used due to district restriction.

**Comment by hayvesyong** [comment]
Even I have logged in with my QQ account, it still showing out the region restriction as below.

"抱歉，应版权方要求，暂无法在当前国家或地区提供此歌曲服务，但可以去看MV哦"

Any ideal how to resolve it??

Thanks.

**Comment by tommyzhaozbh** [comment]
I know what happened now. QQ music has changed all the links into https, which makes most of the proxy rules expired. But interestingly, since I used to be a paid user, the change to https doesn't have any effect on me, even though I'm not a paid user now.
