### ISSUE TITLE
网易云音乐的电脑客户端在离线下载音乐时会立即失败

### ISSUE THREAD

**Issue by Patrick-Liao** [uku/Unblock-Youku#730]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: DNS

请具体描述您遇到的问题（例如有问题的视频网址）：
本人是在自己的SFO的debian服务器上用了你们的dns，然后用IPsec/L2TP连接自己的电脑，结果在网易云音乐上（电脑端）下载音乐的时候会马上就失败，而手机版就没有这个问题，话说我直接在自己的电脑上改DNS也是这个问题，求解。是不是下载的服务器的解析记录有误（没代理下载服务器的地址?）谢谢

您所处的国家或地区: 美东，宾夕法尼亚州

**Comment by ToadJiang** [comment]
更新：出现问题的都是有版权（在海外无法播放）的音乐

**Comment by yanggis** [comment]
不管是手机或者电脑，只要有一个可以正常解锁，就说明我们的DNS服务器没有问题，因为DNS服务器down掉，任何设备都应该是无法解锁的。你说的某个设备无法解锁十有八九应该是你自己配置的问题。

**Comment by zjgcainiao** [comment]
DNS服務器沒有問題，可以很正常的下載網易云音樂歌曲。Device Info: iMac OS El Captain; Android 7.1.1 and iOS 10.1. @ToadJiang  try to check local setup.

**Comment by LBYPatrick** [comment]
我指的是PC端都没法用下载，手机就可以，麻烦看清楚。可能是PC端用的服务器域名不一样，导致PC的下载功能解锁失败

**Comment by zjgcainiao** [comment]
我看的很清楚。 你說的是Debian。我說我的Mac ，手機都好用。 麻煩你看清楚。 所以建議你看看local config
Sent from Yahoo Mail on Android 
 
  On Mon, Dec 12, 2016 at 5:34 PM, LBYPatrick<notifications@github.com> wrote:   我指的是PC端都没法用下载，手机就可以，麻烦看清楚。可能是PC端用的服务器域名不一样，导致PC的下载功能解锁失败
