### ISSUE TITLE
QQ音乐版权问题解决办法

### ISSUE THREAD

**Issue by cameron93lin** [uku/Unblock-Youku#731]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
QQ音乐
请具体描述您遇到的问题（例如有问题的视频网址）：
QQ音乐无法播放
您所处的国家或地区：
美国

通过解析qq音乐网页的js文件和网络抓包，发现qq音乐通过http://jqmt.qq.com/rpt.png 这个网址检测是否为大陆ip，将pac文件中的jqmt.qq.com挂上代理即可解决。

**Comment by tommyzhaozbh** [comment]
这个有点稀奇，得叫人过来看看。@mc16888 @yanggis

**Comment by yanggis** [comment]
png格式显然是个图片啊，楼主不是在开玩笑吧？

**Comment by mc16888** [comment]
@tommyzhaozbh @yanggis 我剛試了一下,沒發現連這一個url. 
@cameron93lin 你是用客服端還是網頁版 ?

**Comment by cameron93lin** [comment]
没开玩笑……我也很奇怪 但是你打开这个链接就会发现不是一个png文件，这个方法仅限网页版，mac的app和手机的app都不行，还在研究怎么弄，打算通过抓包看看能不能弄到检测的地址，反正我现在用自己的pac（综合你们的pac和unblockcn的pac，unblockcn的pac访问网易云速度快）然后pac里加上了jqmt.qq.com的访问代理，网页版的QQ音乐就可以听了 @mc16888 @tommyzhaozbh @yanggis

**Comment by yanggis** [comment]
网页版的QQ音乐不是一直都可以听吗？

**Comment by cameron93lin** [comment]
if (shExpMatch(url, "fcg_action_ctrl")) {
    } 

用这个可以绕过app版的限制

**Comment by cameron93lin** [comment]
@yanggis 啊?为啥我之前不行……所以我才研究怎么弄

**Comment by yanggis** [comment]
@cameron93lin 网页版是最容易解锁的，具体PAC的问题@tommyzhaozbh 应该比较了解。

**Comment by tommyzhaozbh** [comment]
pac的话今天也出问题了。我在用HD版QQ音乐，之前一直都行的，今天搜索全是灰色的。抓了一下发现IP地址变了
![image](https://cloud.githubusercontent.com/assets/8757104/21171388/d108c366-c206-11e6-8574-b24c8dc0ec08.png)
DNS反查的结果显示对应的域名是shacc.music.qq.com，而不是之前的acc.music.qq.com，可能是因为那是上海的服务器所以加了sh这玩意……
![image](https://cloud.githubusercontent.com/assets/8757104/21171881/a8bb68ac-c209-11e6-83b2-45b18bec4804.png)
好奇之下翻查了一下 #536 里面 @mc16888 所给的地址，发现这些地址基本上都是上海或者深圳的，于是又翻了一下szacc.music.qq.com的DNS记录，结果也是出奇般相似。
![image](https://cloud.githubusercontent.com/assets/8757104/21171893/cbc5f560-c209-11e6-95c3-290e7721836a.png)
但我搜hkacc.music.qq.com的时候却出来了将近70个地址，看来这应该不是了，暂时在pac里面加着这些吧。不知道你们是不是也是测试到类似的地址呢？

**Comment by cameron93lin** [comment]
@tommyzhaozbh 我自己弄了个pac文件  你可以看看能不能用  我这里测试的是可以用的，QQ音乐mac版和网页版都能用   www.unlguide.com/unblock.pac 使用了你们的pac文件以及加入了unblockcn的服务器来访问网易云音乐，因为比较快= =

**Comment by cameron93lin** [comment]
@tommyzhaozbh 在QQ音乐的app中抓包发现的访问一个文件fcg_action_ctrl 是那种IP地址中的文件 我用pac代理访问这个文件就可以播放了

**Comment by tommyzhaozbh** [comment]
刚测试了一下，移动app不行

**Comment by yanggis** [comment]
@tommyzhaozbh  acc的那几个链接是不是根本不需要加啊？
移动app是IPhone还是android的呀？

**Comment by tommyzhaozbh** [comment]
苹果的，这是抓包捉到的

**Comment by cameron93lin** [comment]
啊 我之前发完改了一下pac文件…现在改回来了  我这边苹果设备测试没有问题啊…

**Comment by tommyzhaozbh** [comment]
我用的是HD版，可能跟手机版有不同。

**Comment by cameron93lin** [comment]
你现在试一下  用我的pac文件做代理看行不行  我这边周杰伦的歌都能听

**Comment by tommyzhaozbh** [comment]
现在可以了

**Comment by cameron93lin** [comment]
我是直接用url里有没有getsession做判断条件，感觉这个比较好一点，不管换不换服务器都可以用

**Comment by yanggis** [comment]
@cameron93lin 你这种是非常危险的，不要玩火。按你这个，随便一个加一个参数http://www.baidu.com/tt=fcg_action_ctrl,这个连接就会被导到代理服务器，甚至是一个钓鱼网站连接，里面加一个这个字符串fcg_action_ctrl，都可以被导近代理服务器，是非常危险的！

**Comment by cameron93lin** [comment]
啊 那就只能去找用的哪个服务器了么……我没考虑到这个 只是想着能用就行= =
