### ISSUE TITLE
QQ音乐 windows客户端无法打开音乐馆和电台

### ISSUE THREAD

**Issue by LesterLyu** [uku/Unblock-Youku#733]
https://c.y.qq.com 好像屏蔽了你们的服务器， 注意，是https，http没有屏蔽，不是很懂= =

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: PAC

请具体描述您遇到的问题（例如有问题的视频网址）：503 Forbidden: https://c.y.qq.com/v8/fcg-bin/fcg_v8_radiolist.fcg?channel=radio&format=html&page=index&tpl=wk&new=1 

您所处的国家或地区：Canada

**Comment by LesterLyu** [comment]
补充下，Android上无论改DNS或用PAC代理，都无法使用qq音乐。ios上就可以。

**Comment by yanggis** [comment]
手机root的话就只能chinatunnel吧，其他无解……，因为QQ音乐android客户端用的是非http的验证，所有Http的解锁方法都会无效。

**Comment by LesterLyu** [comment]
这就很尴尬了，ios竟然和Android不用一样的方式通信。
