### ISSUE TITLE
B站DNS规则需要更新

### ISSUE THREAD

**Issue by Patrick-Liao** [uku/Unblock-Youku#734]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: DNS

请具体描述您遇到的问题（例如有问题的视频网址）：感觉规则需要更新了，b站播放版权番的时候在网页端的播放器会直接加载不出来，无版权的正常（外加所有iOS和安卓的APP客户端都正常，因为播放器已经在本地了）

您所处的国家或地区：北美

**Comment by yanggis** [comment]
网页版加载不了和DNS没关系。DNS就只拦截那2个link，如果iOS和安卓的APP客户端都正常，就说明DNS针对B站运行时正常的。
