### ISSUE TITLE
爱奇艺pps不能正常播放了

### ISSUE THREAD

**Issue by cz1997** [uku/Unblock-Youku#735]
我人在欧洲捷克，之前一直在用158DNS
![png2](https://cloud.githubusercontent.com/assets/24873223/21587323/4932aa4a-d0db-11e6-9988-b6a4184edd95.png)

，一直正常但是就是2017年1月1号就不能正常用 pps爱奇艺，我一点击某些视频就会出现这个
![png1](https://cloud.githubusercontent.com/assets/24873223/21587234/30c98e66-d0da-11e6-8986-9227622efc24.png)
请问怎么解决这个问题？？           谢谢

**Comment by cz1997** [comment]
用158DNS看优酷视频就正常

**Comment by yanggis** [comment]
dns代理服务器的IP被爱奇艺封了

**Comment by cz1997** [comment]
也就是说以后就别想看爱奇艺了

**Comment by yanggis** [comment]
现在在想别的办法，

**Comment by cz1997** [comment]
辛苦了，谢谢

**Comment by yanggis** [comment]
现在爱奇艺应该可以了。

**Comment by cz1997** [comment]
非常感谢，辛苦了。

**Comment by cz1997** [comment]
又重新出现这个了
![png 1](https://cloud.githubusercontent.com/assets/24873223/21819255/3e088ee6-d76b-11e6-9f88-2d8752e82bde.png)

**Comment by cz1997** [comment]
前几天明明正常了，不知道为什么又没用了。

**Comment by cz1997** [comment]
可以了

**Comment by cz1997** [comment]
![png45](https://cloud.githubusercontent.com/assets/24873223/22430628/2d02b672-e70f-11e6-852e-b72bba90aa6b.png)
现在能正常看了，但是不能正常下载

**Comment by cz1997** [comment]
大神你不是说一切DNS的问题，都在dns反馈里提问吗?我在哪里提问了但是没人理会。

**Comment by yanggis** [comment]
@cz1997 什么问题没人回答你啊？

**Comment by cz1997** [comment]
![png11](https://cloud.githubusercontent.com/assets/24873223/22432919/ddfc24a2-e716-11e6-9f3b-8b6643aa4601.png)
![png45](https://cloud.githubusercontent.com/assets/24873223/22432920/ddfc29f2-e716-11e6-8e11-e4d933559c27.png)

**Comment by cz1997** [comment]
我刚刚把问题做了一些修改所以显示的是今天，这个问题早在半个月前就放上去了就一直没人做出理会。

**Comment by yanggis** [comment]
反馈问题之前看看以前已有的issues，有些之前都已经反馈过了做过解释了。
DNS的问题是在这里反馈的，
https://github.com/uku/Unblock-Youku/issues/618

你发在那个地方很少有人去看的。

反馈问题不要用一些模糊性的词，比如unblock-youku用不了，什么看不了之类的，我们都知道你是因为用不了看不了才来反馈的，看得了你也不会来反馈嘛。

你要反馈你用的哪个服务器，你自己的设备是android设备还是iOS设备，看的是哪个视频？我们连这些信息都不知道，怎么帮你测试问题出在哪里呀？

**Comment by cz1997** [comment]
哦～知道了，谢谢大神。
