### ISSUE TITLE
PCqq音乐无法显示页面

### ISSUE THREAD

**Issue by cz1997** [uku/Unblock-Youku#736]
qq音乐出现这个能解决吗？我也是158DNS
![png3](https://cloud.githubusercontent.com/assets/24873223/21610878/be26477c-d1ca-11e6-8f07-b063bc6878f8.png)
谢谢

**Comment by cz1997** [comment]
辛苦了

**Comment by tommyzhaozbh** [comment]
现在这个问题应该解决了的，再试试

**Comment by cz1997** [comment]
网页是显示出来了，但是又有新问题出现了，就是不能点击播放，听。
![png4](https://cloud.githubusercontent.com/assets/24873223/21627826/ee6c20c8-d21a-11e6-9e95-576c263309f4.png)

**Comment by tommyzhaozbh** [comment]
我啥问题都木有诶
![image](https://cloud.githubusercontent.com/assets/8757104/21633068/fc105d40-d286-11e6-8c50-9453eb979544.png)

**Comment by cz1997** [comment]
我一会再试试

**Comment by cz1997** [comment]
可以了，谢谢。
