### ISSUE TITLE
Firefox 51 無法使用 PAC 規則追看 Bilibili 新番

### ISSUE THREAD

**Issue by hkgsherlock** [uku/Unblock-Youku#738]
**您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:**
PAC `http://pac.uku.im/pac.pac`
Firefox 51 (```Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0```)

**请具体描述您遇到的问题（例如有问题的视频网址）：**
在 1 月 4 日開始無法使用 Firefox + PAC 方法繞過 Bilibili 版權區域限制觀看新番。<br/>
(另，此前使用 Firefox 觀看新番時，Firefox 曾經更新過 (42 --> 51)。)

不過，在 Chromium 55 Dev Build (`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36`) 配搭 Unblock Youku 插件進入同樣新番頁面並沒有出現同樣問題。

瀏覽頁面為 `/anime/5523/play#96675`。

**您所处的国家或地区：**
香港

---

([補充 HAR 資料，Firefox 51 + Chromium 55](https://gist.github.com/hkgsherlock/3ba85e207f905b9f041fb9cfef3516c7))

**Comment by tommyzhaozbh** [comment]
pac所使用的服务器目前被攻击暂时无法使用

**Comment by hkgsherlock** [comment]
了解します
