### ISSUE TITLE
新手求助，有木有更新的全局解锁用在路由器上的UNBLOCK YOUKU教程呀？？？

### ISSUE THREAD

**Issue by allenrong88** [uku/Unblock-Youku#739]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: 路由器全局解锁

请具体描述您遇到的问题（例如有问题的视频网址）：如题，有木有更新的全局解锁用在路由器上的UNBLOCK YOUKU教程呀？？？之前那个貌似是2013年哒，下载链接也失效了。除了基于OPENWRT，有木有可能在gargoyle，OPENWRT下的一个分支上用呀？

您所处的国家或地区：澳洲

谢谢大神们

**Comment by yanggis** [comment]
这个没有，这种用的人太少，还要花费太多精力维护，又和设备端解锁重叠，没太大开发的必要。

**Comment by allenrong88** [comment]
谢谢大神。不知道有木有用在OPENWRT上的教程呢？这样就可以解索局域网上所有设备了。

**Comment by yanggis** [comment]
也木有。。。

**Comment by yanggis** [comment]
你给局域网设备配解锁的dns不就OK了吗？

**Comment by allenrong88** [comment]
那是不是在路由器里把ISP的DNS换成UNBLOCK YOUKU的DNS就行了？

**Comment by yanggis** [comment]
这个不同的路由器略有区别，你要自己摸索一下，不过肯定是很简单的

**Comment by allenrong88** [comment]
恩。。。谢谢大神

**Comment by brlala** [comment]
@allenrong88 直接在openwrt 把DNS改去158.69.209.100不就行了吗？
