### ISSUE TITLE
爱奇艺pps又不能正常播放了

### ISSUE THREAD

**Issue by cz1997** [uku/Unblock-Youku#740]
我检查了一下网络正常啊，优酷都能正常播放，就是爱奇艺不行
![png2](https://cloud.githubusercontent.com/assets/24873223/21851746/b713fa96-d810-11e6-94e7-5c92e04e0fe4.png)

我点击这个视频就会出现这个
![png4](https://cloud.githubusercontent.com/assets/24873223/21852070/f7779f60-d811-11e6-8ef4-7db65f9356bd.png)

人在欧洲

**Comment by cz1997** [comment]
点击其他的视频也是一样。

**Comment by cz1997** [comment]
我没更改DNS
![png5](https://cloud.githubusercontent.com/assets/24873223/21852206/80c8bbbe-d812-11e6-8fd5-c14ce9689c22.png)

**Comment by cz1997** [comment]
是网络问题吗？

**Comment by cz1997** [comment]
我这个没办法修复吗？

**Comment by yanggis** [comment]
IP又被封了

**Comment by cz1997** [comment]
是吗？该死的爱奇艺公司

**Comment by cz1997** [comment]
嗨，看了是真的没办法了。

**Comment by cz1997** [comment]
不够，我也要非常感谢您，百忙之中回复我，
非常谢谢

**Comment by cz1997** [comment]
是没办法咯？？
我们全家人都在用158DNS看爱奇艺。

**Comment by yanggis** [comment]
抱歉，这个现在在想办法解决，需要时间。。。。

**Comment by cz1997** [comment]
嗯 加油大神
