### ISSUE TITLE
希望支持优酷会员续费页面

### ISSUE THREAD

**Issue by guyigenius** [uku/Unblock-Youku#741]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）：Chrome 插件

请具体描述您遇到的问题（例如有问题的视频网址）：
http://pay.youku.com/buy/products.html 无法访问。
This site can’t be reached
pay.youku.com’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
更改 DNS 可以正常访问，但是 Chrome 插件不行，希望可以支持一下，谢谢。

您所处的国家或地区：美国

**Comment by tommyzhaozbh** [comment]
那是你默认的dns服务器有问题，插件本来就支持的。
