### ISSUE TITLE
最新版Android网易云音乐无法使用

### ISSUE THREAD

**Issue by ewjy** [uku/Unblock-Youku#744]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: DNS服务

请具体描述您遇到的问题（例如有问题的视频网址）：昨天更新到最新版的网易云音乐（V3.8.1.169998）之后，被限制地区。但手机Chrome访问ipservice.163.com/isFromMainland所返回的结果为true，电脑上目前也可以正常使用网易云音乐（Windows 10 UWP版）。

您所处的国家或地区：香港

**Comment by yanggis** [comment]
最新版已经加入了反制dns解锁的模块，所以dns解锁不了了，以后dns解锁对网易云音乐客户端都没戏了，要解锁就root手机安装Chinatunnel。

**Comment by ewjy** [comment]
了解了，谢谢您告知。不过目前手机还在保修期内，暂时不打算root，希望未来有免root走tunnel的方法。

**Comment by ewjy** [comment]
@yanggis 请问一下，pac解锁法和DNS的原理一致吗？请问现在pac对新版有没有效？

**Comment by yanggis** [comment]
pac方法一直都无法解锁网易云音乐。

**Comment by ewjy** [comment]
好吧，谢谢告知。看到不止一个商业公司冒充Unblock Youku，感到悲哀，作者加油。

**Comment by yanggis** [comment]
一直被模仿，但从未被超越

**Comment by brlala** [comment]
@yanggis 给iOS的有没有像Chinnatunnel的? 我改了hosts, ipservice.163.com 显示true可是网易云还是不能用，应该是有反制DNS的。我用流量听歌所以改DNS(只能改WIFI的)没有用啊

**Comment by yanggis** [comment]
@brlala 暂时没有哦，抱歉。

**Comment by brlala** [comment]
@yanggis 谢谢告知。下载了旧的版本的网易云就能用hosts。3.7.4的版本没有反制DNS
