### ISSUE TITLE
用unblock youku dns有没有可能解开新版mac迅雷的地区限制。。

### ISSUE THREAD

**Issue by sanen2** [uku/Unblock-Youku#749]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: dns

请具体描述您遇到的问题（例如有问题的视频网址）：迅雷

您所处的国家或地区：美国

网易云之前是在/etc/resolver下创建了一个music.163.com 的文件nameserver 45.32.72.192
现在mac迅雷也限制地区了.不知道这种方法能不能解开迅雷的限制。。

**Comment by yanggis** [comment]
这个应该可以，但是手边没有MAC电脑，没法测试到底是哪个link，如果你能确定是哪个link，可以发给我，我加到服务器列表里。

**Comment by sanen2** [comment]
问题就是我不确定是哪个link.

**Comment by WangQiru** [comment]
说的是mac迅雷3.0.3里那个精选tab里的视频么？用switchhost直接改一下对应视频网站的host就行了。
@sanen2 

<img width="565" alt="screen shot 2017-02-04 at 17 47 45" src="https://cloud.githubusercontent.com/assets/5896343/22620370/61b3412e-eb02-11e6-8f3d-de055d381891.png">

**Comment by summersky92** [comment]
貌似是政策问题， 知乎的相关讨论见https://www.zhihu.com/question/49727074

身处坡县毫无问题  还可以会员离线加速以及高级通道

**Comment by sanen2** [comment]
说的并不是那个精选tab里的视频。。。
是3.0.3 在国外什么东西都下不了。。。提示所在区域无法下载。 @WangQiru 
<a href="http://www.dumparump.com/view.php?id=2AzKkhb" target="_blank"><img src="http://thumb.dumparump.com/493/2AzKkhb.png" alt="dumpArump.com" border="0"></a>

**Comment by WangQiru** [comment]
从来没遇到过这种情况。
