### ISSUE TITLE
關於bilibili app版問題

### ISSUE THREAD

**Issue by maple3142** [uku/Unblock-Youku#750]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: android wifi+pac proxy

请具体描述您遇到的问题（例如有问题的视频网址）：在使用bilibili app時出現地區版權限制(番劇)
http://ipservice.163.com/isFromMainland
在這邊的回應是true

您所处的国家或地区：台灣

**Comment by yanggis** [comment]
你应该是刚更新的最新版的B站客户端吧？

**Comment by maple3142** [comment]
4.32.0版

**Comment by yanggis** [comment]
@Tommy 帮看一下pac的问题吧

**Comment by tommyzhaozbh** [comment]
我一会儿试试看

**Comment by tommyzhaozbh** [comment]
drony+bilibili 4.34.0 没有发现异常

**Comment by yoyo178134** [comment]
最新版 用drony異常 鎖版權 台灣

**Comment by maple3142** [comment]
手機使用pac proxy再次出現異常於bilibili

電腦使用chrome正常運作

**Comment by yanggis** [comment]
pac服务器被攻击了
