### ISSUE TITLE
Hi 你好

### ISSUE THREAD

**Issue by lvp8906** [uku/Unblock-Youku#753]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

请具体描述您遇到的问题（例如有问题的视频网址）：

您所处的国家或地区：

**Comment by lvp8906** [comment]
Hi 你好 
这个星期乐视又看不了，我已经试过重装过软件，麻烦你们看看 谢谢
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome
请具体描述您遇到的问题（例如有问题的视频网址）：
乐视显示该内容不支持当前地区观看
您所处的国家或地区：
美国

**Comment by mc16888** [comment]
現在應該可以了, 請更新去 3.5.3
