### ISSUE TITLE
芒果TV 歌手版 android 看不了

### ISSUE THREAD

**Issue by honjacky** [uku/Unblock-Youku#755]
芒果TV 歌手版 android 看不了

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:PAC/DNS

请具体描述您遇到的问题（例如有问题的视频网址）：沒有

您所处的国家或地区：香港

**Comment by honjacky** [comment]
解決了, 謝謝 admin

**Comment by mc16888** [comment]
上面說的芒果TV是盒子版
http://app.shafa.com/apk/mangguotv.html

點播需要代理的是這一個domain
ott.liveapi.mgtv.com

直播的話我用android emulator一直報錯,直接用VLC去播wireshark抓的直播link就沒問題,不知道是emulator的問題還是app的問題.

因為是盒子用的, 加去DNS/Chinatunnel 比較合適, 我就不提Pull Request了.

@yanggis 有時間請加去 DNS/Chinatunnel, 謝謝.

**Comment by yanggis** [comment]
好的，有时间我加一下，这两天在出差。

**Comment by yanggis** [comment]
您好，我已经把ott.liveapi.mgtv.com添加到whitelist了。

**Comment by mc16888** [comment]
多謝 !
