### ISSUE TITLE
iPad网页版看爱奇艺，用PAC/DNS的方式无法观看

### ISSUE THREAD

**Issue by guodaqian** [uku/Unblock-Youku#756]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

使用PAC/DNS，无法用iPad网页版看爱奇艺，浏览器是iPad版Safari
症状：成功绕过地区限制，但网页视频加载无限菊花

以下方式可以正常观看爱奇艺：
1) PC上使用Chrome浏览器 + Chrome插件
2) 安卓手机使用爱奇艺app + PAC/DNS

请具体描述您遇到的问题（例如有问题的视频网址）
1) 在iPad上配置好PAC或DNS
2) 使用iPad版Safari访问 http://www.iqiyi.com/v_19rrlpgmt0.html

您所处的国家或地区：加拿大

希望能解决这个问题，非常感谢！

**Comment by guodaqian** [comment]
自己更新一下：

无限菊花卡住是因为video标签会卡在广告上，而这个广告的url是无效的：http://meta.video.qiyi.com/20160804/6b/07/c20e4caa9ac84ee6a71c033b1a99e72c.m3u8

而http://cache.m.iqiyi.com/jp/tmts/*
这个api返回的值是一个无效的值:

> try{QP.__callbacks__.cb84rmt3({"timestamp":"20160811144502","data":{"playInfo":{"startTime":-1,"shortTitle":"广告宣传片","vu":"http:\/\/www.iqiyi.com\/v_19rrlltp38.html","coa":1,"keyword":"","sid":0,"es":1,"uid":"","plg":90,"an":"广告宣传片","vid":"12078ce069daab217b2632248272d722","pd":1,"apic":"http:\/\/pic3.qiyipic.com\/image\/20160615\/a3\/17\/v_110536086_m_601.jpg","s":"","tvid":496130600,"info":"","ty":0,"endTime":-1,"au":"http:\/\/www.iqiyi.com\/v_19rrlltp38.html","c":20,"ipLimit":0,"qtId":0,"commentAllowed":1,"bossStatus":0,"aid":496130600,"nvid":0,"vn":"广告宣传片","subt":"","vpic":"http:\/\/pic3.qiyipic.com\/image\/20160615\/a3\/17\/v_110536086_m_601.jpg"},"vidl":[{"vd":1,"vid":"43f62760005998a7e1c4beae2df30506"},{"vd":2,"vid":"04a698129c0c7b622eb15f448780c6ea"}],"adDuration":0,"clientIp":"202.108.14.240","ugc":0,"vd":2,"vid":"12078ce069daab217b2632248272d722","previewType":"","m3utx":"","tail":0,"cid":20,"tipType":"","m3u":"http:\/\/60.210.17.241\/videos\/other\/20160811\/87\/7a\/52990d1c3b72ab7191e39934ff67c3d9.mp4?key=0f348cd8944b99660c02b3c13fbe8e8ad&src=iqiyi.com&uuid=ca6c0ef0-57ac2095-7a","ad":1,"ds":"A00012","head":0,"prv":"","duration":90},"ctl":{"area":1},"code":"A00000"});}catch(e){};

里面包含一个错误视频：
http://60.210.17.241/videos/other/20160811/87/7a/52990d1c3b72ab7191e39934ff67c3d9.mp4?key=0f348cd8944b99660c02b3c13fbe8e8ad&src=iqiyi.com&uuid=ca6c0ef0-57ac2095-7a
![image](https://cloud.githubusercontent.com/assets/1021261/23097704/424e1ec0-f611-11e6-9066-f8e9a7fa143f.png)

不知道为什么DNS服务器对安卓app是有效的，但是对浏览器里的网页版就失效了？

**Comment by guodaqian** [comment]
又查了一下，应该还是DNS服务器在处理http://cache.m.iqiyi.com/jp/tmts/* 这个接口的时候有问题。
比如这个请求：
> http://cache.m.iqiyi.com/jp/tmts/472978200/ca97e2f29158ec4fae1b32655015d1fd/?uid=2493079404&cupid=qc_100001_100103&src=03020031010000000000&platForm=h5&qdv=1&qdx=n&qdy=x&qds=0&__jsT=sgve&t=1487516131067&type=m3u8&qypid=472978200_03030021010000000000&callback=QP.__callbacks__.cbnezo1k&vf=928e391662cc2151fd706ae8e3831c51

我试了让这个url走普通的中国代理服务器，得到的是有效的结果。里面包含正常的m3u8地址。视频也可以正常播放。
但是用DNS服务器的方式，返回结果就是一个无效的视频。参考2L。

而158.69.209.100 DNS解析cache.m.iqiyi.com的结果是：

> PS C:\Users\> nslookup cache.m.iqiyi.com 158.69.209.100
Server:  100.ip-158-69-209.net
Address:  158.69.209.100
Name:    cache.m.iqiyi.com
Addresses:  45.63.69.42
          158.69.209.100
          45.32.72.192

因此怀疑158.69.209.100 DNS确实试图处理cache.m.iqiyi.com的url请求，但返回结果有问题？
这个问题在安卓app上并没有体现出来，只是在网页版里出现了。

**Comment by benhong** [comment]
ios 系列使用pac 不能看愛奇藝 應該有一陣子了
後來發現到 ios 再看愛奇藝的時候 某些網頁是不會走http 代理伺服器的
最後我解決的方法就是 vpn 推送route table 到VPN server 
vpn server 再使用iptable 將資料導到中國大陸的proxy server

vpn server 和proxy server 是不同台，並且vpn server 不在大陸
原因當你在proxy server 架vpn server 速度會慢到受不了

若有需要我可以提供VPN 給你玩玩看

**Comment by guodaqian** [comment]
谢谢回复！我这边是用iOS Safari看网页版爱奇艺。使用普通的中国大陆代理做全局proxy后是可以看的。只是用158.69.209.100这个DNS不行。

**Comment by guodaqian** [comment]
我现在确信是http://cache.m.iqiyi.com/jp/tmts/*
这个url的问题了。

@yanggis 请问有空的话可以麻烦看一下这个问题么？谢谢:)。

比如这个url：
> http://cache.m.iqiyi.com/jp/tmts/472978200/ca97e2f29158ec4fae1b32655015d1fd/?uid=2493079404&cupid=qc_100001_100103&src=03020031010000000000&platForm=h5&qdv=1&qdx=n&qdy=x&qds=0&__jsT=sgve&t=1487516131067&type=m3u8&qypid=472978200_03030021010000000000&callback=QP.__callbacks__.cbnezo1k&vf=928e391662cc2151fd706ae8e3831c51

在不使用任何修改的情况下，默认网络的返回结果是：
> try{QP.__callbacks__.cbnezo1k({"timestamp":"20170220232347","st":502,"ctl":{"area":301},"ip":"70.54.49.178","code":"A00111"});}catch(e){};

其中A00111就是爱奇艺地区限制的错误代码。

使用158.69.209.100 DNS后得到的是一个无效的结果：
> try{QP.__callbacks__.cbnezo1k({"timestamp":"20160811144502","data":{"playInfo":{"startTime":-1,"shortTitle":"广告宣传片","vu":"http:\/\/www.iqiyi.com\/v_19rrlltp38.html","coa":1,"keyword":"","sid":0,"es":1,"uid":"","plg":90,"an":"广告宣传片","vid":"12078ce069daab217b2632248272d722","pd":1,"apic":"http:\/\/pic3.qiyipic.com\/image\/20160615\/a3\/17\/v_110536086_m_601.jpg","s":"","tvid":496130600,"info":"","ty":0,"endTime":-1,"au":"http:\/\/www.iqiyi.com\/v_19rrlltp38.html","c":20,"ipLimit":0,"qtId":0,"commentAllowed":1,"bossStatus":0,"aid":496130600,"nvid":0,"vn":"广告宣传片","subt":"","vpic":"http:\/\/pic3.qiyipic.com\/image\/20160615\/a3\/17\/v_110536086_m_601.jpg"},"vidl":[{"vd":1,"vid":"43f62760005998a7e1c4beae2df30506"},{"vd":2,"vid":"04a698129c0c7b622eb15f448780c6ea"}],"adDuration":0,"clientIp":"202.108.14.240","ugc":0,"vd":2,"vid":"12078ce069daab217b2632248272d722","previewType":"","m3utx":"","tail":0,"cid":20,"tipType":"","m3u":"http:\/\/60.210.17.241\/videos\/other\/20160811\/87\/7a\/52990d1c3b72ab7191e39934ff67c3d9.mp4?key=0f348cd8944b99660c02b3c13fbe8e8ad&src=iqiyi.com&uuid=ca6c0ef0-57ac2095-7a","ad":1,"ds":"A00012","head":0,"prv":"","duration":90},"ctl":{"area":1},"code":"A00000"});}catch(e){};

**使用普通中国大陆proxy的返回是有效结果**：
> try{QP.__callbacks__.cbnezo1k({"timestamp":"20170220232924","data":{"vidl":[{"m3utx":"http:\/\/cache.m.iqiyi.com\/mus\/text\/203687301\/e04fe88af8dbd77c6721bc4cb99df459\/afbe8fd3d73448c9\/2493079404\/20161103\/e1\/0e\/208fb53e638e66fd08b30d2c213464ee.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=b296ef177ee1c0a790593ead9ef67cd1&qypid=472978200_03030021010000000000_21&qd_k=928e391662cc2151fd706ae8e3831c51&other=","vd":21,"vid":"e04fe88af8dbd77c6721bc4cb99df459","m3u":"http:\/\/cache.m.iqiyi.com\/mus\/203687301\/e04fe88af8dbd77c6721bc4cb99df459\/afbe8fd3d73448c9\/2493079404\/20161103\/e1\/0e\/208fb53e638e66fd08b30d2c213464ee.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=b296ef177ee1c0a790593ead9ef67cd1&qypid=472978200_03030021010000000000_21&qd_k=928e391662cc2151fd706ae8e3831c51&other=","fileFormat":"H265"},{"vd":1,"vid":"dcc3b7c8d3644b6614cc361e58d6541e","m3utx":"http:\/\/cache.m.iqiyi.com\/mus\/text\/203687301\/dcc3b7c8d3644b6614cc361e58d6541e\/afbe8fd3d73448c9\/2493079404\/20160429\/99\/aa\/f9fcc326fcf30233e98e902a3b797c98.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=218eb60083ad536b55c550bfb166a051&qypid=472978200_03030021010000000000_1&qd_k=928e391662cc2151fd706ae8e3831c51&other=","m3u":"http:\/\/cache.m.iqiyi.com\/mus\/203687301\/dcc3b7c8d3644b6614cc361e58d6541e\/afbe8fd3d73448c9\/2493079404\/20160429\/99\/aa\/f9fcc326fcf30233e98e902a3b797c98.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=218eb60083ad536b55c550bfb166a051&qypid=472978200_03030021010000000000_1&qd_k=928e391662cc2151fd706ae8e3831c51&other="},{"vd":2,"vid":"ca97e2f29158ec4fae1b32655015d1fd","m3utx":"http:\/\/cache.m.iqiyi.com\/mus\/text\/203687301\/ca97e2f29158ec4fae1b32655015d1fd\/afbe8fd3d73448c9\/2493079404\/20160429\/f9\/48\/8b147dae05e51160202ce209cd9db595.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=a274ee8c3bc411e1c3d498419b2e86cd&qypid=472978200_03030021010000000000_2&qd_k=928e391662cc2151fd706ae8e3831c51&other=","m3u":"http:\/\/cache.m.iqiyi.com\/mus\/203687301\/ca97e2f29158ec4fae1b32655015d1fd\/afbe8fd3d73448c9\/2493079404\/20160429\/f9\/48\/8b147dae05e51160202ce209cd9db595.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=a274ee8c3bc411e1c3d498419b2e86cd&qypid=472978200_03030021010000000000_2&qd_k=928e391662cc2151fd706ae8e3831c51&other="},{"vd":96,"vid":"2b51b95a16029c98cea318e33ecaaf0d","m3utx":"http:\/\/cache.m.iqiyi.com\/mus\/text\/203687301\/2b51b95a16029c98cea318e33ecaaf0d\/afbe8fd3d73448c9\/2493079404\/20160429\/0b\/b6\/2d804d2dc80f75e20fb1217f2ed69008.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=5f50107acb30d8c79f23b2467113dc15&qypid=472978200_03030021010000000000_96&qd_k=928e391662cc2151fd706ae8e3831c51&other=","m3u":"http:\/\/cache.m.iqiyi.com\/mus\/203687301\/2b51b95a16029c98cea318e33ecaaf0d\/afbe8fd3d73448c9\/2493079404\/20160429\/0b\/b6\/2d804d2dc80f75e20fb1217f2ed69008.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=5f50107acb30d8c79f23b2467113dc15&qypid=472978200_03030021010000000000_96&qd_k=928e391662cc2151fd706ae8e3831c51&other="}],"pano":{"rType":0,"type":1},"adDuration":0,"aid":203687301,"head":62,"vipInfo":{"msg":"不是会员","unfeeze_times":0,"status":"Q00305","vip":false,"keepalive":0,"text":""},"ugc":0,"clientIp":"125.88.74.122","vd":2,"rTime":"","ds":"A00012","prv":"","previewType":"","duration":2580,"tail":2523,"um":0,"cid":2,"tipType":"","m3u":"http:\/\/cache.m.iqiyi.com\/mus\/203687301\/ca97e2f29158ec4fae1b32655015d1fd\/afbe8fd3d73448c9\/2493079404\/20160429\/f9\/48\/8b147dae05e51160202ce209cd9db595.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=a274ee8c3bc411e1c3d498419b2e86cd&qypid=472978200_03030021010000000000_2&qd_k=928e391662cc2151fd706ae8e3831c51&other=","ad":1,"bossStatus":0,"tvid":472978200,"vid":"ca97e2f29158ec4fae1b32655015d1fd","m3utx":"http:\/\/cache.m.iqiyi.com\/mus\/text\/203687301\/ca97e2f29158ec4fae1b32655015d1fd\/afbe8fd3d73448c9\/2493079404\/20160429\/f9\/48\/8b147dae05e51160202ce209cd9db595.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=472978200&bossStatus=0&qd_vip=0&px=f4UustlUYNGyStVuSZa0jT3fHchbGP1pYhDm2qrm30eNf1RtUW51gARBFwwsLfjm3rObeda&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1487604564330&qd_sc=a274ee8c3bc411e1c3d498419b2e86cd&qypid=472978200_03030021010000000000_2&qd_k=928e391662cc2151fd706ae8e3831c51&other="},"ctl":{"area":5},"code":"A00000"});}catch(e){};

**Comment by yanggis** [comment]
好的，我一会把这个链接加进去，这几天在出差，不太方便修改DNS服务器。

**Comment by yanggis** [comment]
刚才检查了一下cache.m.iqiyi.com这个已经在DNS拦截的list里面了，现在唯一能解释的就是爱奇艺把我们的对我们代理服务器发出的cache.m.iqiyi.com的请求进行了特殊处理，不返回正确的结果。

**Comment by guodaqian** [comment]
是的，应该确实是他们特殊处理了，因为我用其他通用的代理是正常的。
看来也不容易解决。那我先把这个issue关掉了。安卓app都还是正常的。谢谢！
