### ISSUE TITLE
想要一份DNS的域名列表

### ISSUE THREAD

**Issue by Love4Taylor** [uku/Unblock-Youku#758]
自己有dnsmasq服务 但是因为某些原因不想直接修改全局上游DNS 所以想指定这些域名用unblock的DNS

**Comment by yanggis** [comment]
基本是在这个link上修改的，以适应不同的DNS软件，
https://github.com/dlei/Unblock-Youku/blob/b8c1fa1974d6931e0d8ac4a43bb71f89c77b65f2/shared/urls.js

**Comment by Love4Taylor** [comment]
@yanggis 好气啊 虽然这么设置了 但是 iqiyi android 提示 104,A00001 腾讯视频提示 无法连接网络 -840 芒果tv 无限加载 搜狐能加载视频 但是视频信息及评论区提示网络连接错误
所以还是想求一份配置

> #163Music
server=/ipservice.163.com/158.69.209.100
server=/so.open.163.com/158.69.209.100
server=/music.126.net/158.69.209.100
server=/music.163.com/158.69.209.100
#Tencent
server=/qq.com/158.69.209.100
#HunanTV MGTV
server=/hunantv.com/158.69.209.100
server=/mgtv.com/158.69.209.100
#LeTV
server=/letv.cn/158.69.209.100
server=/letv.com/158.69.209.100
server=/le.com/158.69.209.100
server=/lecloud.com/158.69.209.100
#Youku Tudou
server=/youku.com/158.69.209.100
server=/soku.com/158.69.209.100
server=/tudou.com/158.69.209.100
#Sohu
server=/sohu.com/158.69.209.100
#iQiyi
server=/qiyi.com/158.69.209.100
server=/iqiyi.com/158.69.209.100
#PPTV
server=/pptv.com/158.69.209.100
server=/pplive.cn/158.69.209.100
#CNTV
server=/cntv.cn/158.69.209.100
#DoubanFM
server=/douban.fm/158.69.209.100
#Kuwo
server=/kuwo.cn/158.69.209.100
#Kugou
server=/kugou.com/158.69.209.100

**Comment by yanggis** [comment]
iqiyi和芒果TV需要你自己抓包，你要想定制自己的dns列表，需要你自己抓包去找这些link,
我们不负责帮用户维护dns列表。
