### ISSUE TITLE
为什么 https 的 b 站 看授权番这么卡？

### ISSUE THREAD

**Issue by ngkeanhowe** [uku/Unblock-Youku#759]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

请具体描述您遇到的问题（例如有问题的视频网址）： https://www.bilibili.com 看授权番的网页很卡！

您所处的国家或地区：马来西亚

**Comment by zhuzhuor** [comment]
https 本身就很慢，如果能用 http 就用 http 吧，多谢
