### ISSUE TITLE
优酷火影, 柯南等"剧集列表"不能载入

### ISSUE THREAD

**Issue by aifreedom** [uku/Unblock-Youku#760]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome 插件

请具体描述您遇到的问题（例如有问题的视频网址）：
1. 使用标准模式的Unblock Youku Chrome插件, 打开[柯南](http://list.youku.com/show/id_zcc003400962411de83b1.html)或者[火影忍者](http://list.youku.com/show/id_zcc001f06962411de83b1.html)的列表页. 最近一组的剧集列表正常载入:
![image](https://cloud.githubusercontent.com/assets/70373/23585717/49cd96e2-013a-11e7-8baf-686f4d03acf3.png)

2. 选择其他一组剧集列表, 比如上图中的"701-710". Loading动画后, 剧集链接载入失败
![image](https://cloud.githubusercontent.com/assets/70373/23585725/82a0cb42-013a-11e7-9b26-646b97922cdc.png)

3. 粗略分析是请求 "http://list.youku.com/show/episode" 时没有返回结果. 猜想用全局大陆VPN访问可以得到结果. 

4. 在视频播放页, 比如[这里](http://v.youku.com/v_show/id_XMTkzMTA0NjgyMA==.html)右边的选集功能也有类似问题. 但失败的请求似乎不是发往同一个endpoint.

您所处的国家或地区：
美国

**Comment by zhuzhuor** [comment]
@aifreedom 多谢你的详细反馈！ @mc16888 的关于这个的 pull request 已经 merge 进来了，我这就上传到 Chrome Web Store，之后请再试试！

**Comment by zhuzhuor** [comment]
我手动试了下，已经 OK 了
有问题欢迎再来反馈或者 reopen issue

**Comment by aifreedom** [comment]
👍 确认已修复

**Comment by zhuzhuor** [comment]
@aifreedom 多谢反馈！
