### ISSUE TITLE
開啟後無法訪問google，關閉後也不行

### ISSUE THREAD

**Issue by rainsweet** [uku/Unblock-Youku#762]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

请具体描述您遇到的问题（例如有问题的视频网址）：
開啟標準模式後無法訪問google，選擇關閉模式也無法訪問google

您所处的国家或地区：

**Comment by zhuzhuor** [comment]
我们的 Unblock Youku 服务不对 Google 做任何处理，请你检查自己的网络设置
