### ISSUE TITLE
用 DNS B站 https 全挂

### ISSUE THREAD

**Issue by Love4Taylor** [uku/Unblock-Youku#763]
DNS 服务提供的 https 代理 时不时挂掉

http://www.17ce.com/site/http/201703_76c95ead3c123ff111b08ae7534e7e56.html
http://www.17ce.com/site/http/201703_3bdb11fecce2576a984c256599c66634.html
http://www.17ce.com/site/http/201703_ee60a72e8c4565b23133bf6c8954d4ce.html

**Comment by yanggis** [comment]
17CE的检查和我们的DNS解锁有什么关系啊？

**Comment by Love4Taylor** [comment]
@yanggis 用你们的 DNS 解析出来的是3个 DNS 的 IP, 我在 17ce 上指定了 host 三个分别是你们3个 DNS 的 IP, 真的没关系？
![](http://ww4.sinaimg.cn/large/0060lm7Tgy1fdla7dba6jj30fw0b2wev.jpg)
![](http://ww4.sinaimg.cn/large/0060lm7Tgy1fdla7tl44rj30pj0gn3yw.jpg)

**Comment by yanggis** [comment]
@Love4Taylor 你为什么要在17ce 上指定我们的DNS的IP？我们的DNS仅仅是提供个人使用的，17ce你这种商业公司制定我们的IP得到我们的授权了吗？

**Comment by Love4Taylor** [comment]
@yanggis 你到底是语文不好还是根本没用过17ce ？用 17ce 测试网址 做 get 请求的时候 高级选项内可以自己自定义服务器的 IP  而不靠解析
还 个人使用 还 商业公司 还授权 麻烦 读明白了

**Comment by yanggis** [comment]
@Love4Taylor 嗯，你还挺有理啊，从现在开始关闭所有关于bilibili的https解析！

**Comment by Love4Taylor** [comment]
@yanggis 你随意 自己服务出问题不去看 反倒还怪用户用测试工具去测试 很服气

**Comment by yanggis** [comment]
@Love4Taylor 我已经随意了。

**Comment by yanggis** [comment]
@嫌服务有问题就不要用，别一边用着我们的DNS服务，一般还说着吃里扒外的话。

**Comment by Love4Taylor** [comment]
@yanggis 那我上面的截图都是假的？ time out是假的？来来来 说说我怎么吃里扒外了 反馈问题就吃里扒外了？

**Comment by yanggis** [comment]
@Love4Taylor 就是真的又能怎么样？你用的我们的服务器的时候我给你承诺我的服务器永远没有问题了？

**Comment by yanggis** [comment]
@Love4Taylor 现在我把所有B站的解析服务全关了，你用17CE解析全是time out了，你又能怎么样？

**Comment by Love4Taylor** [comment]
@yanggis 所以我才来反馈 让你去看 照你这么说用户就该一声不坑？

我无所谓 我在国内 谢谢

**Comment by yanggis** [comment]
@Love4Taylor 
这是你吧？
http://space.bilibili.com/2240781/#!/
怪不得B站一解析不了你就紧张的打哆嗦。

**Comment by Love4Taylor** [comment]
@yanggis 我打哆嗦？笑死了 我还是个B黑呢 你知道么

**Comment by yanggis** [comment]
@Love4Taylor 我不需要知道，我只是知道我想让你用我们的DNS解析服务你就可以用的了，我想不让你用，你就用不了。

**Comment by LBYPatrick** [comment]
你们这个直接影响到了正常用户的使用啊...

**Comment by yanggis** [comment]
@LBYPatrick 没谁强迫你用，你要觉得等不及就去用其他的解锁方法。解决问题需要时间的。

**Comment by LBYPatrick** [comment]
@yanggis 有时候你确实是得反省反省了。大部分情况下你都是看别人的东西看一半就马上下结论，我指的影响正常使用是你因为和他吵架一气之下把b站解析直接关掉这事儿。你确实舒服了，他也没话说了，但是剩下的用户呢? 重点问题还真不是影响了其他用户，而是你真的太冲了。

**Comment by yanggis** [comment]
@LBYPatrick, 我关了他的DNS解析服务影响你使用了吗？如果有请指出来，或者你知道影响谁了，请指出来，如果没有请不要在这瞎啰嗦。
