### ISSUE TITLE
跑题：求 Firefox 插件 ❤️

### ISSUE THREAD

**Issue by guoyunhe** [uku/Unblock-Youku#765]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Firefox 插件。 https://addons.mozilla.org/en-US/firefox/addon/unblock-youku/

请具体描述您遇到的问题（例如有问题的视频网址）：
那个 Firefox 的插件用不了，一年前开始就没有更新了。希望官方出一个 Firefox 版吧，毕竟也是主流浏览器。

您所处的国家或地区：
芬兰

**Comment by gloomy-ghost** [comment]
Depends on: https://bugzilla.mozilla.org/show_bug.cgi?id=1283639

**Comment by wtjfree** [comment]
根据我的经验.firefox对unlock youku 免疫. 我用ss的时候firefox也免疫视频代理.建议谷歌或者ie浏览器.

**Comment by infinitysky** [comment]
兼容起来比较麻烦。
你可以参照 这个 文档 设置代理
[https://bbs.uku.im/t/ios-android-firefox-unblock-youku/27](url)


[https://dpicw87f8m7nl.cloudfront.net/original/1X/b25c3b937272a12f5ad804288e27721b8d727304.png](url)

**Comment by gloomy-ghost** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/unblock-youku/ 在 @whuhacker 手上，方便的话合作一下？
