### ISSUE TITLE
能提供iOS酷狗的hosts网址？

### ISSUE THREAD

**Issue by brlala** [uku/Unblock-Youku#769]
http://www.huarenjie.com/thread-7529755-1-1.html
这网址说unblock youku能解决酷狗版权的问题。因为我比较常用流量，只能通过更改hosts来越墙。
我用iOS的。
好比网易云用这个：
158.69.209.100 music.163.com

有没有酷狗，QQ版本的hosts网址?感谢万分

**Comment by tommyzhaozbh** [comment]
把上面的163地址换成下面这两个
ip2.kugou.com
ip.kugou.com
QQ音乐的是基于IP地址验证，改hosts不起作用，建议付费

**Comment by brlala** [comment]
@tommyzhaozbh 谢谢您！成功播放了
