### ISSUE TITLE
在优酷搜电影，结果全部跳转到预告片，而不是正片

### ISSUE THREAD

**Issue by rinick** [uku/Unblock-Youku#770]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome插件

  请具体描述您遇到的问题（例如有问题的视频网址）：
在优酷搜电影，本来应该是正片的，但是国外点开基本都直接跳转到预告片
http://list.youku.com/category/show/c_96_a_%E7%BE%8E%E5%9B%BD_r_2016_u_1_pt_1_s_1_d_2.html?spm=a2h1n.8251845.filterPanel.5!4~1~3!3~A

  您所处的国家或地区：
美国

**Comment by rinick** [comment]
优酷自动判断所在区域是国外，所以屏蔽电影正片的链接，直接跳转到预告片链接。这难道不是针对unblock youku的新措施吗？ 之前就是显示所在区域不能播放，但是unblock youku还能放。现在干脆不给你跳转到那个链接了。

**Comment by zhuzhuor** [comment]
原来如此。我把youku的分类列表也加到代理列表里了，之后看看效果

**Comment by mc16888** [comment]
正片不是可以在右边的列表里面选吗 ？我用自己的没更新服务器试
![youku](https://user-images.githubusercontent.com/6530873/26999582-e8b31bc4-4dcf-11e7-8e3f-625943bf4b69.jpg)
