### ISSUE TITLE
b站客户端告吹

### ISSUE THREAD

**Issue by LBYPatrick** [uku/Unblock-Youku#771]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: DNS

请具体描述您遇到的问题（例如有问题的视频网址）：app.bilibili.com

您所处的国家或地区：美国东部

使用的系统: Ubuntu （架设SS，DNS采用158.69.209.100），IOS，Android

iPad Air 2 (IOS 10.3) 以及 Android 7.1.1 的Nexus 5X 通过我的Ubuntu云主机 架设的SS （DNS为unblock youku dns，所以连接SS相当于解锁国内网站）打开b站发现所有的东西都加载不出来，其中：
        Android：可以加载视频列表，但是点开视频之后就直接是加载失败
        IOS：整个客户端都无法连接

接下来分别使用这两台设备通过家里Wi-Fi裸连，仅更改DNS为45.32.72.192, 结果同上。

但是，这两种方式依然能正常解锁网页端和其他国内网站

B站单方面动手了？

**Comment by LBYPatrick** [comment]
顺带一提：一天前还是正常的，云主机在Linode的Freemont,CA 机房里。

**Comment by yanggis** [comment]
在检查问题，耐心等待……

**Comment by LBYPatrick** [comment]
好的。话说目标服务器是可以ping得通和dig得到地址的, 所以有可能不是DNS的问题而是...

**Comment by o0o0vso0o0** [comment]
那啥。。。我也上不去了，大概是b站封了这个服务器

**Comment by LBYPatrick** [comment]
有进展了么？

**Comment by zhuzhuor** [comment]
@yanggis 辛苦了，你用自己的 pace 来修服务器，不要有压力。 有需要什么新的服务器的话跟我说

@LBYPatrick @o0o0vso0o0 大家稍安勿躁，等 yanggis 有空了再尝试进一步解决吧

**Comment by yanggis** [comment]
@zhuzhuor 现在其他网站都返回正常，只有B站返回不了正确的数据，暂时没检查出来什么问题，这几天超级忙，要交一个research proposal，还没抽出来时间详细检查问题出在什么地方。等后面详细调试以后才知道具体问题。

**Comment by zhuzhuor** [comment]
@yanggis research proposal 要紧，你抓紧时间弄吧，辛苦了！

@LBYPatrick @o0o0vso0o0 感谢你们的理解

**Comment by o0o0vso0o0** [comment]
假设B站是用了更高级的ip追踪方式，比如在客户端记录每个联网ip，其中只要有一个是境外ip，临近时间的ip都被判断为境外使用的dns。虽然并不认为b站值得这么做，不过背后跟b站有协议的动漫商就不一定了

**Comment by vitaminac** [comment]
补充下：
     b站安卓客户端：
           不使用dns可以加载番剧列表 不能下载
           使用dns不能打开番剧列表 可以通过历史记录下载 观看那些视频
           不使用dns看不了也下载不了视频 不会添加在历史纪录
           不使用dns打开番剧详情后  切换回dns可以在线观看（有时能用）
           不使用dns打开番剧详情后点击加入下载列表 在切换回dns下载 会出现视频解析错误

           有些web端能看的 客户端打开不了（应该只是不能从番剧详情那里打开）

    web端:
                打开时间表 番索引等 都会出现 Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP

**Comment by yanggis** [comment]
感谢反馈，你的提示对我们很重要。

**Comment by bgc8080** [comment]
@yanggis  应该是客户端中直接使用httpdns，以绕过常规的dns解析，防止劫持。 https://www.qcloud.com/product/hd

**Comment by yanggis** [comment]
您说这问题不存在，现在B站解锁正常，就是速度稍慢。

**Comment by jackalsin** [comment]
美国加州山景市测试B站解锁失败

**Comment by david082321** [comment]
@jackalsin 
台湾正常解锁番剧
Android，B站客户端，使用DNS
