### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by LBYPatrick** [uku/Unblock-Youku#772]
建议把两个45开头的服务器都迁到linode的佛利蒙机房，连接世界很多网络的效果真的比45.42.72.192的Vultr要好太多了(本人租了45.32.83.222用来折腾，机房友，但是这周就打算关掉)，重点是现在linode降价了，最低的只要5刀(配置是原来10刀的). 本人在美国东部，租那个45.32.83.222完全是为了研究学习(但是也搭了ss用来快捷用unblock youku，结果正如我这几天开的issue一样，GG)。158的听说你们弄了硬件防火墙那就算了...

**Comment by yanggis** [comment]
你懂什么，45的服务器是网友出资捐赠的，他付款让大家免费用的，因为他的每个月付20美元大家才有这两个免费的服务器来用，不知道对人家服务感恩，还说三道四，嫌弃网络差。那你先捐500美元给@zhuzhuor,够两年用的，让他开两台Linode的服务器做DNS解析用，我负责维护。

**Comment by LBYPatrick** [comment]
...因为价格下到和vultr一样了，所以推荐换过去。我倒也没说45那俩服务器网络不好，只是linode那边的太好了...这个大神莫激动...还有，没人缺500美元。

**Comment by yanggis** [comment]
连接世界很多网络的效果真的比45.42.72.192的Vultr要好太多了,这不是你说的吗？

我给你这么回复，是想给你解释，我们这个免费项目，资金有限，只有在资金有限的范围内给他家提供尽可能好的服务，而不是想一些价格高昂，项目组没法承受的不切实际的方案。

我知道你不缺钱，但是真正能像用户@Migflyway免费给我们提供两台服务器用一两年的人却非常少，我们是缺这样的用户。

再就是项目组每个人都有自己正式的工作，做这个只是牺牲的业余时间，你不可能要求大家丢了正式的工作专心做这个东西，毕竟做这个只是兴趣爱好，正式的工作才生活的保障。

**Comment by LBYPatrick** [comment]
...看起来你还是误解我的意思了...

因为**现在**这位网友**每月在Vultr上租这两个服务器花的钱**在Linode上**可以租到规格更高的两个服务器**，简单地说就是可以**加量不加价**，因为**Linode调整了VPS产品的价格**。我也当然知道资金有限，我身上也有学业，我是基于自己的情况来提出了这个**不需要额外的资金**就可以实现的改进。

**Comment by yanggis** [comment]
我没误会你的意思，每个人都有自己喜欢的VPS服务商，你凭什么强求别人把服务器从Vultr迁到Linode去啊？你觉规格高那是你自己的看法，别人未必这么想，如果都像你这么认为，为什么还有那么多客户在用Vultr呢？那我自己还用DO呢，我就觉得Linode只能信用卡付款不安全，坚决不用。
你自己Linode上有VPS，为什么不自己架设自己的DNS自己用，非要纠缠我们迁到Linode上呢？

**Comment by zhuzhuor** [comment]
@LBYPatrick 我们之前其实也用过 Linode，其实抗攻击方面并没有 Vultr 好，Vultr 还有 10GB 的 DDoS 防火墙。另外 Linode 之前还出过好几次数据库泄露的问题，现在并没有比别家例如 DO 或者 Vultr 更有优势
也欢迎继续反馈，也欢迎给我们捐款捐服务器。我们现在其实比较缺国内的服务器，国内的服务器不好找，之前就有人在网上给我们捐了个国内的服务器，我们用了很久
