### ISSUE TITLE
小米盒子腾讯视频app支持

### ISSUE THREAD

**Issue by jason51122** [uku/Unblock-Youku#773]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
DNS
请具体描述您遇到的问题（例如有问题的视频网址）：
小米盒子目前看爱奇艺 芒果TV 优酷这些都没有问题 只有腾讯视频app还显示有地域限制 求问可以增加腾讯的支持吗

您所处的国家或地区：

**Comment by yanggis** [comment]
腾讯云视听仅仅依靠DNS是解锁不了的，芒果TV的最新版靠DNS解锁成功率也不高，这是DNS的缺陷，没办法。你要想解锁云视听只能安装chinatunnel.apk

**Comment by jason51122** [comment]
多谢多谢 我安装试一下

**Comment by yanggis** [comment]
要root盒子

**Comment by gitawego** [comment]
出于好奇，可以提示下是哪些缺陷吗？
