### ISSUE TITLE
DNS异常

### ISSUE THREAD

**Issue by LBYPatrick** [uku/Unblock-Youku#775]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: DNS

请具体描述您遇到的问题（例如有问题的视频网址）：备用节点无法正常工作

您所处的国家或地区：美东宾州费城附近小镇/美西加州fremont

**45.32.72.192**服务器现在拒绝解析，无法正常打开网页，**45.63.69.42**在手机上b站无法解锁。158.69.209.100现在有较为严重的速度问题。
待解决。

**Comment by yanggis** [comment]
我刚才试了45.32.72.192解析没有任何问题。

**Comment by LBYPatrick** [comment]
158现在没有速度问题了，45,32.72.192依然不能工作，具体如下
```
root@ubuntu:~# dig @45.32.72.192 bilibili.com
; <<>> DiG 9.10.3-P4-Ubuntu <<>> @45.32.72.192 bilibili.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
root@ubuntu:~#
```
我做过DNS缓存，今天早上（美国东部时间）发现的问题，比45.32.72.192只多撑了一小会儿，还是被搞下来了。下午5点我用自己写的bind-china-list(已经开源)把中国网站的解析DNS换回了158.69.209.100，然后就可以了。

**Comment by yanggis** [comment]
我们的DNS服务器是面向移动客户端终端设备的，只给终端客户使用。
不提供任何在我们DNS上搭建的DNS缓冲服务器的支持，
另外我们的服务器有并发数限制，超过并发数限制会自动把IP加到黑名单，停止DNS解析服务。

**Comment by LBYPatrick** [comment]
OK. 理解你的意思。

但请注意：
1. 我在服务器做这个是为了免于让我每次都在安卓和IOS设备上反复手动修改DNS的痛苦，所以才放上去，我也没有说过我在其他设备上用过。

2. 我的DNS缓存并没有问题，我向你询问的是45.32.72.192的问题，因为不仅我服务器遇到了这个问题，在我家用真实IP使用45.32.72.192的谷歌亲儿子5X也遇到了这个问题，恐怕不只是黑名单的问题。至于并发数问题, 我不认为我超了并发数，因为我一共也才三台设备，每次只用一台设备，并发数理论上只会有一个普通用户的量，这个希望你可以反复检查一下服务器规则。

3. 我为什么要做DNS缓存：因为我这里连过去158.69.209.100的延迟高达75ms, 本地解析可以加速，而且可以减少对你DNS服务器产生的压力，即使对你的实际效果几乎为零，况且我只在上国内网站的时候会用到你的解析（bind9可以分流，非国内网站自动走8.8.8.8）。

4. 我用了bind9来做dns解析缓存，你并不需要帮bind9的用户提供技术支持。

希望你能理解。

**Comment by yanggis** [comment]
1. 我不关心你在不在乎地方用，我关心的是你发送到DNS服务器的请求有没有违反DNS服务器设计的规则。
2.有没有超过并发数不是你说了算。
3.没人关心你为什么用DNS缓存。
4.既然不想让提供支持就不用告诉我你用的什么软件。
