### ISSUE TITLE
PAC无法正常解锁B站

### ISSUE THREAD

**Issue by TT702** [uku/Unblock-Youku#776]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: PAC

请具体描述您遇到的问题（例如有问题的视频网址）：
1、B站客户端请求了117.25.128.201:443被拒绝。
2、使用iOS B站客户端显示错误信息“该HTTPS链接不可信”

您所处的国家或地区：新西兰

**Comment by LBYPatrick** [comment]
临时先用DNS解决问题吧，PAC不稳定是其性质的锅。
