### ISSUE TITLE
插件无法解锁BiliBili

### ISSUE THREAD

**Issue by renyidong** [uku/Unblock-Youku#777]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome插件
请具体描述您遇到的问题（例如有问题的视频网址）：
BiliBili大部分新番，比如：https://www.bilibili.com/video/av10570681/
您所处的国家或地区：
美国

**Comment by jlwangPoincare** [comment]
姑且帮忙附议一下，目前的确是有问题。

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome插件
请具体描述您遇到的问题（例如有问题的视频网址）：
BiliBili大部分新番，比如：https://www.bilibili.com/video/av10570681/
您所处的国家或地区：
美国

同时，如果在同一台计算机上使用DNS服务器158.69.209.100，关闭Chrome扩展，该视频是可以观看的。

**Comment by zjdavid** [comment]
同在美国，播放同一视频并没有出现问题
![2017-05-21 1 04 25](https://cloud.githubusercontent.com/assets/16710181/26285861/1209e2a0-3e26-11e7-8f32-5e17bc4ca85c.png)
此外其他新番也是可以播放的。
可能是运营商的问题？我这里用的是Xfinity

**Comment by zhuzhuor** [comment]
前两天刚修复了下，如果能用了就好

**Comment by renyidong** [comment]
确认已经修复
