### ISSUE TITLE
问下电视盒子的问题

### ISSUE THREAD

**Issue by wuweixioa** [uku/Unblock-Youku#780]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:  小米盒子，用DNS

请具体描述您遇到的问题（例如有问题的视频网址）：想看盒子自带的国内视频，不过，特别卡。很多情况卡在100kb左右。有时直接动不了。我是校内外，想知道是dns问题，还是说学校网络就是这样。

您所处的国家或地区：澳大利亚， 对了是学校提供的网络。访问youtube或下载steam的东西速度是很快的。有70M/S左右

**Comment by LBYPatrick** [comment]
土澳的回国线路不行...跟我在美国遇到的问题类似...只能通过在日本架个Shadowsocks然后在SS上用DNS，而且效果还不一定好（但是服务器成本的话你可以租给你国内的朋友来摊掉，因为他们用了可以翻墙）

**Comment by yanggis** [comment]
澳洲往中国线路有问题，应该是在澳洲访问中国大陆大多数网站都很慢，看视频本来就堪忧。
