### ISSUE TITLE
Bilibili 番剧不用代理也能看了？

### ISSUE THREAD

**Issue by guoyunhe** [uku/Unblock-Youku#783]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome 插件

请具体描述您遇到的问题（例如有问题的视频网址）：
从七月开始，发现不用启用 Unblock Youku 也能看 Bilibili 番剧了。包括新出的七月番和以前的四月番。不用代理看还更快一些。如果是 Bilibili 解除 IP 限制了的话，是不是就不用代理 Bilibili 了？

您所处的国家或地区：
芬兰

**Comment by CXwudi** [comment]
加拿大测试显示并没有解除IP限制

**Comment by simon300000** [comment]
美国西雅图测试显示并没有解除IP限制

**Comment by gitTaky** [comment]
日本使用unblockyouku并没有用

**Comment by xupefei** [comment]
同在芬兰，不用代理不但能看，还更快了。

**Comment by tigerhuhuhu** [comment]
美国boston测试，不使用代理已经可以观看，而且速度更快

**Comment by erbo055** [comment]
美国休斯顿测试显示并没有解除IP限制

**Comment by czk1997** [comment]
美国宾夕法尼亚匹兹堡Comcast测试显示并没有解除IP限制

**Comment by LBYPatrick** [comment]
坐标美国宾夕法尼亚州华盛顿堡，显示没有解锁限制

Linode 新加坡IP，部分番剧解锁，但new game等都没有解锁

Linode 东京二区，172.104 IP开头, 全部解锁，利用SS连接后发现加载起来比直接用华盛顿堡的Verizon宽带和T-Mobile的LTE还要稳定高速许多

**Comment by guoyunhe** [comment]
貌似仅限芬兰……

**Comment by LBYPatrick** [comment]
还有荷兰和日本部分地区...
