### ISSUE TITLE
网易云音乐网页端异常

### ISSUE THREAD

**Issue by LBYPatrick** [uku/Unblock-Youku#784]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: DNS

请具体描述您遇到的问题（例如有问题的视频网址）：music.163.com

您所处的国家或地区：美国

如图
![image](https://user-images.githubusercontent.com/23201539/28401900-83dcf5cc-6d4f-11e7-984c-eb973f5877d4.png)

**Comment by LBYPatrick** [comment]
需不需要考虑换个服务器？

**Comment by JackalZheng** [comment]
會是跟VPN封鎖事件有關嗎？

我在台灣的測試結果：

http://ipservice.163.com/isFromMainland
.209.100 完全連不上
.72.192 重整5次有兩次連上
.69.42 重整5次有兩次連上

在云音乐里面听歌换歌时，偶会出现

获取播放地址失败

**Comment by LBYPatrick** [comment]
@JackalZheng DNS维护者 @yanggis 说是在加拿大的DNS服务器和在中国的代理服务器通讯不畅，所以这是有可能的

**Comment by erbo055** [comment]
我也有同样的问题，同事bilibili也打不开了。刚刚尝试清理DNS cache以后在一台机器上恢复了，但是在另外一台同样DNS配置的机器上问题依旧，非常迷

**Comment by erbo055** [comment]
我也有同样的问题，同时bilibili也打不开了。刚刚尝试清理DNS cache以后在一台机器上恢复了，但是在另外一台同样DNS配置的机器上问题依旧，非常迷

**Comment by LBYPatrick** [comment]
@erbo055 Unblock Youku的PAC和DNS因为技术限制已经开始靠不住了，最佳方案还是在国内租个服务器搭代理用。我现在就是按照论坛上一位热心网友的提示用上了172 IP开头的Linode日本服务器在正常看b站番剧（但是其他网站都只能靠DNS，那就比较看运气了）

**Comment by erbo055** [comment]
@LBYPatrick  我上个月回国的时候发现在国内也都打不开，卸载插件+清理DNS以后也是时好时坏，现在彻底换了台电脑才算好。现在保险点也只好租服务器搭代理了

**Comment by erbo055** [comment]
比较诡异的是其中一个机器无论怎么修复重置都没用，一直是无法显示。

**Comment by LBYPatrick** [comment]
估计是 @yanggis 最近比较忙，因为他最近在网络上活动很少，之前说修复b站也一直没有搞定。网易云那边肯定是服务器通讯受干扰了，毕竟有[其他人](https://s1.jixun.moe/163/ips.html)弄出来了，要解决也能解决但是要投入大量精力和时间才行，所以应该是他最近太忙了。凑合用吧
