### ISSUE TITLE
能否支持迅雷离线网页版

### ISSUE THREAD

**Issue by lonelykid** [uku/Unblock-Youku#785]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome插件

请具体描述您遇到的问题（例如有问题的视频网址）：
之前只要打开插件，就可以正常访问lixian.xunlei.com，之后就可以正常下载。最近可以打开离线的网页，但是无法正常下载了。
URL列表里有网页版离线的地址lixian.xunlei.com等，但是没有迅雷的load balancer和下载节点地址。
gdl.lixian.vip.xunlei.com
dl.*.lixian.vip.xunlei.com 
vod*.*.lixian.vip.xunlei.com
这里面给出了节点的列表https://github.com/iambus/xunlei-lixian/issues/327  虽然很老，但大体上似乎还是这样的。
请问这个问题可以解决吗？

Update: 弄了个墙内的SS，ERR_EMPTY_RESPONSE，==’，还是不能下

Update: 这个不是IP的问题了，迅雷基本算是关闭了离线这个服务，所以没甚么办法了吧。客户端加代理的话的确是可以，但是太不安全了。
您所处的国家或地区：
US

**Comment by LBYPatrick** [comment]
给你一个小妙招: 下载一个迅雷9（可以用[thunder9-booster](https://github.com/LBYPatrick/thunder9-booster)精简一下会更好），然后登录你的会员帐号，然后在代理设置里设成你的SS(SOCKS 5 127.0.0.1:1080), 下载的时候并不会走你的SS流量，但是依然可以解锁美国地区限制(其实迅雷只封杀了美国的IP,所以其他国家的都可以用来解锁，比如我就是用的日本SS)

坐标 Fort Washington, 宾夕法尼亚州
