### ISSUE TITLE
阿里云上自己搭建服务器 无法使用

### ISSUE THREAD

**Issue by wood2464** [uku/Unblock-Youku#786]
Hello
按照教程在阿里云上自己搭建了服务器
可是无法连接！

curl -x 127.0.0.1:8888 "http://ipservice.163.com/isFromMainland
这个是false..

<img width="561" alt="default" src="https://user-images.githubusercontent.com/30617812/28815786-606d7fc4-7657-11e7-85d8-1a1e9e4c1325.png">

没有收到需要备案的提示.... 和备案有关？？

**Comment by wood2464** [comment]
@zhuzhuor  大神能否帮帮忙？

**Comment by zhuzhuor** [comment]
@wood2464 可能是给你分配的 IP 在 163 的数据库里还算是海外的 IP，你可以找找网上的 IP 库查查

**Comment by wood2464** [comment]
<img width="776" alt="_20170803012842" src="https://user-images.githubusercontent.com/30617812/28913010-60cd9d74-77eb-11e7-86af-00b117ad1620.png">

然而.....确实在国内啊 我选的时候选的国内的服务器

**Comment by mc16888** [comment]
@wood2464  你直接用 curl "http://ipservice.163.com/isFromMainland" 结果是true 还是 false, 如果是true，你squid的设定有问题, 如果是false, 那就是IP的问题。

**Comment by chenpingzhao** [comment]
用的哪里的教程，能不能把链接贴出来看看？

**Comment by wood2464** [comment]
@mc16888  是false 可服务器是国内的 应该不会有问题啊....

**Comment by wood2464** [comment]
@chenpingzhao 
http://www.forece.net/post/4207.htm
https://bbs.uku.im/t/unblock-youku/29
https://github.com/uku/Unblock-Youku/wiki/%E5%9C%A8%E7%BE%8E%E5%9B%A2%E4%BA%91%E6%9E%B6%E8%AE%BE%E8%87%AA%E5%B7%B1%E7%9A%84-Unblock-Youku-%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E5%99%A8

主要看的这三个

**Comment by mc16888** [comment]
@wood2464 false的话，你现在的公网IP 在163 的数据库里算是海外的。 你问阿里云可不可以换一个不在 101.200.0.0 ~ 101.201.255.255 之间的公网IP给你。

**Comment by chenpingzhao** [comment]
非常感谢， @mc16888 请问有没有DNS解决方案的教程？

**Comment by wood2464** [comment]
@mc16888  ....不可以更换ip 看看过几天弄一个美团云试试吧 
谢谢啦

**Comment by G-F-CH** [comment]
是不是阿里云的8888端口没有开？
