### ISSUE TITLE
如何搭建unblock DNS服务器

### ISSUE THREAD

**Issue by axot** [uku/Unblock-Youku#787]
bbs.uku.im 讨论里面说用了Bind9, redsocks, sniproxy，shadowsocks这几个软件，
能不能发下软件的config呢？

**Comment by yanggis** [comment]
现在很多APP已经加入了反制DNS解锁的手段，搭建DNS解锁服务器已经意义不大了。

**Comment by axot** [comment]
恩，不知道是怎么判断的？或者只不过是block几个固定的ip而已呢？

**Comment by LBYPatrick** [comment]
@axot 你倒是可以让bind9实现类似转发的效果。在``/etc/bind/named.conf.options``里面把forwarders设成158.69.209.100，像这样

```
forwarders {
   158.69.209.100;
};
```

然后添加这行来实现给外网使用:
```
allow-query {any;}; 
/*
这代表所有IP的机器都可以用，包括公网，你也可以只设成localhost,这样的话只有机用127.0.0.1作DNS才能用。
*/
```

然后重启服务之后就可以在用户机上把DNS设成你服务器的IP，然后就可以了:

```
systemctl restart bind9
```

**Comment by axot** [comment]
转发可以实现这个功能，我想让域名解析在自己的机器上实现，毕竟用外部的DNS会有安全隐患

**Comment by axot** [comment]
暂时在unbound上转发了腾讯的域名，可以用

forward-zone:
    name: "qq.com."
    forward-addr: 158.69.209.100

**Comment by LBYPatrick** [comment]
@axot Unblock Youku DNS的whitelist应该可以直接从[ChinaTunnel](https://github.com/yanggis/ChinaTunnel)里面拿，然后你在国内租一个服务器，whitelist的网站走127.0.0.1:1080 (Shadowsocks) 代理， 应该就可以了

**Comment by tywtyw2002** [comment]
@yanggis 反制dns？详细说说

**Comment by LBYPatrick-old** [comment]
QQ音乐是基于IP验证，请求不是HTTP的。bilibili和网易云是弄了HTTP DNS，因为HTTP
DNS的服务器IP储存在本地，所以没办法弄。（网易云手软一点，你屏蔽HTTP
DNS的服务器之后勉强能用一下，但这得靠IPTABLES，DNS搞不定IP）


tywtyw2002 <notifications@github.com>于2017年9月10日 周日下午11:18写道：

**Comment by axot** [comment]
`HTTP DNS`是什么意思？local cache dns?

**Comment by tywtyw2002** [comment]
现在`HTTP DNS` 是HTTP还是 HTTPS？

DNS其实已经失效很久了，很早之前网易云音乐IOS版本就搞出了好几个大坑。

**Comment by LBYPatrick** [comment]
@tywtyw2002 music.httpdns.c.163.com这个域名
