### ISSUE TITLE
关于最近情况的一个点子

### ISSUE THREAD

**Issue by LBYPatrick** [uku/Unblock-Youku#788]
首先，这不是个issue.

近期，bilibili出现DNS解锁失效，网易云音乐也出现访问不顺畅，很多人也就因此无法正常解锁。根据@yanggis的信息， DNS解锁不了主要还是因为只能做http代理，那么我就想:

如果能开发出来一个linux上的代理客户端呢?

如果用户用自己的能力通过VPN连接上了自己的linux服务器，那么Unblock Youku在这个linux服务器上就可以随便搞了，甚至可以采用chinaTunnel的tcp+http代理了，b站的问题也就很好解决了（理论上是可以套chinaTunnel那一套东西），甚至Unblock Youku的修改网页元素也不是不可能（也许通过拦下网络流量然后修改即可，全程在本地，用户只需要让机器走这个代理就可以实现这样的过滤，因为CloudMusicGear在windows上就是这么解锁网易云客户端的的）。

以上。

**Comment by yanggis** [comment]
你这点子只能说是太理想化，你知道几万人同时连一个VPN是什么后果吗？

**Comment by yanggis** [comment]
如果让用户自己建VPN，用户计算机技术水平参差不齐，所有的时间都用上都不够帮用户解决问题的。最后搞成功的也没几个。
@zhuzhuor 很早就放出来教程，教大家怎么搭建unblock-youku的代理服务器，真正做成功的极少，更没有人愿意拿出来共享。

**Comment by tommyzhaozbh** [comment]
现在的主要问题是，大家都喜欢用免费的东西，都不愿意自己花钱搭服务器。但流量大了容易引起别人注意，所以才会出现不少网站有意封杀的问题。只要大家都是用同一个代理去连，那必定会引起网站方面的注意，这很难办

**Comment by LBYPatrick** [comment]
@tommyzhaozbh @yanggis  是的，没有人愿意共享，因为本来用Unblock Youku的就是一批不想花钱的人。我指的并不是在国内租个服务器然后搞代理，而是让用户在海外弄服务器，然后通过修改http或者tcp请求中的关键数据（据说bilibili是修改HTTP header) 来解锁，前提是用户能把自己所有的流量导到这个服务器上。这个处理所用到的服务器要让用户自己搭，你们要做的是开发这样一个服务器端软件给用户去折腾。留言只看上半句不看下半句，可以这很yanggis

**Comment by yanggis** [comment]
@LBYPatrick 说话这么酸就没意思了，你们讨论吧。

**Comment by tommyzhaozbh** [comment]
用户自己搭服务器这事情本身就各种不愿意的，现在我们也有教程教他们自己搭服务器。但问题是，有多少人愿意自己花钱折腾这个呢?所有人都喜欢用免费的。叫他们在海外弄个服务器，他们不也是不愿意?

**Comment by wtjfree** [comment]
服务器是一方面。unlock youku效能面对国内花样繁多的验证，以及恶意攻击等方方面面，有些力不从心。感觉需要往前迈一步了。需要更好解锁视频的方式了。

**Comment by zhuzhuor** [comment]
@LBYPatrick VPN 基本上就是 TCP/UDP 或者 IP 层的协议，不太能抗 DDoS 攻击，而且如 @yanggis 说的如果很多个用户一起保持 live TCP 连接的话，估计对服务器性能是个大考验

不过想法是正确的，可以解决现有的一些问题， 可以弄个服务器给自己用
