### ISSUE TITLE
路由器层面实现

### ISSUE THREAD

**Issue by liuhangcheng** [uku/Unblock-Youku#789]
请问如何在路由器层面实现代理 openwrt 日常听听QQ音乐

**Comment by yanggis** [comment]
这个暂时不讨论路由器怎么实现，因为OpenWRT用户太少，没有太大开发的必要。

**Comment by LBYPatrick** [comment]
@liuhangcheng 利用现有Unblock Youku资源的话, 国内你自己搭一个Unblock Youku的squid服务器用。不喜欢的话，直接搭SS用，openwrt是有shadowsocks可以用的

**Comment by liuhangcheng** [comment]
已经在一个whois ip是中国的服务器上搭建了ss,谢谢
