### ISSUE TITLE
bilibili视频海外加速的问题

### ISSUE THREAD

**Issue by fierywing** [uku/Unblock-Youku#790]
我发现如果开着unblockyouku看bilibili视频,  视频源地址是离我服务器最近的国内的cmcc源地址 这个地址对国外的连接性很差(经常没速度或者10多k的速度).
不开unblockyouku的情况下bilibili视频 会直接连在美国的tx.acgvideo.com这个源,这个源的速度国外访问的话感觉速度飞快(3-4M/s),
那么有没有过了ip检测后,直接连国外源的办法呢?

**Comment by LBYPatrick** [comment]
还是那句话，中国-日本-美国线路是最快的，你在日本搭一个VPN连过去，源是42.96.146.169,  速度能稳定在3MB/s,就是有点延迟(200+ms)

**Comment by wtjfree** [comment]
@LBYPatrick 懂抓包？ 能给推荐两个连接看看吗？

@Travical 我不怎么看bilibili不过腾讯好像解锁个视频也就100k之后就直连了。貌似存视频的服务器并不参与验证了。

**Comment by Travical** [comment]
@wtjfree bilibli也是解锁视频后直连,
但是因为用国内服务器过验证的原因,bilibili会认为在代理服务器的位置, 然后就分配到国内的cmcc服务器了,然后你直接就连到cmcc服务器了  
  如果不开代理 bilibili就会把你分配到海外的源

**Comment by wtjfree** [comment]
这样就有点纠结了. 肉身不在国内自然网速无法比. 但是ip如果是国外的岂不是看不了.囧

**Comment by LBYPatrick** [comment]
@wtjfree 不会，搭成VPN之后照样可以用Unblock-Youku

**Comment by wtjfree** [comment]
@LBYPatrick 也就是说所有视频流量都走VPN吧？

**Comment by LBYPatrick** [comment]
@wtjfree 对
