### ISSUE TITLE
Firefox 插件

### ISSUE THREAD

**Issue by chenzhekl** [uku/Unblock-Youku#792]
Hi，Firefox 正在逐步添加 WebExtensions 支持，Unblock Youku 是否有计划上架 Firefox 插件。

**Comment by Wilbeibi** [comment]
+1

**Comment by chenzhekl** [comment]
我做了一个简单的port，暂时有些粗糙，支持FF 57+。

https://addons.mozilla.org/zh-CN/firefox/addon/unblock-youku-firefox/

**Comment by 8tx81vb8rt8ci4whgk** [comment]
@chenzhekl 
Thanks for your addon! It works on Firefox for PC (Windows / macOS / Linux), but not for Android. Please refer to the issue I submitted in your GitHub repository (https://github.com/chenzhekl/unblock-youku-firefox).
