### ISSUE TITLE
哔哩哔哩客户端无法播放

### ISSUE THREAD

**Issue by vSsSv** [uku/Unblock-Youku#793]
遇到的问题：
客户端上显示：非常抱歉，根据版权方的要求，您所在的地区无法观看本番
但是我开着Drony用Chrome打开就没问题。可是浏览器B站每集只让看开头6分钟……
希望能够解决…不胜感激…不想抱着电脑补番啊～～～

地点：加拿大
Android：4.4.2
PAC：http://pac.uku.im/pac.pac
设置方法：通过系统自己的WiFi设置面板修改
uku.im/check测试结果：true
bilibili客户端：4.32.0
测试动画：男子高中生的日常

**Comment by gitlzh** [comment]
bilibili最近网页端似乎开启了全站https。不排除应用也走https的可能

**Comment by LBYPatrick** [comment]
建议还是采用IP暴力解锁的方式，例如cn-proxy或者使用亚洲国家的IP（日本有部分区域完全解锁，新加坡IP可以解锁例如RE:CREATORS或者干物妹小埋一二季这样的番剧，我室友卡了新加坡IP在看，我卡了日本的，速度都不错）。Unblock-Youku跟IOS越狱一样，并不总是有效的

**Comment by LBYPatrick** [comment]
多嘴一句，可以用电脑下好番之后通过FTP的方式把番剧传到手机上看，除了没有弹幕以外，其他都是完美的（很多字幕组的资源清晰度甚至比b站的1080P还好）
