### ISSUE TITLE
Bilibili上的非番剧视频加载问题

### ISSUE THREAD

**Issue by WilliamZY** [uku/Unblock-Youku#794]
Bilibili上的非番剧视频的加载速度非常慢, 坐标澳大利亚悉尼
看非番剧视频的时候,一般要么从头卡到尾或者只能加载出头一小段视频然后就卡在那里转圈了(完全没速度
试过Unblock-Youku的三种模式, 但结果都一样. 但是如果禁用Unblock-Youku之后加载速度就非常快, 5-6m/s的速度
在上面看到了一个issue也有说到不开Unblock-Youku以后速度飞快的现象
所以有没有办法手动设置让B站的普通视频不走Unblock-Youku呢?

**Comment by HaoyeTang** [comment]
同样的问题
标准模式下会有以下提示
`无法连接服务器或服务器返回异常 ([NetworkError] Exception: 3104 Failed to fetch)`
精简模式及关闭后正常工作
虽然没有很大影响不过出于方便性着想请务必修复谢谢

**Comment by ydeng19** [comment]
相同问题，
加载普通视屏的时候出现:
加载视频地址。。。。完成
加载视频内容。。。。失败
服务器返回异常 NetworkError, HttpStatusCodeInvalid: 466
然后它尝试重新加载又失败：
加载视频地址。。。。完成
加载视频内容。。。。失败
无法连接服务器或服务器返回异常 NetworkError Exception 3104 Failed to Fetch

466这个error code完全没见过啊。。。。

对比失败和成功的文件路径：
失败的时候会先尝试下FLV，然后尝试MP4：
先浙江温州电信？报466，自己尝试链接是453
https://cn-zjwz3-dx-v-04.acgvideo.com/vg2/f/20/31648251-1-64.flv?expires=1518347700&platform=pc&ssig=Cyl4qfXfUoAQnDifvlB72g&oi=2015070164&nfa=iKQJtLw3Fy5f05Q/mDvFYw==&dynamic=1&hfa=2025007496&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=
再浙江温州移不动？？还是报466，自己尝试链接是453
https://cn-zjwz-cmcc-v-09.acgvideo.com/vg5/6/2e/31648251-1-16.mp4?expires=1518347700&platform=pc&ssig=R3n1_-iVnMZNKV7-j1iskQ&oi=2015070164&nfa=iKQJtLw3Fy5f05Q/mDvFYw==&dynamic=1&hfa=2025007500&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=

关闭unblock youku后一次成功为flv，自己尝试可直接下载文件。。。
https://tx.acgvideo.com/51/82/31648251/31648251-1-64.flv?txTime=1518347689&platform=pc&txSecret=3043d2825dc2168f3142d6d13873becd&oi=3093467086&rate=132848&hfb=b99ffc3c5c68f00a33123bb25f882d5b

**Comment by zhuzhuor** [comment]
稍微看了下这问题，发现只需要通过代理服务器，就会出现这问题
例如不用 Unblock Youku，直接给浏览器弄上全局代理，访问也是出现同样的错误信息

具体的细节是，通过代理服务器访问
`https://interface.bilibili.com/v2/playurl?cid=3542800&appkey=84956560bc028eb7&otype=json&type=&quality=0&qn=0&sign=301dd326294b44b126e06992dbb82fd8`

会得到类似这样的 URL
`https://cn-zjwz-cmcc-v-09.acgvideo.com`
再访问就会报错

不用代理访问`interface.bilibili.com`，会得到不同的 URL，就不会出错
`http://ws.acgvideo.com/b/ea/3542800-1.flv`

**Comment by zhuzhuor** [comment]
结论是貌似 http://cn-sdyt-cu-v-05.acgvideo.com 这样的域名内容一直都有问题，b 站没有配置好？

我们在 Unblock Youku 如何处理这问题还得想想 technical solution
