### ISSUE TITLE
关于“在美团云架设自己的 Unblock Youku 代理服务器” 的新问题

### ISSUE THREAD

**Issue by yang15** [uku/Unblock-Youku#799]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: NAN

请具体描述您遇到的问题（例如有问题的视频网址）：NAN

您所处的国家或地区：USA

版主看在我也是UW 毕业的份上，请务必回答我的XX问题啊。。。。。
1. 我已经创建了美团云主机，然而只显示内网IP, 并没有公网IP. 我又重新检查了一遍提交创建服务器的过程，并没有用到开通公网的选项。莫非应该选择“独享云主机”而不是“云主机”？
2. curl -o /opt/crx_url_list.txt http://pac.uku.im/regex 显示time out 是不是已经过期了？有没有新更新呢？

跪谢！！

**Comment by G-F-CH** [comment]
1.我没有用过美团云，但是有个疑问，没有公网IP，你怎么远程登录你的主机的？
2.在你主机上ping pac.uku.im呢？

**Comment by yang15** [comment]
1. 问题就在于我不能远程登陆，只能用“终端”。 我刚才又发现一个新的更新。就像AWS一样, 浮动IP要绑定。现在有了外网IP，然而依旧ping
不通。是不是美团云创建的IP不支持国外访问?
2. 本地ping pac.uku.im是通的

**Comment by G-F-CH** [comment]
https://github.com/uku/Unblock-Youku/wiki/%E5%9C%A8%E7%BE%8E%E5%9B%A2%E4%BA%91%E6%9E%B6%E8%AE%BE%E8%87%AA%E5%B7%B1%E7%9A%84-Unblock-Youku-%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E5%99%A8
你是参照这个教程安装的吗？
这个教程好像没有你类似的问题。

**Comment by G-F-CH** [comment]
另外，无法连接http://pac.uku.im/regex也不是问题。你把这个文件下载下来，保存到本地也行。以后手动更新就是了。

**Comment by WatcherOfTheWorld** [comment]
其实用Shadowsocks做代理是最方便的。。。。
