### ISSUE TITLE
能否将pac文件加入repo？

### ISSUE THREAD

**Issue by Vancion** [uku/Unblock-Youku#801]
我知道可以在http://pac.uku.im/pac.pac找到pac文件，但是在repo里好像找不到。请问如果想提交对pac文件的修改需要怎么做呢？

uwp的网易云音乐原来一直搞不定（自建国内ss服务器+本机pac），后来加了如下两条规则就可以了
music.126.net
music.126.net.gccdn.net

https://bbs.uku.im/t/topic/1225

**Comment by ShuangyiTong** [comment]
http://pac.uku.im/pac.pac上的这个pac安卓的bilibili用不了。然后使用chrome/proxy.js里的setup_proxy生成的pac_data放到安卓里bilibili就好用了。我也建议放一个pac到repo里。
