### ISSUE TITLE
无法观看搜狐视频，麻煩各位幫忙

### ISSUE THREAD

**Issue by tttransform** [uku/Unblock-Youku#802]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome Unblock Youku
请具体描述您遇到的问题（例如有问题的视频网址）：
无法观看搜狐视频(有VIP帳戶)
https://film.sohu.com/album/9366408.html
您所处的国家或地区：
香港

**Comment by m31317015** [comment]
我也是香港，DNS好像又下线了。
http://status.uku.im
