### ISSUE TITLE
能否限制Extension Permission，只允许访问特定网站的数据

### ISSUE THREAD

**Issue by wonderyl** [uku/Unblock-Youku#808]
我在使用公司的电脑，由于unlock-youku的permission允许访问任意网站的数据，公司管理员禁止了这个插件。
能否在unblock-youku的permission里指明其需要访问特定网站的数据，这样可以消除安全隐患。

**Comment by zhuzhuor** [comment]
扩展程序需要有用 chrome.proxy 设置代理服务器的权限，这个权限会让浏览器提示允许访问任意网页的数据，这个暂时没什么解决办法

我们已经把安全设计的非常谨慎，代理的网址都是直接 hard code 在浏览器插件里，不是从网上自动下载的

**Comment by wonderyl** [comment]
我不是很熟悉chrom permission, 但是manifest.json里的声明是这样的：
https://github.com/uku/Unblock-Youku/blob/1731113a421bd7cf3a1a61fe63fa4f15daecc6b5/manifest.json
"permissions": [
    "proxy",
    "webRequest",
    "webRequestBlocking",
    "storage",
    "tabs",
    **_"http://\*/\*",
    "https://\*/\*"_**
  ],
我怀疑是不是这个声明导致插件可以为任何网站设置代理。如果把这个限制到youku, qq等支持的网站就会避免这个问题。

**Comment by zhuzhuor** [comment]
你可以自己试试看，删掉了还是有同样的 permission 提示
只要有了 "proxy" 或 "webRequest" 就会提示

那两个是给 content script 用的，一个一个网址加上去的话太麻烦了
而且每次新加一个网址扩展程序升级用户可能得手动 enable 一下才能继续用

**Comment by zhuzhuor** [comment]
另外，代理是给 Chrome 全局设置，并没有给 "网站设置代理" 设置代理一说。但是虽然 Unblock Youku 设置了全局代理，但是实际上是只有在白名单里的网址才会被代理，你有兴趣可以读读代码
