### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by williewillus** [uku/Unblock-Youku#810]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Firefox 57, Windows 10

请具体描述您遇到的问题（例如有问题的视频网址）：Firefox now supports WebExtension API's (same as Chrome), so it shouldn't be too difficult to support Firefox at the same time.

您所处的国家或地区：en_US

**Comment by yan12125** [comment]
https://github.com/uku/Unblock-Youku/issues/792#issuecomment-334166512

QQ音樂可用
