### ISSUE TITLE
爱奇艺 DARLING in the FRANXX 不可看

### ISSUE THREAD

**Issue by ydeng19** [uku/Unblock-Youku#812]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome 插件， Chrome 版本63.0.3239.132

请具体描述您遇到的问题（例如有问题的视频网址）：标准模式下 DARLING in the FRANXX 全集都不可看，如第一集http://www.iqiyi.com/v_19rrewimn0.html ，显示的错误是“当前平台暂无法播放哦~”或“所在地区无法观看”，但是同时其他独播新番如爆肝工程师和高木同学可以看。如切换到关闭模式，则全部显示“所在地区无法播放”，甚至连http://www.iqiyi.com/dongman/ 爱奇艺动漫主页都无法打开，报404

您所处的国家或地区：美国

**Comment by ydeng19** [comment]
有爱奇艺会员，但是登不登陆都一样

**Comment by zhuzhuor** [comment]
有意思，这个错误提示还是第一次看到

试了试把整个网站代理了都不行，估计是只能用 iqiyi 的 app 观看？

**Comment by ydeng19** [comment]
下了app也看不了，看来得试试VPN加app或者代理加APP。。。奇怪的是国内可以网页看啊。。。。
另外最近B站在标准模式下普通视频完全看不了了,我再去开个issue吧

**Comment by ydeng19** [comment]
https://zhuanlan.zhihu.com/p/33677892
2月3日，爱奇艺独播新番《DARLINGin the FRANX》（国内戏称“国家队”）遭举报下架。
T_T我逗比了。。。。
