### ISSUE TITLE
bilibili 需要改 static.hdslb.com dns

### ISSUE THREAD

**Issue by colinfang** [uku/Unblock-Youku#814]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

chrome, unblock youku

请具体描述您遇到的问题（例如有问题的视频网址）：

无法连接 static.hdslb.com

您所处的国家或地区：
UK

我试着 添加 以下几行，没有用。

```js
unblock_youku.chrome_proxy_urls = unblock_youku.redirect_urls.concat([
    'https://static.hdslb.com/*',
    ....
```

最终需要修改 etc/hosts
```
61.155.221.135    static.hdslb.com
```

**Comment by zhuzhuor** [comment]
多谢！这个是  #794  的解决办法吗？

**Comment by colinfang** [comment]
我也不知道。在我这里只需要修改这一行dns，都不需要装unblock youku
感觉是  static.hdslb.com 的 cdn 禁了我。

**Comment by theandychung** [comment]
我是海外firefox的使用者。修改dns後還是需要用unblock youku (full)。
