### ISSUE TITLE
app proxy type 选择问题

### ISSUE THREAD

**Issue by xiaozibuxiao** [uku/Unblock-Youku#815]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Drony app Pac 网站
请具体描述您遇到的问题（例如有问题的视频网址）：在安卓setting wifi 的时候， 选择Proxy Type之中没有proxy选项，应该选择什么，4个选项分别是plain,https,socks4a,socks5.非常感谢

您所处的国家或地区：美国

**Comment by tommyzhaozbh** [comment]
部分非原生安卓系统以及5.0以下的系统是没有设定pac功能的，如果没有则需要搭配drony使用，或者直接固定IP以修改DNS。
