### ISSUE TITLE
网页看腾讯视频不行，安卓客户端行

### ISSUE THREAD

**Issue by kahwei312** [uku/Unblock-Youku#816]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: PAC 

请具体描述您遇到的问题（例如有问题的视频网址）：浏览器浏览腾讯视频提示版权，客户端却可以看， ipservice.163.com/isFromMainland 原本提示true，浏览器提示有版权后我回去刷新变false 了

您所处的国家或地区：马来西亚 新山 靠近新加坡

这个到底什么回事啊，求助。我用DNS也一样不能看。

系统:安卓(Android)

**Comment by kahwei312** [comment]
其他还可以正常浏览，只不过有些网站很慢

**Comment by zhuzhuor** [comment]
PAC 受限制比较多，并不是很好用
推荐使用 Chrome 插件或者 DNS
