### ISSUE TITLE
海外的路由器上设置自建非转发unblock youku dns

### ISSUE THREAD

**Issue by michael-jpn** [uku/Unblock-Youku#817]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:dns

请具体描述您遇到的问题（例如有问题的视频网址）：海外的路由器上设置dns以及自建dns服务

您所处的国家或地区：JP

目前我在日本使用dd-wrt的路由器添加unblock youku的dns服务，
使得所有连接这台路由器的设备，包括手机平板和电脑都能使用unblock youku的dns服务。
好处就是不用每一台设备都设置。
当然有时候会有不稳定，想请教如何在中国国内自建unblock youku的dns服务？（中国国内有电脑和服务器等资源）

另外自己有3台安装了openwrt的路由器在中国国内，都安装了softether vpn做vpn服务器，在日本连接vpn后看视频上网等速度还能接受，当然如果能将这3台路由器当成dns服务器是最好...

目前：
设备<->路由器（有线，无线）dns设置（unblock youku dns）<->外网

设想：
设备<->路由器（有线，无线）dns设置（自己在国内的dns服务器，非转发到unblock youku dns）<->外网

**Comment by zhuzhuor** [comment]
@yanggis

**Comment by yanggis** [comment]
纯粹依赖DNS现在能解锁的视频很少了，尤其是对移动端设备，所以没太大意义做这个。

**Comment by glucee** [comment]
直接在路由器上实现Unblock Yoku：https://github.com/gxfxyz/unblockchn
或者直接在任何一台局域网上实现网关：https://github.com/glucee/unblockyouku_gateway/
