### ISSUE TITLE
https://secure.uku.im:8443/ 挂了？

### ISSUE THREAD

**Issue by ydeng19** [uku/Unblock-Youku#818]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Chrome

请具体描述您遇到的问题（例如有问题的视频网址）：proxy 无效，无法连接https://secure.uku.im:8443/

您所处的国家或地区：
美国

**Comment by ydeng19** [comment]
今天起来发现插件失效。。。发现无法访问secure.uku.im:8443
Unblock test failed! Invalid config or server not working properly.
是服务器挂了么？

**Comment by jiakaiz** [comment]
Same issue here.

**Comment by zhuzhuor** [comment]
今天服务器有点问题，已经在恢复了
可以再试试看，有问题欢迎再来反馈，多谢！

**Comment by ydeng19** [comment]
已确认修复~谢谢作者！

**Comment by ydeng19** [comment]
看了一集bilibili后又挂了。。。。不太稳定啊。。。

**Comment by BraveHorseGogogo** [comment]
@ydeng19 请问你看不了的bilibili链接是什么？

**Comment by ydeng19** [comment]
https://www.bilibili.com/bangumi/play/ep192294 现在貌似稳定了
