### ISSUE TITLE
能不能伪装成其他地区的用户

### ISSUE THREAD

**Issue by vczh** [uku/Unblock-Youku#822]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome插件

请具体描述您遇到的问题（例如有问题的视频网址）：B站番剧，只限制大陆观看的能观看，其他地方的不行

您所处的国家或地区：美国

**Comment by huming2207** [comment]
轮子哥好哇，
可以试试把他们的PAC的IP改个其他地区的IP？没试过但理论可行吧

**Comment by vczh** [comment]
@huming2207 没看见哪里可以改（

**Comment by lonelykid** [comment]
@vczh 可以自定义proxy backend的，没必要用他们提供的，右键option。

**Comment by lonelykid** [comment]
@vczh 那你自己买一个或者搭一个台湾的代理服务器呗...上面 @huming2207 说的pac文件在这里，http://pac.uku.im/pac.pac，你看看就明白了。直接用这个pac我感觉也差不多。

**Comment by huming2207** [comment]
楼上说得没错，台湾服务器的话，搞个google cloud台湾区就行了。然后用搭个http代理，把IP填进pac里即可。
