### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by MingJin-Lu** [uku/Unblock-Youku#824]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome 插件
请具体描述您遇到的问题（例如有问题的视频网址）：
Bilibili 无法观看版权视频
您所处的国家或地区：
美国

**Comment by zhuzhuor** [comment]
https://status.uku.im/  服务器现在的状态

**Comment by MingJin-Lu** [comment]
问题已经解决
