### ISSUE TITLE
Proxy Auto-Config does not work

### ISSUE THREAD

**Issue by placetne** [uku/Unblock-Youku#831]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: PAC

请具体描述您遇到的问题（例如有问题的视频网址）：

There is a problem when using the Proxy Auto-Config http://pac.uku.im/pac.pac for Unblock Youku on IOS/Android/Firefox. Directions are at https://bbs.uku.im/t/topic/27.

It does not work anymore for IOS/Android/Firefox even though the Chrome extension works.  When I go to http://ipservice.163.com/isFromMainland , it returns false.

When the pac.pac returns a proxy, it returns "PROXY proxy.uku.im:443; DIRECT;". But "proxy.uku.im:443" seems to be turned off. Instead it should return "HTTPS secure.uku.im:8443; DIRECT;" because that still works.

您所处的国家或地区：USA

**Comment by myahmao** [comment]
even if changed to HTTPS "secure.uku.im:8443", it still not working.
