### ISSUE TITLE
B站新番看不了

### ISSUE THREAD

**Issue by taoyuan1994** [uku/Unblock-Youku#835]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome插件
请具体描述您遇到的问题（例如有问题的视频网址）：
新番好像都看不了，例如：
https://www.bilibili.com/bangumi/play/ep250435/?spm_id_from=333.334.bili_bangumi.24
您所处的国家或地区：
美国，华盛顿特区

**Comment by idomori** [comment]
不只是新番，标准模式下浏览b站所有视频都会502 503

**Comment by COTTONPADS** [comment]
我也是呜呜呜呜

**Comment by Szcnorya** [comment]
B站好像对视频内容flv存储的cdn服务器acgvideo.com也加上了IP限制，现在这个服务器需要中国IP才能访问，Unlock Youku应该是被Ban IP了。对bangumi.bilibili.com和acgvideo.com挂代理回中国实测有效。

**Comment by weisheng4321** [comment]
unblock boundary 能做到，插件应该可以修复这问题

**Comment by leonhardt913** [comment]
使用html5看新番会出现 NetworkError Expection 3104 failed to fetch
换回flash播放器 可以看但是加载非常的慢

您所处的国家或地区：Virginia
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome插件

**Comment by jubeater** [comment]
> unblock boundary 能做到，插件应该可以修复这问题

哥们 那东西貌似后台挖矿

**Comment by Szcnorya** [comment]
如果视频流走Unlock Youku的服务器的话是可行的（前提是Unlock Youku的服务器没有被Ban IP），但是用户数量一多共享代理服务器带宽的情况下服务质量会非常差。自己有代理的话走自己的代理是最优选择，因为是反向翻墙普通代理就好，并不需要加密服务。

**Comment by zgfn** [comment]
> > unblock boundary 能做到，插件应该可以修复这问题
> 
> 哥们 那东西貌似后台挖矿

是不是挖矿看看CPU和GPU使用情况就知道了。别啥都挖矿

**Comment by jubeater** [comment]
> > > unblock boundary 能做到，插件应该可以修复这问题
> > 
> > 
> > 哥们 那东西貌似后台挖矿
> 
> 是不是挖矿看看CPU和GPU使用情况就知道了。别啥都挖矿

我以前在chrome 商店插件评价里面看见的 难道版本更新了？

**Comment by cz1997** [comment]
请问现在bi站不用158也能看吗？之前在外国不用158或者youku插件也能看了，现在不知道在外国还能不用158也能看吗？
