### ISSUE TITLE
愛奇藝無法使用

### ISSUE THREAD

**Issue by yeyetae** [uku/Unblock-Youku#840]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome 插件-unblock youku 3.8.7 

请具体描述您遇到的问题（例如有问题的视频网址）：https://www.iqiyi.com/v_19rra64i9c.html

您所处的国家或地区：香港
<img width="1031" alt="2018-12-30 1 11 34" src="https://user-images.githubusercontent.com/46247355/50540608-e9ca5d00-0bcf-11e9-8e78-4bb3fc66fe58.png">

**Comment by walkingsparrow** [comment]
从昨天晚上开始，我也看不了了。

**Comment by leoaction** [comment]
+1

**Comment by SaguruHakuba** [comment]
是的，跨年直播也看不了。。

**Comment by skripp** [comment]
我这儿也一样。
