### ISSUE TITLE
路由器实现unblock-youku功能

### ISSUE THREAD

**Issue by glucee** [uku/Unblock-Youku#842]
由于很多设备无法设置PAC，现在想让家里所有的设备无需设置，连上路由器就可以直接使用unblock-youku，目前考虑几个想法：

1. 局域网内某设备作为网关服务器，上面使用iptables分流，识别出来走国内，否则直连，类似PAC。设备需要设置成该设备的IP作为网关。这里涉及到把PAC的规则转成iptables的规则。
2. 直接路由器上使用iptables分流，这时候需要一个能够支持很多功能的路由器。

有没有什么更好的想法？

**Comment by glucee** [comment]
@yanggis

**Comment by glucee** [comment]
已经解决，见
https://github.com/glucee/unblockyouku_gateway

**Comment by cz1997** [comment]
@glucee 有没有简易说明，我不懂电脑术语，有没有连电脑白痴都可以懂的说明？比如我！

**Comment by ntgeralt** [comment]
该github项目似乎播放视频属于直连状态，为何上面有提到需要shadowsocks服务端。

**Comment by glucee** [comment]
> 该github项目似乎播放视频属于直连状态，为何上面有提到需要shadowsocks服务端。

主要是一些域名解析需要到中国服务器上进行（假装在国内），对一些手机应用，有些是必须直连。
