### ISSUE TITLE
加入https://manga.bilibili.com/*?

### ISSUE THREAD

**Issue by johnmave126** [uku/Unblock-Youku#845]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
Chrome 插件
请具体描述您遇到的问题（例如有问题的视频网址）：
似乎做了区域限制，区域外post https://manga.bilibili.com/twirp/comic.v1.Comic/ComicDetail?device=h5&platform=h5 时返回的列表为空
您所处的国家或地区：United States

**Comment by cs10108** [comment]
支持 最近發現終於加入網頁版 最好更新

**Comment by markx** [comment]
我试了试在本地把这个加入chrome_proxy_urls列表里，结果ERR_TUNNEL_CONNECTION_FAILED了。请问是不是我的操作有误？
