### ISSUE TITLE
B站版权番永远处于菊花状态播放不了 （2019.3）

### ISSUE THREAD

**Issue by vczh** [uku/Unblock-Youku#846]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Chrome + Unblock Youku  3.8.9 默认设置

请具体描述您遇到的问题（例如有问题的视频网址）：B站版权番永远处于菊花状态播放不了，不管是哪个都不行，e.g. https://www.bilibili.com/bangumi/play/ep65786 

您所处的国家或地区：美国

**Comment by UnbearableFate** [comment]
轮子哥也用这个插件啊。我在日本也是同样的问题，希望开发者早点解决吧。

**Comment by vczh** [comment]
@UnbearableFate 不会是他的代理机器被干了吧

**Comment by zhuzhuor** [comment]
需要修改 hosts 才行，见 https://bbs.uku.im/t/topic/3704/96

**Comment by zhuzhuor** [comment]
哇，大名鼎鼎的轮子哥，也帮我们用户解决解决技术问题吧！

**Comment by TransLive** [comment]
B站用某個專門針對 B 站的油猴腳本效果更好

**Comment by vczh** [comment]
最近试了一下感觉又可以了

**Comment by LBYPatrick** [comment]
先回去玩Hitman啦轮子哥
