### ISSUE TITLE
bilibili版权纪录片无法播放

### ISSUE THREAD

**Issue by MysteriousMing** [uku/Unblock-Youku#849]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Chrome插件

请具体描述您遇到的问题（例如有问题的视频网址）：
版权纪录片
https://www.bilibili.com/bangumi/play/ep120942?from=search&seid=13212593671713595010

standard模式下提醒：加载视频内容失败，无法连接到服务器
lite模式下提醒：非常抱歉，根据版权方要求，您所在的地区无法观看本片

您所处的国家或地区：英国

**Comment by brlala** [comment]
面临着同样一个问题，安装了插件后B站加载不了视频

**Comment by liangjiapei** [comment]
我也有一样的问题，在美国，用该插件无法播放bilibili有版权的视频

**Comment by anzeye** [comment]
hdslb.com   把这个加进代理列表就可以了。

**Comment by xiegeyang** [comment]
这个Issue已经不能reproduce了是不是可以close了
