### ISSUE TITLE
未来是否有移植到Safari 14的计划？

### ISSUE THREAD

**Issue by BrushXue** [uku/Unblock-Youku#853]
能否支持macOS和iOS？谢谢！

**Comment by zmingxie** [comment]
An old discussion on this topic can be found here: https://github.com/uku/Unblock-Youku/issues/514

**Comment by valkjsaaa** [comment]
+1  Safari 14 supports almost the same APIs as chrome extensions

**Comment by valkjsaaa** [comment]
Upon closer inspection, it seems that Safari don't yet support `browser.proxy` API. So I don't think Unblock-Youku can be ported to Safari 14.

**Comment by valkjsaaa** [comment]
It seems that the LITE mode works though.
