### ISSUE TITLE
Bilibili 番剧不好用

### ISSUE THREAD

**Issue by czhang-trinity** [uku/Unblock-Youku#859]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:
 Chrome 插件
请具体描述您遇到的问题（例如有问题的视频网址）：
哔哩哔哩番剧不好用 一直显示 download error: Media Segment Error
您所处的国家或地区：
USA

**Comment by x-ji** [comment]
好像就是几天前开始有这个情况

**Comment by GZGavinZhao** [comment]
火狐浏览器85，同样的问题。我这边不只是慢的问题，根本看不了。
是不是服务器被屏蔽了？

**Comment by x-ji** [comment]
8 号晚上（欧洲时间）倒是正常了 现在好像又不行了？

**Comment by KanzakiYui** [comment]
可以用了

**Comment by TianyiShi2001** [comment]
又不行了
